/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypographyIndexRouteImport } from './routes/typography/index'
import { Route as TooltipIndexRouteImport } from './routes/tooltip/index'
import { Route as ToggleIndexRouteImport } from './routes/toggle/index'
import { Route as ToggleGroupIndexRouteImport } from './routes/toggle-group/index'
import { Route as ToastIndexRouteImport } from './routes/toast/index'
import { Route as TabsIndexRouteImport } from './routes/tabs/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as StackIndexRouteImport } from './routes/stack/index'
import { Route as SpacingIndexRouteImport } from './routes/spacing/index'
import { Route as SliderIndexRouteImport } from './routes/slider/index'
import { Route as SkeletonIndexRouteImport } from './routes/skeleton/index'
import { Route as SidebarIndexRouteImport } from './routes/sidebar/index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase/index'
import { Route as SheetIndexRouteImport } from './routes/sheet/index'
import { Route as SeparatorIndexRouteImport } from './routes/separator/index'
import { Route as SelectIndexRouteImport } from './routes/select/index'
import { Route as ScrollAreaIndexRouteImport } from './routes/scroll-area/index'
import { Route as ResponsiveGridIndexRouteImport } from './routes/responsive-grid/index'
import { Route as ResizableIndexRouteImport } from './routes/resizable/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as PopoverIndexRouteImport } from './routes/popover/index'
import { Route as PaginationIndexRouteImport } from './routes/pagination/index'
import { Route as NativeSelectIndexRouteImport } from './routes/native-select/index'
import { Route as MessageIndexRouteImport } from './routes/message/index'
import { Route as MarkerIndexRouteImport } from './routes/marker/index'
import { Route as ListIndexRouteImport } from './routes/list/index'
import { Route as KbdIndexRouteImport } from './routes/kbd/index'
import { Route as ItemIndexRouteImport } from './routes/item/index'
import { Route as IconIndexRouteImport } from './routes/icon/index'
import { Route as HoverCardIndexRouteImport } from './routes/hover-card/index'
import { Route as GridIndexRouteImport } from './routes/grid/index'
import { Route as FormControlsIndexRouteImport } from './routes/form-controls/index'
import { Route as EmptyIndexRouteImport } from './routes/empty/index'
import { Route as DropzoneIndexRouteImport } from './routes/dropzone/index'
import { Route as DropdownMenuIndexRouteImport } from './routes/dropdown-menu/index'
import { Route as DividerIndexRouteImport } from './routes/divider/index'
import { Route as DirectionIndexRouteImport } from './routes/direction/index'
import { Route as DialogIndexRouteImport } from './routes/dialog/index'
import { Route as ContainerIndexRouteImport } from './routes/container/index'
import { Route as ColorTokensIndexRouteImport } from './routes/color-tokens/index'
import { Route as CollapsibleIndexRouteImport } from './routes/collapsible/index'
import { Route as CodeBlockIndexRouteImport } from './routes/code-block/index'
import { Route as CarouselIndexRouteImport } from './routes/carousel/index'
import { Route as CardIndexRouteImport } from './routes/card/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as ButtonIndexRouteImport } from './routes/button/index'
import { Route as BubbleIndexRouteImport } from './routes/bubble/index'
import { Route as BreadcrumbIndexRouteImport } from './routes/breadcrumb/index'
import { Route as BentoIndexRouteImport } from './routes/bento/index'
import { Route as BadgeIndexRouteImport } from './routes/badge/index'
import { Route as AvatarIndexRouteImport } from './routes/avatar/index'
import { Route as AspectRatioIndexRouteImport } from './routes/aspect-ratio/index'
import { Route as AlertIndexRouteImport } from './routes/alert/index'
import { Route as AlertDialogIndexRouteImport } from './routes/alert-dialog/index'
import { Route as AiElementsIndexRouteImport } from './routes/ai-elements/index'
import { Route as AccordionIndexRouteImport } from './routes/accordion/index'
import { Route as AiElementsToolIndexRouteImport } from './routes/ai-elements/tool/index'
import { Route as AiElementsTaskIndexRouteImport } from './routes/ai-elements/task/index'
import { Route as AiElementsSuggestionsIndexRouteImport } from './routes/ai-elements/suggestions/index'
import { Route as AiElementsSourcesIndexRouteImport } from './routes/ai-elements/sources/index'
import { Route as AiElementsShimmerIndexRouteImport } from './routes/ai-elements/shimmer/index'
import { Route as AiElementsReasoningIndexRouteImport } from './routes/ai-elements/reasoning/index'
import { Route as AiElementsPromptInputIndexRouteImport } from './routes/ai-elements/prompt-input/index'
import { Route as AiElementsPlanIndexRouteImport } from './routes/ai-elements/plan/index'
import { Route as AiElementsMessageIndexRouteImport } from './routes/ai-elements/message/index'
import { Route as AiElementsFullChatIndexRouteImport } from './routes/ai-elements/full-chat/index'
import { Route as AiElementsConversationIndexRouteImport } from './routes/ai-elements/conversation/index'
import { Route as AiElementsConfirmationIndexRouteImport } from './routes/ai-elements/confirmation/index'
import { Route as AiElementsChainOfThoughtIndexRouteImport } from './routes/ai-elements/chain-of-thought/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyIndexRoute = TypographyIndexRouteImport.update({
  id: '/typography/',
  path: '/typography/',
  getParentRoute: () => rootRouteImport,
} as any)
const TooltipIndexRoute = TooltipIndexRouteImport.update({
  id: '/tooltip/',
  path: '/tooltip/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToggleIndexRoute = ToggleIndexRouteImport.update({
  id: '/toggle/',
  path: '/toggle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToggleGroupIndexRoute = ToggleGroupIndexRouteImport.update({
  id: '/toggle-group/',
  path: '/toggle-group/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToastIndexRoute = ToastIndexRouteImport.update({
  id: '/toast/',
  path: '/toast/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const StackIndexRoute = StackIndexRouteImport.update({
  id: '/stack/',
  path: '/stack/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacingIndexRoute = SpacingIndexRouteImport.update({
  id: '/spacing/',
  path: '/spacing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SliderIndexRoute = SliderIndexRouteImport.update({
  id: '/slider/',
  path: '/slider/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkeletonIndexRoute = SkeletonIndexRouteImport.update({
  id: '/skeleton/',
  path: '/skeleton/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/sidebar/',
  path: '/sidebar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetIndexRoute = SheetIndexRouteImport.update({
  id: '/sheet/',
  path: '/sheet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeparatorIndexRoute = SeparatorIndexRouteImport.update({
  id: '/separator/',
  path: '/separator/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectIndexRoute = SelectIndexRouteImport.update({
  id: '/select/',
  path: '/select/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollAreaIndexRoute = ScrollAreaIndexRouteImport.update({
  id: '/scroll-area/',
  path: '/scroll-area/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsiveGridIndexRoute = ResponsiveGridIndexRouteImport.update({
  id: '/responsive-grid/',
  path: '/responsive-grid/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizableIndexRoute = ResizableIndexRouteImport.update({
  id: '/resizable/',
  path: '/resizable/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopoverIndexRoute = PopoverIndexRouteImport.update({
  id: '/popover/',
  path: '/popover/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginationIndexRoute = PaginationIndexRouteImport.update({
  id: '/pagination/',
  path: '/pagination/',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeSelectIndexRoute = NativeSelectIndexRouteImport.update({
  id: '/native-select/',
  path: '/native-select/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageIndexRoute = MessageIndexRouteImport.update({
  id: '/message/',
  path: '/message/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkerIndexRoute = MarkerIndexRouteImport.update({
  id: '/marker/',
  path: '/marker/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListIndexRoute = ListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const KbdIndexRoute = KbdIndexRouteImport.update({
  id: '/kbd/',
  path: '/kbd/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIndexRoute = ItemIndexRouteImport.update({
  id: '/item/',
  path: '/item/',
  getParentRoute: () => rootRouteImport,
} as any)
const IconIndexRoute = IconIndexRouteImport.update({
  id: '/icon/',
  path: '/icon/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoverCardIndexRoute = HoverCardIndexRouteImport.update({
  id: '/hover-card/',
  path: '/hover-card/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/grid/',
  path: '/grid/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormControlsIndexRoute = FormControlsIndexRouteImport.update({
  id: '/form-controls/',
  path: '/form-controls/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyIndexRoute = EmptyIndexRouteImport.update({
  id: '/empty/',
  path: '/empty/',
  getParentRoute: () => rootRouteImport,
} as any)
const DropzoneIndexRoute = DropzoneIndexRouteImport.update({
  id: '/dropzone/',
  path: '/dropzone/',
  getParentRoute: () => rootRouteImport,
} as any)
const DropdownMenuIndexRoute = DropdownMenuIndexRouteImport.update({
  id: '/dropdown-menu/',
  path: '/dropdown-menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const DividerIndexRoute = DividerIndexRouteImport.update({
  id: '/divider/',
  path: '/divider/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionIndexRoute = DirectionIndexRouteImport.update({
  id: '/direction/',
  path: '/direction/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogIndexRoute = DialogIndexRouteImport.update({
  id: '/dialog/',
  path: '/dialog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerIndexRoute = ContainerIndexRouteImport.update({
  id: '/container/',
  path: '/container/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorTokensIndexRoute = ColorTokensIndexRouteImport.update({
  id: '/color-tokens/',
  path: '/color-tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollapsibleIndexRoute = CollapsibleIndexRouteImport.update({
  id: '/collapsible/',
  path: '/collapsible/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeBlockIndexRoute = CodeBlockIndexRouteImport.update({
  id: '/code-block/',
  path: '/code-block/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselIndexRoute = CarouselIndexRouteImport.update({
  id: '/carousel/',
  path: '/carousel/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIndexRoute = CardIndexRouteImport.update({
  id: '/card/',
  path: '/card/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonIndexRoute = ButtonIndexRouteImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => rootRouteImport,
} as any)
const BubbleIndexRoute = BubbleIndexRouteImport.update({
  id: '/bubble/',
  path: '/bubble/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreadcrumbIndexRoute = BreadcrumbIndexRouteImport.update({
  id: '/breadcrumb/',
  path: '/breadcrumb/',
  getParentRoute: () => rootRouteImport,
} as any)
const BentoIndexRoute = BentoIndexRouteImport.update({
  id: '/bento/',
  path: '/bento/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeIndexRoute = BadgeIndexRouteImport.update({
  id: '/badge/',
  path: '/badge/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarIndexRoute = AvatarIndexRouteImport.update({
  id: '/avatar/',
  path: '/avatar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AspectRatioIndexRoute = AspectRatioIndexRouteImport.update({
  id: '/aspect-ratio/',
  path: '/aspect-ratio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIndexRoute = AlertIndexRouteImport.update({
  id: '/alert/',
  path: '/alert/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertDialogIndexRoute = AlertDialogIndexRouteImport.update({
  id: '/alert-dialog/',
  path: '/alert-dialog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsIndexRoute = AiElementsIndexRouteImport.update({
  id: '/ai-elements/',
  path: '/ai-elements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionIndexRoute = AccordionIndexRouteImport.update({
  id: '/accordion/',
  path: '/accordion/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsToolIndexRoute = AiElementsToolIndexRouteImport.update({
  id: '/ai-elements/tool/',
  path: '/ai-elements/tool/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsTaskIndexRoute = AiElementsTaskIndexRouteImport.update({
  id: '/ai-elements/task/',
  path: '/ai-elements/task/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsSuggestionsIndexRoute =
  AiElementsSuggestionsIndexRouteImport.update({
    id: '/ai-elements/suggestions/',
    path: '/ai-elements/suggestions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiElementsSourcesIndexRoute = AiElementsSourcesIndexRouteImport.update({
  id: '/ai-elements/sources/',
  path: '/ai-elements/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsShimmerIndexRoute = AiElementsShimmerIndexRouteImport.update({
  id: '/ai-elements/shimmer/',
  path: '/ai-elements/shimmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsReasoningIndexRoute =
  AiElementsReasoningIndexRouteImport.update({
    id: '/ai-elements/reasoning/',
    path: '/ai-elements/reasoning/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiElementsPromptInputIndexRoute =
  AiElementsPromptInputIndexRouteImport.update({
    id: '/ai-elements/prompt-input/',
    path: '/ai-elements/prompt-input/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiElementsPlanIndexRoute = AiElementsPlanIndexRouteImport.update({
  id: '/ai-elements/plan/',
  path: '/ai-elements/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsMessageIndexRoute = AiElementsMessageIndexRouteImport.update({
  id: '/ai-elements/message/',
  path: '/ai-elements/message/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsFullChatIndexRoute = AiElementsFullChatIndexRouteImport.update({
  id: '/ai-elements/full-chat/',
  path: '/ai-elements/full-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiElementsConversationIndexRoute =
  AiElementsConversationIndexRouteImport.update({
    id: '/ai-elements/conversation/',
    path: '/ai-elements/conversation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiElementsConfirmationIndexRoute =
  AiElementsConfirmationIndexRouteImport.update({
    id: '/ai-elements/confirmation/',
    path: '/ai-elements/confirmation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiElementsChainOfThoughtIndexRoute =
  AiElementsChainOfThoughtIndexRouteImport.update({
    id: '/ai-elements/chain-of-thought/',
    path: '/ai-elements/chain-of-thought/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion/': typeof AccordionIndexRoute
  '/ai-elements/': typeof AiElementsIndexRoute
  '/alert-dialog/': typeof AlertDialogIndexRoute
  '/alert/': typeof AlertIndexRoute
  '/aspect-ratio/': typeof AspectRatioIndexRoute
  '/avatar/': typeof AvatarIndexRoute
  '/badge/': typeof BadgeIndexRoute
  '/bento/': typeof BentoIndexRoute
  '/breadcrumb/': typeof BreadcrumbIndexRoute
  '/bubble/': typeof BubbleIndexRoute
  '/button/': typeof ButtonIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/card/': typeof CardIndexRoute
  '/carousel/': typeof CarouselIndexRoute
  '/code-block/': typeof CodeBlockIndexRoute
  '/collapsible/': typeof CollapsibleIndexRoute
  '/color-tokens/': typeof ColorTokensIndexRoute
  '/container/': typeof ContainerIndexRoute
  '/dialog/': typeof DialogIndexRoute
  '/direction/': typeof DirectionIndexRoute
  '/divider/': typeof DividerIndexRoute
  '/dropdown-menu/': typeof DropdownMenuIndexRoute
  '/dropzone/': typeof DropzoneIndexRoute
  '/empty/': typeof EmptyIndexRoute
  '/form-controls/': typeof FormControlsIndexRoute
  '/grid/': typeof GridIndexRoute
  '/hover-card/': typeof HoverCardIndexRoute
  '/icon/': typeof IconIndexRoute
  '/item/': typeof ItemIndexRoute
  '/kbd/': typeof KbdIndexRoute
  '/list/': typeof ListIndexRoute
  '/marker/': typeof MarkerIndexRoute
  '/message/': typeof MessageIndexRoute
  '/native-select/': typeof NativeSelectIndexRoute
  '/pagination/': typeof PaginationIndexRoute
  '/popover/': typeof PopoverIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/resizable/': typeof ResizableIndexRoute
  '/responsive-grid/': typeof ResponsiveGridIndexRoute
  '/scroll-area/': typeof ScrollAreaIndexRoute
  '/select/': typeof SelectIndexRoute
  '/separator/': typeof SeparatorIndexRoute
  '/sheet/': typeof SheetIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/sidebar/': typeof SidebarIndexRoute
  '/skeleton/': typeof SkeletonIndexRoute
  '/slider/': typeof SliderIndexRoute
  '/spacing/': typeof SpacingIndexRoute
  '/stack/': typeof StackIndexRoute
  '/table/': typeof TableIndexRoute
  '/tabs/': typeof TabsIndexRoute
  '/toast/': typeof ToastIndexRoute
  '/toggle-group/': typeof ToggleGroupIndexRoute
  '/toggle/': typeof ToggleIndexRoute
  '/tooltip/': typeof TooltipIndexRoute
  '/typography/': typeof TypographyIndexRoute
  '/ai-elements/chain-of-thought/': typeof AiElementsChainOfThoughtIndexRoute
  '/ai-elements/confirmation/': typeof AiElementsConfirmationIndexRoute
  '/ai-elements/conversation/': typeof AiElementsConversationIndexRoute
  '/ai-elements/full-chat/': typeof AiElementsFullChatIndexRoute
  '/ai-elements/message/': typeof AiElementsMessageIndexRoute
  '/ai-elements/plan/': typeof AiElementsPlanIndexRoute
  '/ai-elements/prompt-input/': typeof AiElementsPromptInputIndexRoute
  '/ai-elements/reasoning/': typeof AiElementsReasoningIndexRoute
  '/ai-elements/shimmer/': typeof AiElementsShimmerIndexRoute
  '/ai-elements/sources/': typeof AiElementsSourcesIndexRoute
  '/ai-elements/suggestions/': typeof AiElementsSuggestionsIndexRoute
  '/ai-elements/task/': typeof AiElementsTaskIndexRoute
  '/ai-elements/tool/': typeof AiElementsToolIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion': typeof AccordionIndexRoute
  '/ai-elements': typeof AiElementsIndexRoute
  '/alert-dialog': typeof AlertDialogIndexRoute
  '/alert': typeof AlertIndexRoute
  '/aspect-ratio': typeof AspectRatioIndexRoute
  '/avatar': typeof AvatarIndexRoute
  '/badge': typeof BadgeIndexRoute
  '/bento': typeof BentoIndexRoute
  '/breadcrumb': typeof BreadcrumbIndexRoute
  '/bubble': typeof BubbleIndexRoute
  '/button': typeof ButtonIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/card': typeof CardIndexRoute
  '/carousel': typeof CarouselIndexRoute
  '/code-block': typeof CodeBlockIndexRoute
  '/collapsible': typeof CollapsibleIndexRoute
  '/color-tokens': typeof ColorTokensIndexRoute
  '/container': typeof ContainerIndexRoute
  '/dialog': typeof DialogIndexRoute
  '/direction': typeof DirectionIndexRoute
  '/divider': typeof DividerIndexRoute
  '/dropdown-menu': typeof DropdownMenuIndexRoute
  '/dropzone': typeof DropzoneIndexRoute
  '/empty': typeof EmptyIndexRoute
  '/form-controls': typeof FormControlsIndexRoute
  '/grid': typeof GridIndexRoute
  '/hover-card': typeof HoverCardIndexRoute
  '/icon': typeof IconIndexRoute
  '/item': typeof ItemIndexRoute
  '/kbd': typeof KbdIndexRoute
  '/list': typeof ListIndexRoute
  '/marker': typeof MarkerIndexRoute
  '/message': typeof MessageIndexRoute
  '/native-select': typeof NativeSelectIndexRoute
  '/pagination': typeof PaginationIndexRoute
  '/popover': typeof PopoverIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/resizable': typeof ResizableIndexRoute
  '/responsive-grid': typeof ResponsiveGridIndexRoute
  '/scroll-area': typeof ScrollAreaIndexRoute
  '/select': typeof SelectIndexRoute
  '/separator': typeof SeparatorIndexRoute
  '/sheet': typeof SheetIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/sidebar': typeof SidebarIndexRoute
  '/skeleton': typeof SkeletonIndexRoute
  '/slider': typeof SliderIndexRoute
  '/spacing': typeof SpacingIndexRoute
  '/stack': typeof StackIndexRoute
  '/table': typeof TableIndexRoute
  '/tabs': typeof TabsIndexRoute
  '/toast': typeof ToastIndexRoute
  '/toggle-group': typeof ToggleGroupIndexRoute
  '/toggle': typeof ToggleIndexRoute
  '/tooltip': typeof TooltipIndexRoute
  '/typography': typeof TypographyIndexRoute
  '/ai-elements/chain-of-thought': typeof AiElementsChainOfThoughtIndexRoute
  '/ai-elements/confirmation': typeof AiElementsConfirmationIndexRoute
  '/ai-elements/conversation': typeof AiElementsConversationIndexRoute
  '/ai-elements/full-chat': typeof AiElementsFullChatIndexRoute
  '/ai-elements/message': typeof AiElementsMessageIndexRoute
  '/ai-elements/plan': typeof AiElementsPlanIndexRoute
  '/ai-elements/prompt-input': typeof AiElementsPromptInputIndexRoute
  '/ai-elements/reasoning': typeof AiElementsReasoningIndexRoute
  '/ai-elements/shimmer': typeof AiElementsShimmerIndexRoute
  '/ai-elements/sources': typeof AiElementsSourcesIndexRoute
  '/ai-elements/suggestions': typeof AiElementsSuggestionsIndexRoute
  '/ai-elements/task': typeof AiElementsTaskIndexRoute
  '/ai-elements/tool': typeof AiElementsToolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordion/': typeof AccordionIndexRoute
  '/ai-elements/': typeof AiElementsIndexRoute
  '/alert-dialog/': typeof AlertDialogIndexRoute
  '/alert/': typeof AlertIndexRoute
  '/aspect-ratio/': typeof AspectRatioIndexRoute
  '/avatar/': typeof AvatarIndexRoute
  '/badge/': typeof BadgeIndexRoute
  '/bento/': typeof BentoIndexRoute
  '/breadcrumb/': typeof BreadcrumbIndexRoute
  '/bubble/': typeof BubbleIndexRoute
  '/button/': typeof ButtonIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/card/': typeof CardIndexRoute
  '/carousel/': typeof CarouselIndexRoute
  '/code-block/': typeof CodeBlockIndexRoute
  '/collapsible/': typeof CollapsibleIndexRoute
  '/color-tokens/': typeof ColorTokensIndexRoute
  '/container/': typeof ContainerIndexRoute
  '/dialog/': typeof DialogIndexRoute
  '/direction/': typeof DirectionIndexRoute
  '/divider/': typeof DividerIndexRoute
  '/dropdown-menu/': typeof DropdownMenuIndexRoute
  '/dropzone/': typeof DropzoneIndexRoute
  '/empty/': typeof EmptyIndexRoute
  '/form-controls/': typeof FormControlsIndexRoute
  '/grid/': typeof GridIndexRoute
  '/hover-card/': typeof HoverCardIndexRoute
  '/icon/': typeof IconIndexRoute
  '/item/': typeof ItemIndexRoute
  '/kbd/': typeof KbdIndexRoute
  '/list/': typeof ListIndexRoute
  '/marker/': typeof MarkerIndexRoute
  '/message/': typeof MessageIndexRoute
  '/native-select/': typeof NativeSelectIndexRoute
  '/pagination/': typeof PaginationIndexRoute
  '/popover/': typeof PopoverIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/resizable/': typeof ResizableIndexRoute
  '/responsive-grid/': typeof ResponsiveGridIndexRoute
  '/scroll-area/': typeof ScrollAreaIndexRoute
  '/select/': typeof SelectIndexRoute
  '/separator/': typeof SeparatorIndexRoute
  '/sheet/': typeof SheetIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/sidebar/': typeof SidebarIndexRoute
  '/skeleton/': typeof SkeletonIndexRoute
  '/slider/': typeof SliderIndexRoute
  '/spacing/': typeof SpacingIndexRoute
  '/stack/': typeof StackIndexRoute
  '/table/': typeof TableIndexRoute
  '/tabs/': typeof TabsIndexRoute
  '/toast/': typeof ToastIndexRoute
  '/toggle-group/': typeof ToggleGroupIndexRoute
  '/toggle/': typeof ToggleIndexRoute
  '/tooltip/': typeof TooltipIndexRoute
  '/typography/': typeof TypographyIndexRoute
  '/ai-elements/chain-of-thought/': typeof AiElementsChainOfThoughtIndexRoute
  '/ai-elements/confirmation/': typeof AiElementsConfirmationIndexRoute
  '/ai-elements/conversation/': typeof AiElementsConversationIndexRoute
  '/ai-elements/full-chat/': typeof AiElementsFullChatIndexRoute
  '/ai-elements/message/': typeof AiElementsMessageIndexRoute
  '/ai-elements/plan/': typeof AiElementsPlanIndexRoute
  '/ai-elements/prompt-input/': typeof AiElementsPromptInputIndexRoute
  '/ai-elements/reasoning/': typeof AiElementsReasoningIndexRoute
  '/ai-elements/shimmer/': typeof AiElementsShimmerIndexRoute
  '/ai-elements/sources/': typeof AiElementsSourcesIndexRoute
  '/ai-elements/suggestions/': typeof AiElementsSuggestionsIndexRoute
  '/ai-elements/task/': typeof AiElementsTaskIndexRoute
  '/ai-elements/tool/': typeof AiElementsToolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordion/'
    | '/ai-elements/'
    | '/alert-dialog/'
    | '/alert/'
    | '/aspect-ratio/'
    | '/avatar/'
    | '/badge/'
    | '/bento/'
    | '/breadcrumb/'
    | '/bubble/'
    | '/button/'
    | '/calendar/'
    | '/card/'
    | '/carousel/'
    | '/code-block/'
    | '/collapsible/'
    | '/color-tokens/'
    | '/container/'
    | '/dialog/'
    | '/direction/'
    | '/divider/'
    | '/dropdown-menu/'
    | '/dropzone/'
    | '/empty/'
    | '/form-controls/'
    | '/grid/'
    | '/hover-card/'
    | '/icon/'
    | '/item/'
    | '/kbd/'
    | '/list/'
    | '/marker/'
    | '/message/'
    | '/native-select/'
    | '/pagination/'
    | '/popover/'
    | '/progress/'
    | '/resizable/'
    | '/responsive-grid/'
    | '/scroll-area/'
    | '/select/'
    | '/separator/'
    | '/sheet/'
    | '/showcase/'
    | '/sidebar/'
    | '/skeleton/'
    | '/slider/'
    | '/spacing/'
    | '/stack/'
    | '/table/'
    | '/tabs/'
    | '/toast/'
    | '/toggle-group/'
    | '/toggle/'
    | '/tooltip/'
    | '/typography/'
    | '/ai-elements/chain-of-thought/'
    | '/ai-elements/confirmation/'
    | '/ai-elements/conversation/'
    | '/ai-elements/full-chat/'
    | '/ai-elements/message/'
    | '/ai-elements/plan/'
    | '/ai-elements/prompt-input/'
    | '/ai-elements/reasoning/'
    | '/ai-elements/shimmer/'
    | '/ai-elements/sources/'
    | '/ai-elements/suggestions/'
    | '/ai-elements/task/'
    | '/ai-elements/tool/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordion'
    | '/ai-elements'
    | '/alert-dialog'
    | '/alert'
    | '/aspect-ratio'
    | '/avatar'
    | '/badge'
    | '/bento'
    | '/breadcrumb'
    | '/bubble'
    | '/button'
    | '/calendar'
    | '/card'
    | '/carousel'
    | '/code-block'
    | '/collapsible'
    | '/color-tokens'
    | '/container'
    | '/dialog'
    | '/direction'
    | '/divider'
    | '/dropdown-menu'
    | '/dropzone'
    | '/empty'
    | '/form-controls'
    | '/grid'
    | '/hover-card'
    | '/icon'
    | '/item'
    | '/kbd'
    | '/list'
    | '/marker'
    | '/message'
    | '/native-select'
    | '/pagination'
    | '/popover'
    | '/progress'
    | '/resizable'
    | '/responsive-grid'
    | '/scroll-area'
    | '/select'
    | '/separator'
    | '/sheet'
    | '/showcase'
    | '/sidebar'
    | '/skeleton'
    | '/slider'
    | '/spacing'
    | '/stack'
    | '/table'
    | '/tabs'
    | '/toast'
    | '/toggle-group'
    | '/toggle'
    | '/tooltip'
    | '/typography'
    | '/ai-elements/chain-of-thought'
    | '/ai-elements/confirmation'
    | '/ai-elements/conversation'
    | '/ai-elements/full-chat'
    | '/ai-elements/message'
    | '/ai-elements/plan'
    | '/ai-elements/prompt-input'
    | '/ai-elements/reasoning'
    | '/ai-elements/shimmer'
    | '/ai-elements/sources'
    | '/ai-elements/suggestions'
    | '/ai-elements/task'
    | '/ai-elements/tool'
  id:
    | '__root__'
    | '/'
    | '/accordion/'
    | '/ai-elements/'
    | '/alert-dialog/'
    | '/alert/'
    | '/aspect-ratio/'
    | '/avatar/'
    | '/badge/'
    | '/bento/'
    | '/breadcrumb/'
    | '/bubble/'
    | '/button/'
    | '/calendar/'
    | '/card/'
    | '/carousel/'
    | '/code-block/'
    | '/collapsible/'
    | '/color-tokens/'
    | '/container/'
    | '/dialog/'
    | '/direction/'
    | '/divider/'
    | '/dropdown-menu/'
    | '/dropzone/'
    | '/empty/'
    | '/form-controls/'
    | '/grid/'
    | '/hover-card/'
    | '/icon/'
    | '/item/'
    | '/kbd/'
    | '/list/'
    | '/marker/'
    | '/message/'
    | '/native-select/'
    | '/pagination/'
    | '/popover/'
    | '/progress/'
    | '/resizable/'
    | '/responsive-grid/'
    | '/scroll-area/'
    | '/select/'
    | '/separator/'
    | '/sheet/'
    | '/showcase/'
    | '/sidebar/'
    | '/skeleton/'
    | '/slider/'
    | '/spacing/'
    | '/stack/'
    | '/table/'
    | '/tabs/'
    | '/toast/'
    | '/toggle-group/'
    | '/toggle/'
    | '/tooltip/'
    | '/typography/'
    | '/ai-elements/chain-of-thought/'
    | '/ai-elements/confirmation/'
    | '/ai-elements/conversation/'
    | '/ai-elements/full-chat/'
    | '/ai-elements/message/'
    | '/ai-elements/plan/'
    | '/ai-elements/prompt-input/'
    | '/ai-elements/reasoning/'
    | '/ai-elements/shimmer/'
    | '/ai-elements/sources/'
    | '/ai-elements/suggestions/'
    | '/ai-elements/task/'
    | '/ai-elements/tool/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionIndexRoute: typeof AccordionIndexRoute
  AiElementsIndexRoute: typeof AiElementsIndexRoute
  AlertDialogIndexRoute: typeof AlertDialogIndexRoute
  AlertIndexRoute: typeof AlertIndexRoute
  AspectRatioIndexRoute: typeof AspectRatioIndexRoute
  AvatarIndexRoute: typeof AvatarIndexRoute
  BadgeIndexRoute: typeof BadgeIndexRoute
  BentoIndexRoute: typeof BentoIndexRoute
  BreadcrumbIndexRoute: typeof BreadcrumbIndexRoute
  BubbleIndexRoute: typeof BubbleIndexRoute
  ButtonIndexRoute: typeof ButtonIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CardIndexRoute: typeof CardIndexRoute
  CarouselIndexRoute: typeof CarouselIndexRoute
  CodeBlockIndexRoute: typeof CodeBlockIndexRoute
  CollapsibleIndexRoute: typeof CollapsibleIndexRoute
  ColorTokensIndexRoute: typeof ColorTokensIndexRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
  DialogIndexRoute: typeof DialogIndexRoute
  DirectionIndexRoute: typeof DirectionIndexRoute
  DividerIndexRoute: typeof DividerIndexRoute
  DropdownMenuIndexRoute: typeof DropdownMenuIndexRoute
  DropzoneIndexRoute: typeof DropzoneIndexRoute
  EmptyIndexRoute: typeof EmptyIndexRoute
  FormControlsIndexRoute: typeof FormControlsIndexRoute
  GridIndexRoute: typeof GridIndexRoute
  HoverCardIndexRoute: typeof HoverCardIndexRoute
  IconIndexRoute: typeof IconIndexRoute
  ItemIndexRoute: typeof ItemIndexRoute
  KbdIndexRoute: typeof KbdIndexRoute
  ListIndexRoute: typeof ListIndexRoute
  MarkerIndexRoute: typeof MarkerIndexRoute
  MessageIndexRoute: typeof MessageIndexRoute
  NativeSelectIndexRoute: typeof NativeSelectIndexRoute
  PaginationIndexRoute: typeof PaginationIndexRoute
  PopoverIndexRoute: typeof PopoverIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  ResizableIndexRoute: typeof ResizableIndexRoute
  ResponsiveGridIndexRoute: typeof ResponsiveGridIndexRoute
  ScrollAreaIndexRoute: typeof ScrollAreaIndexRoute
  SelectIndexRoute: typeof SelectIndexRoute
  SeparatorIndexRoute: typeof SeparatorIndexRoute
  SheetIndexRoute: typeof SheetIndexRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
  SkeletonIndexRoute: typeof SkeletonIndexRoute
  SliderIndexRoute: typeof SliderIndexRoute
  SpacingIndexRoute: typeof SpacingIndexRoute
  StackIndexRoute: typeof StackIndexRoute
  TableIndexRoute: typeof TableIndexRoute
  TabsIndexRoute: typeof TabsIndexRoute
  ToastIndexRoute: typeof ToastIndexRoute
  ToggleGroupIndexRoute: typeof ToggleGroupIndexRoute
  ToggleIndexRoute: typeof ToggleIndexRoute
  TooltipIndexRoute: typeof TooltipIndexRoute
  TypographyIndexRoute: typeof TypographyIndexRoute
  AiElementsChainOfThoughtIndexRoute: typeof AiElementsChainOfThoughtIndexRoute
  AiElementsConfirmationIndexRoute: typeof AiElementsConfirmationIndexRoute
  AiElementsConversationIndexRoute: typeof AiElementsConversationIndexRoute
  AiElementsFullChatIndexRoute: typeof AiElementsFullChatIndexRoute
  AiElementsMessageIndexRoute: typeof AiElementsMessageIndexRoute
  AiElementsPlanIndexRoute: typeof AiElementsPlanIndexRoute
  AiElementsPromptInputIndexRoute: typeof AiElementsPromptInputIndexRoute
  AiElementsReasoningIndexRoute: typeof AiElementsReasoningIndexRoute
  AiElementsShimmerIndexRoute: typeof AiElementsShimmerIndexRoute
  AiElementsSourcesIndexRoute: typeof AiElementsSourcesIndexRoute
  AiElementsSuggestionsIndexRoute: typeof AiElementsSuggestionsIndexRoute
  AiElementsTaskIndexRoute: typeof AiElementsTaskIndexRoute
  AiElementsToolIndexRoute: typeof AiElementsToolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography/': {
      id: '/typography/'
      path: '/typography'
      fullPath: '/typography/'
      preLoaderRoute: typeof TypographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooltip/': {
      id: '/tooltip/'
      path: '/tooltip'
      fullPath: '/tooltip/'
      preLoaderRoute: typeof TooltipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toggle/': {
      id: '/toggle/'
      path: '/toggle'
      fullPath: '/toggle/'
      preLoaderRoute: typeof ToggleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toggle-group/': {
      id: '/toggle-group/'
      path: '/toggle-group'
      fullPath: '/toggle-group/'
      preLoaderRoute: typeof ToggleGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toast/': {
      id: '/toast/'
      path: '/toast'
      fullPath: '/toast/'
      preLoaderRoute: typeof ToastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/': {
      id: '/tabs/'
      path: '/tabs'
      fullPath: '/tabs/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack/': {
      id: '/stack/'
      path: '/stack'
      fullPath: '/stack/'
      preLoaderRoute: typeof StackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spacing/': {
      id: '/spacing/'
      path: '/spacing'
      fullPath: '/spacing/'
      preLoaderRoute: typeof SpacingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slider/': {
      id: '/slider/'
      path: '/slider'
      fullPath: '/slider/'
      preLoaderRoute: typeof SliderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skeleton/': {
      id: '/skeleton/'
      path: '/skeleton'
      fullPath: '/skeleton/'
      preLoaderRoute: typeof SkeletonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebar/': {
      id: '/sidebar/'
      path: '/sidebar'
      fullPath: '/sidebar/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/': {
      id: '/sheet/'
      path: '/sheet'
      fullPath: '/sheet/'
      preLoaderRoute: typeof SheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/separator/': {
      id: '/separator/'
      path: '/separator'
      fullPath: '/separator/'
      preLoaderRoute: typeof SeparatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select/': {
      id: '/select/'
      path: '/select'
      fullPath: '/select/'
      preLoaderRoute: typeof SelectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-area/': {
      id: '/scroll-area/'
      path: '/scroll-area'
      fullPath: '/scroll-area/'
      preLoaderRoute: typeof ScrollAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsive-grid/': {
      id: '/responsive-grid/'
      path: '/responsive-grid'
      fullPath: '/responsive-grid/'
      preLoaderRoute: typeof ResponsiveGridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resizable/': {
      id: '/resizable/'
      path: '/resizable'
      fullPath: '/resizable/'
      preLoaderRoute: typeof ResizableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popover/': {
      id: '/popover/'
      path: '/popover'
      fullPath: '/popover/'
      preLoaderRoute: typeof PopoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagination/': {
      id: '/pagination/'
      path: '/pagination'
      fullPath: '/pagination/'
      preLoaderRoute: typeof PaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-select/': {
      id: '/native-select/'
      path: '/native-select'
      fullPath: '/native-select/'
      preLoaderRoute: typeof NativeSelectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/': {
      id: '/message/'
      path: '/message'
      fullPath: '/message/'
      preLoaderRoute: typeof MessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marker/': {
      id: '/marker/'
      path: '/marker'
      fullPath: '/marker/'
      preLoaderRoute: typeof MarkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/': {
      id: '/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof ListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kbd/': {
      id: '/kbd/'
      path: '/kbd'
      fullPath: '/kbd/'
      preLoaderRoute: typeof KbdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/': {
      id: '/item/'
      path: '/item'
      fullPath: '/item/'
      preLoaderRoute: typeof ItemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon/': {
      id: '/icon/'
      path: '/icon'
      fullPath: '/icon/'
      preLoaderRoute: typeof IconIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hover-card/': {
      id: '/hover-card/'
      path: '/hover-card'
      fullPath: '/hover-card/'
      preLoaderRoute: typeof HoverCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/': {
      id: '/grid/'
      path: '/grid'
      fullPath: '/grid/'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-controls/': {
      id: '/form-controls/'
      path: '/form-controls'
      fullPath: '/form-controls/'
      preLoaderRoute: typeof FormControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty/': {
      id: '/empty/'
      path: '/empty'
      fullPath: '/empty/'
      preLoaderRoute: typeof EmptyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropzone/': {
      id: '/dropzone/'
      path: '/dropzone'
      fullPath: '/dropzone/'
      preLoaderRoute: typeof DropzoneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropdown-menu/': {
      id: '/dropdown-menu/'
      path: '/dropdown-menu'
      fullPath: '/dropdown-menu/'
      preLoaderRoute: typeof DropdownMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divider/': {
      id: '/divider/'
      path: '/divider'
      fullPath: '/divider/'
      preLoaderRoute: typeof DividerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direction/': {
      id: '/direction/'
      path: '/direction'
      fullPath: '/direction/'
      preLoaderRoute: typeof DirectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/': {
      id: '/dialog/'
      path: '/dialog'
      fullPath: '/dialog/'
      preLoaderRoute: typeof DialogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/container/': {
      id: '/container/'
      path: '/container'
      fullPath: '/container/'
      preLoaderRoute: typeof ContainerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-tokens/': {
      id: '/color-tokens/'
      path: '/color-tokens'
      fullPath: '/color-tokens/'
      preLoaderRoute: typeof ColorTokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collapsible/': {
      id: '/collapsible/'
      path: '/collapsible'
      fullPath: '/collapsible/'
      preLoaderRoute: typeof CollapsibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-block/': {
      id: '/code-block/'
      path: '/code-block'
      fullPath: '/code-block/'
      preLoaderRoute: typeof CodeBlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousel/': {
      id: '/carousel/'
      path: '/carousel'
      fullPath: '/carousel/'
      preLoaderRoute: typeof CarouselIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/': {
      id: '/card/'
      path: '/card'
      fullPath: '/card/'
      preLoaderRoute: typeof CardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button/': {
      id: '/button/'
      path: '/button'
      fullPath: '/button/'
      preLoaderRoute: typeof ButtonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bubble/': {
      id: '/bubble/'
      path: '/bubble'
      fullPath: '/bubble/'
      preLoaderRoute: typeof BubbleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breadcrumb/': {
      id: '/breadcrumb/'
      path: '/breadcrumb'
      fullPath: '/breadcrumb/'
      preLoaderRoute: typeof BreadcrumbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bento/': {
      id: '/bento/'
      path: '/bento'
      fullPath: '/bento/'
      preLoaderRoute: typeof BentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/': {
      id: '/badge/'
      path: '/badge'
      fullPath: '/badge/'
      preLoaderRoute: typeof BadgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar/': {
      id: '/avatar/'
      path: '/avatar'
      fullPath: '/avatar/'
      preLoaderRoute: typeof AvatarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspect-ratio/': {
      id: '/aspect-ratio/'
      path: '/aspect-ratio'
      fullPath: '/aspect-ratio/'
      preLoaderRoute: typeof AspectRatioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/': {
      id: '/alert/'
      path: '/alert'
      fullPath: '/alert/'
      preLoaderRoute: typeof AlertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-dialog/': {
      id: '/alert-dialog/'
      path: '/alert-dialog'
      fullPath: '/alert-dialog/'
      preLoaderRoute: typeof AlertDialogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/': {
      id: '/ai-elements/'
      path: '/ai-elements'
      fullPath: '/ai-elements/'
      preLoaderRoute: typeof AiElementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion/': {
      id: '/accordion/'
      path: '/accordion'
      fullPath: '/accordion/'
      preLoaderRoute: typeof AccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/tool/': {
      id: '/ai-elements/tool/'
      path: '/ai-elements/tool'
      fullPath: '/ai-elements/tool/'
      preLoaderRoute: typeof AiElementsToolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/task/': {
      id: '/ai-elements/task/'
      path: '/ai-elements/task'
      fullPath: '/ai-elements/task/'
      preLoaderRoute: typeof AiElementsTaskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/suggestions/': {
      id: '/ai-elements/suggestions/'
      path: '/ai-elements/suggestions'
      fullPath: '/ai-elements/suggestions/'
      preLoaderRoute: typeof AiElementsSuggestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/sources/': {
      id: '/ai-elements/sources/'
      path: '/ai-elements/sources'
      fullPath: '/ai-elements/sources/'
      preLoaderRoute: typeof AiElementsSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/shimmer/': {
      id: '/ai-elements/shimmer/'
      path: '/ai-elements/shimmer'
      fullPath: '/ai-elements/shimmer/'
      preLoaderRoute: typeof AiElementsShimmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/reasoning/': {
      id: '/ai-elements/reasoning/'
      path: '/ai-elements/reasoning'
      fullPath: '/ai-elements/reasoning/'
      preLoaderRoute: typeof AiElementsReasoningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/prompt-input/': {
      id: '/ai-elements/prompt-input/'
      path: '/ai-elements/prompt-input'
      fullPath: '/ai-elements/prompt-input/'
      preLoaderRoute: typeof AiElementsPromptInputIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/plan/': {
      id: '/ai-elements/plan/'
      path: '/ai-elements/plan'
      fullPath: '/ai-elements/plan/'
      preLoaderRoute: typeof AiElementsPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/message/': {
      id: '/ai-elements/message/'
      path: '/ai-elements/message'
      fullPath: '/ai-elements/message/'
      preLoaderRoute: typeof AiElementsMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/full-chat/': {
      id: '/ai-elements/full-chat/'
      path: '/ai-elements/full-chat'
      fullPath: '/ai-elements/full-chat/'
      preLoaderRoute: typeof AiElementsFullChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/conversation/': {
      id: '/ai-elements/conversation/'
      path: '/ai-elements/conversation'
      fullPath: '/ai-elements/conversation/'
      preLoaderRoute: typeof AiElementsConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/confirmation/': {
      id: '/ai-elements/confirmation/'
      path: '/ai-elements/confirmation'
      fullPath: '/ai-elements/confirmation/'
      preLoaderRoute: typeof AiElementsConfirmationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-elements/chain-of-thought/': {
      id: '/ai-elements/chain-of-thought/'
      path: '/ai-elements/chain-of-thought'
      fullPath: '/ai-elements/chain-of-thought/'
      preLoaderRoute: typeof AiElementsChainOfThoughtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionIndexRoute: AccordionIndexRoute,
  AiElementsIndexRoute: AiElementsIndexRoute,
  AlertDialogIndexRoute: AlertDialogIndexRoute,
  AlertIndexRoute: AlertIndexRoute,
  AspectRatioIndexRoute: AspectRatioIndexRoute,
  AvatarIndexRoute: AvatarIndexRoute,
  BadgeIndexRoute: BadgeIndexRoute,
  BentoIndexRoute: BentoIndexRoute,
  BreadcrumbIndexRoute: BreadcrumbIndexRoute,
  BubbleIndexRoute: BubbleIndexRoute,
  ButtonIndexRoute: ButtonIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CardIndexRoute: CardIndexRoute,
  CarouselIndexRoute: CarouselIndexRoute,
  CodeBlockIndexRoute: CodeBlockIndexRoute,
  CollapsibleIndexRoute: CollapsibleIndexRoute,
  ColorTokensIndexRoute: ColorTokensIndexRoute,
  ContainerIndexRoute: ContainerIndexRoute,
  DialogIndexRoute: DialogIndexRoute,
  DirectionIndexRoute: DirectionIndexRoute,
  DividerIndexRoute: DividerIndexRoute,
  DropdownMenuIndexRoute: DropdownMenuIndexRoute,
  DropzoneIndexRoute: DropzoneIndexRoute,
  EmptyIndexRoute: EmptyIndexRoute,
  FormControlsIndexRoute: FormControlsIndexRoute,
  GridIndexRoute: GridIndexRoute,
  HoverCardIndexRoute: HoverCardIndexRoute,
  IconIndexRoute: IconIndexRoute,
  ItemIndexRoute: ItemIndexRoute,
  KbdIndexRoute: KbdIndexRoute,
  ListIndexRoute: ListIndexRoute,
  MarkerIndexRoute: MarkerIndexRoute,
  MessageIndexRoute: MessageIndexRoute,
  NativeSelectIndexRoute: NativeSelectIndexRoute,
  PaginationIndexRoute: PaginationIndexRoute,
  PopoverIndexRoute: PopoverIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  ResizableIndexRoute: ResizableIndexRoute,
  ResponsiveGridIndexRoute: ResponsiveGridIndexRoute,
  ScrollAreaIndexRoute: ScrollAreaIndexRoute,
  SelectIndexRoute: SelectIndexRoute,
  SeparatorIndexRoute: SeparatorIndexRoute,
  SheetIndexRoute: SheetIndexRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  SidebarIndexRoute: SidebarIndexRoute,
  SkeletonIndexRoute: SkeletonIndexRoute,
  SliderIndexRoute: SliderIndexRoute,
  SpacingIndexRoute: SpacingIndexRoute,
  StackIndexRoute: StackIndexRoute,
  TableIndexRoute: TableIndexRoute,
  TabsIndexRoute: TabsIndexRoute,
  ToastIndexRoute: ToastIndexRoute,
  ToggleGroupIndexRoute: ToggleGroupIndexRoute,
  ToggleIndexRoute: ToggleIndexRoute,
  TooltipIndexRoute: TooltipIndexRoute,
  TypographyIndexRoute: TypographyIndexRoute,
  AiElementsChainOfThoughtIndexRoute: AiElementsChainOfThoughtIndexRoute,
  AiElementsConfirmationIndexRoute: AiElementsConfirmationIndexRoute,
  AiElementsConversationIndexRoute: AiElementsConversationIndexRoute,
  AiElementsFullChatIndexRoute: AiElementsFullChatIndexRoute,
  AiElementsMessageIndexRoute: AiElementsMessageIndexRoute,
  AiElementsPlanIndexRoute: AiElementsPlanIndexRoute,
  AiElementsPromptInputIndexRoute: AiElementsPromptInputIndexRoute,
  AiElementsReasoningIndexRoute: AiElementsReasoningIndexRoute,
  AiElementsShimmerIndexRoute: AiElementsShimmerIndexRoute,
  AiElementsSourcesIndexRoute: AiElementsSourcesIndexRoute,
  AiElementsSuggestionsIndexRoute: AiElementsSuggestionsIndexRoute,
  AiElementsTaskIndexRoute: AiElementsTaskIndexRoute,
  AiElementsToolIndexRoute: AiElementsToolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
