export const showcasePageMeta = [
	{
		slug: 'color-tokens',
		path: '/color-tokens',
		title: 'Color tokens',
		category: 'Foundations',
		description: 'Palette scales, semantic colors, and runtime theme variables.',
	},
	{
		slug: 'typography',
		path: '/typography',
		title: 'Typography',
		category: 'Foundations',
		description: 'Type tokens, font presets, headings, body copy, captions, and code text.',
	},
	{
		slug: 'spacing',
		path: '/spacing',
		title: 'Spacing',
		category: 'Layout',
		description: 'Spacing scale, spacer primitives, and layout rhythm.',
	},
	{
		slug: 'container',
		path: '/container',
		title: 'Container',
		category: 'Layout',
		description: 'Responsive content widths for page and section layouts.',
	},
	{
		slug: 'grid',
		path: '/grid',
		title: 'Grid',
		category: 'Layout',
		description: 'Grid primitives for aligned responsive surfaces.',
	},
	{
		slug: 'stack',
		path: '/stack',
		title: 'Stack',
		category: 'Layout',
		description: 'Vertical and horizontal composition helpers.',
	},
	{
		slug: 'responsive-grid',
		path: '/responsive-grid',
		title: 'Responsive grid',
		category: 'Layout',
		description: 'Auto-fitting grid patterns for repeated content.',
	},
	{
		slug: 'bento',
		path: '/bento',
		title: 'Bento',
		category: 'Layout',
		description: 'Composed bento layouts for dashboard-style content blocks.',
	},
	{
		slug: 'button',
		path: '/button',
		title: 'Button',
		category: 'Actions',
		description: 'Command controls, variants, sizes, loading states, and icon layouts.',
	},
	{
		slug: 'badge',
		path: '/badge',
		title: 'Badge',
		category: 'Actions',
		description: 'Compact labels for status, metadata, and emphasis.',
	},
	{
		slug: 'icon',
		path: '/icon',
		title: 'Icon',
		category: 'Actions',
		description: 'Tokenized icon sizing and color treatments.',
	},
	{
		slug: 'avatar',
		path: '/avatar',
		title: 'Avatar',
		category: 'Actions',
		description: 'User and entity identity surfaces.',
	},
	{
		slug: 'kbd',
		path: '/kbd',
		title: 'Kbd',
		category: 'Actions',
		description: 'Keyboard shortcut and command-key display.',
	},
	{
		slug: 'card',
		path: '/card',
		title: 'Card',
		category: 'Content',
		description: 'Framed content blocks with consistent padding, borders, and hierarchy.',
	},
	{
		slug: 'alert',
		path: '/alert',
		title: 'Alert',
		category: 'Content',
		description: 'Status messaging with semantic tone support.',
	},
	{
		slug: 'accordion',
		path: '/accordion',
		title: 'Accordion',
		category: 'Content',
		description: 'Expandable disclosure sections and grouped content.',
	},
	{
		slug: 'collapsible',
		path: '/collapsible',
		title: 'Collapsible',
		category: 'Content',
		description: 'Single-section disclosure behavior.',
	},
	{
		slug: 'item',
		path: '/item',
		title: 'Item',
		category: 'Content',
		description: 'Reusable list-row composition with media, metadata, and actions.',
	},
	{
		slug: 'message',
		path: '/message',
		title: 'Message',
		category: 'Content',
		description: 'Generic conversational message layout primitives.',
	},
	{
		slug: 'bubble',
		path: '/bubble',
		title: 'Bubble',
		category: 'Content',
		description: 'Chat and comment bubble surfaces.',
	},
	{
		slug: 'marker',
		path: '/marker',
		title: 'Marker',
		category: 'Content',
		description: 'Small semantic indicators for timeline, list, and status layouts.',
	},
	{
		slug: 'list',
		path: '/list',
		title: 'List',
		category: 'Content',
		description: 'Structured lists with consistent spacing and dividers.',
	},
	{
		slug: 'dialog',
		path: '/dialog',
		title: 'Dialog',
		category: 'Overlays',
		description: 'Modal surfaces for focused tasks.',
	},
	{
		slug: 'alert-dialog',
		path: '/alert-dialog',
		title: 'Alert dialog',
		category: 'Overlays',
		description: 'Confirmation and destructive-action dialogs.',
	},
	{
		slug: 'sheet',
		path: '/sheet',
		title: 'Sheet',
		category: 'Overlays',
		description: 'Edge-anchored panels for secondary workflows.',
	},
	{
		slug: 'dropdown-menu',
		path: '/dropdown-menu',
		title: 'Dropdown menu',
		category: 'Overlays',
		description: 'Menu actions, item groups, and selection states.',
	},
	{
		slug: 'popover',
		path: '/popover',
		title: 'Popover',
		category: 'Overlays',
		description: 'Anchored floating content and lightweight panels.',
	},
	{
		slug: 'tooltip',
		path: '/tooltip',
		title: 'Tooltip',
		category: 'Overlays',
		description: 'Short contextual help for controls and dense UI.',
	},
	{
		slug: 'hover-card',
		path: '/hover-card',
		title: 'Hover card',
		category: 'Overlays',
		description: 'Richer hover-triggered context panels.',
	},
	{
		slug: 'toast',
		path: '/toast',
		title: 'Toast',
		category: 'Overlays',
		description: 'Transient notifications and feedback.',
	},
	{
		slug: 'sidebar',
		path: '/sidebar',
		title: 'Sidebar',
		category: 'Navigation',
		description: 'Application navigation shells and rail patterns.',
	},
	{
		slug: 'tabs',
		path: '/tabs',
		title: 'Tabs',
		category: 'Navigation',
		description: 'Tabbed content sections and navigation.',
	},
	{
		slug: 'breadcrumb',
		path: '/breadcrumb',
		title: 'Breadcrumb',
		category: 'Navigation',
		description: 'Hierarchy trails for nested pages.',
	},
	{
		slug: 'pagination',
		path: '/pagination',
		title: 'Pagination',
		category: 'Navigation',
		description: 'Paged navigation for result sets and tables.',
	},
	{
		slug: 'table',
		path: '/table',
		title: 'Table',
		category: 'Data',
		description: 'Structured tabular content with opinionated spacing.',
	},
	{
		slug: 'carousel',
		path: '/carousel',
		title: 'Carousel',
		category: 'Data',
		description: 'Scrollable item sequences and controls.',
	},
	{
		slug: 'progress',
		path: '/progress',
		title: 'Progress',
		category: 'Data',
		description: 'Progress bars and completion indicators.',
	},
	{
		slug: 'code-block',
		path: '/code-block',
		title: 'Code block',
		category: 'Data',
		description: 'Syntax-highlighted code surfaces.',
	},
	{
		slug: 'form-controls',
		path: '/form-controls',
		title: 'Form controls',
		category: 'Forms',
		description: 'Inputs, labels, field layout, helper text, and validation states.',
	},
	{
		slug: 'native-select',
		path: '/native-select',
		title: 'Native select',
		category: 'Forms',
		description: 'Lightweight native select controls with design-system styling.',
	},
	{
		slug: 'select',
		path: '/select',
		title: 'Select',
		category: 'Forms',
		description: 'Composed select menus and option lists.',
	},
	{
		slug: 'toggle',
		path: '/toggle',
		title: 'Toggle',
		category: 'Forms',
		description: 'Pressed-state buttons and binary controls.',
	},
	{
		slug: 'toggle-group',
		path: '/toggle-group',
		title: 'Toggle group',
		category: 'Forms',
		description: 'Single and multiple selection toggle groups.',
	},
	{
		slug: 'slider',
		path: '/slider',
		title: 'Slider',
		category: 'Forms',
		description: 'Range controls and value selection.',
	},
	{
		slug: 'calendar',
		path: '/calendar',
		title: 'Calendar',
		category: 'Forms',
		description: 'Date picking and calendar display.',
	},
	{
		slug: 'dropzone',
		path: '/dropzone',
		title: 'Dropzone',
		category: 'Forms',
		description: 'File upload drop targets and selected file states.',
	},
	{
		slug: 'ai-elements',
		path: '/ai-elements',
		title: 'AI elements',
		category: 'AI',
		description: 'AI-specific messages, prompts, responses, tool calls, and branch controls.',
	},
	{
		slug: 'scroll-area',
		path: '/scroll-area',
		title: 'Scroll area',
		category: 'Utilities',
		description: 'Styled overflow regions and scroll affordances.',
	},
	{
		slug: 'resizable',
		path: '/resizable',
		title: 'Resizable',
		category: 'Utilities',
		description: 'Resizable panels and split layouts.',
	},
	{
		slug: 'direction',
		path: '/direction',
		title: 'Direction',
		category: 'Utilities',
		description: 'Direction-aware layout and text rendering.',
	},
	{
		slug: 'aspect-ratio',
		path: '/aspect-ratio',
		title: 'Aspect ratio',
		category: 'Utilities',
		description: 'Fixed-ratio media and layout boxes.',
	},
	{
		slug: 'empty',
		path: '/empty',
		title: 'Empty',
		category: 'Utilities',
		description: 'Empty states for missing content and setup flows.',
	},
	{
		slug: 'skeleton',
		path: '/skeleton',
		title: 'Skeleton',
		category: 'Utilities',
		description: 'Loading placeholders and pending content states.',
	},
	{
		slug: 'separator',
		path: '/separator',
		title: 'Separator',
		category: 'Utilities',
		description: 'Horizontal and vertical section dividers.',
	},
	{
		slug: 'divider',
		path: '/divider',
		title: 'Divider',
		category: 'Utilities',
		description: 'Opinionated visual dividers for content grouping.',
	},
] as const

export type ShowcasePageMeta = (typeof showcasePageMeta)[number]
export type ShowcaseSlug = ShowcasePageMeta['slug']
export type ShowcaseCategory = ShowcasePageMeta['category']

export const showcaseCategories = [
	'Foundations',
	'Layout',
	'Actions',
	'Content',
	'Overlays',
	'Navigation',
	'Data',
	'Forms',
	'AI',
	'Utilities',
] as const satisfies readonly ShowcaseCategory[]

export const showcaseGroups = showcaseCategories.map((category) => ({
	category,
	pages: showcasePageMeta.filter((page) => page.category === category),
}))

export const showcasePagePaths = showcasePageMeta.map((page) => page.path)
