import type React from 'react'
import {
	AIElementsShowcase,
	AccordionShowcase,
	AlertDialogShowcase,
	AlertsShowcase,
	AspectRatioShowcase,
	AvatarShowcase,
	BadgesShowcase,
	BentoShowcase,
	BreadcrumbShowcase,
	BubbleShowcase,
	ButtonsShowcase,
	CalendarShowcase,
	CardsShowcase,
	CarouselShowcase,
	CodeBlockShowcase,
	CollapsibleShowcase,
	ColorTokensShowcase,
	ContainerShowcase,
	DialogShowcase,
	DirectionShowcase,
	DividerShowcase,
	DropdownMenuShowcase,
	DropzoneShowcase,
	EmptyShowcase,
	FormControlsShowcase,
	GridShowcase,
	HoverCardShowcase,
	IconShowcase,
	ItemShowcase,
	KbdShowcase,
	ListShowcase,
	MarkerShowcase,
	MessageShowcase,
	NativeSelectShowcase,
	PaginationShowcase,
	PopoverShowcase,
	ProgressShowcase,
	ResizableShowcase,
	ResponsiveGridShowcase,
	ScrollAreaShowcase,
	SelectShowcase,
	SeparatorShowcase,
	SheetShowcase,
	SidebarShowcase,
	SkeletonShowcase,
	SliderShowcase,
	SpacingShowcase,
	StackShowcase,
	TableShowcase,
	TabsShowcase,
	ToastShowcase,
	ToggleGroupShowcase,
	ToggleShowcase,
	TooltipShowcase,
	TypographyShowcase,
} from './components'
import { showcasePageMeta, type ShowcaseSlug } from './showcase-pages'

const showcaseComponents = {
	'color-tokens': ColorTokensShowcase,
	typography: TypographyShowcase,
	spacing: SpacingShowcase,
	container: ContainerShowcase,
	grid: GridShowcase,
	stack: StackShowcase,
	'responsive-grid': ResponsiveGridShowcase,
	bento: BentoShowcase,
	button: ButtonsShowcase,
	badge: BadgesShowcase,
	icon: IconShowcase,
	avatar: AvatarShowcase,
	kbd: KbdShowcase,
	card: CardsShowcase,
	alert: AlertsShowcase,
	accordion: AccordionShowcase,
	collapsible: CollapsibleShowcase,
	item: ItemShowcase,
	message: MessageShowcase,
	bubble: BubbleShowcase,
	marker: MarkerShowcase,
	list: ListShowcase,
	dialog: DialogShowcase,
	'alert-dialog': AlertDialogShowcase,
	sheet: SheetShowcase,
	'dropdown-menu': DropdownMenuShowcase,
	popover: PopoverShowcase,
	tooltip: TooltipShowcase,
	'hover-card': HoverCardShowcase,
	toast: ToastShowcase,
	sidebar: SidebarShowcase,
	tabs: TabsShowcase,
	breadcrumb: BreadcrumbShowcase,
	pagination: PaginationShowcase,
	table: TableShowcase,
	carousel: CarouselShowcase,
	progress: ProgressShowcase,
	'code-block': CodeBlockShowcase,
	'form-controls': FormControlsShowcase,
	'native-select': NativeSelectShowcase,
	select: SelectShowcase,
	toggle: ToggleShowcase,
	'toggle-group': ToggleGroupShowcase,
	slider: SliderShowcase,
	calendar: CalendarShowcase,
	dropzone: DropzoneShowcase,
	'ai-elements': AIElementsShowcase,
	'scroll-area': ScrollAreaShowcase,
	resizable: ResizableShowcase,
	direction: DirectionShowcase,
	'aspect-ratio': AspectRatioShowcase,
	empty: EmptyShowcase,
	skeleton: SkeletonShowcase,
	separator: SeparatorShowcase,
	divider: DividerShowcase,
} satisfies Record<ShowcaseSlug, React.ComponentType>

export const showcasePages = showcasePageMeta.map((page) => ({
	...page,
	Component: showcaseComponents[page.slug],
}))

export const showcasePagesBySlug = Object.fromEntries(
	showcasePages.map((page) => [page.slug, page]),
) as {
	[Slug in ShowcaseSlug]: Extract<(typeof showcasePages)[number], { slug: Slug }>
}
