// Generated by scripts/generate-showcase-routes.ts.
import { createFileRoute } from '@tanstack/react-router'
import { AIElementRoute } from '@/ai-element-route'

export const Route = createFileRoute('/ai-elements/prompt-input/')({
	component: () => <AIElementRoute slug="prompt-input" />,
})
