// Generated by scripts/generate-showcase-routes.ts.
import { createFileRoute } from '@tanstack/react-router'
import { ComponentRoute } from '@/component-route'

export const Route = createFileRoute('/dropdown-menu/')({
	component: () => <ComponentRoute slug="dropdown-menu" />,
})
