export interface SemanticColorToken {
	cssVar: string
	reference: string
	category: 'bg' | 'text' | 'icon' | 'border' | 'chart'
	label: string
}

export interface CssAlias {
	cssVar: string
	target: string
}

export interface TailwindColorAlias {
	cssVar: string
	target: string
}

export const semanticColorTokens: SemanticColorToken[] = [
	// Background
	{ cssVar: '--bg-default', reference: '{neutral.100}', category: 'bg', label: 'default' },
	{ cssVar: '--bg-inverse', reference: '{neutral.1000}', category: 'bg', label: 'inverse' },
	{ cssVar: '--bg-muted', reference: '{neutral.200}', category: 'bg', label: 'muted' },
	{
		cssVar: '--bg-surface-default',
		reference: '{neutral.100}',
		category: 'bg',
		label: 'surface-default',
	},
	{ cssVar: '--bg-surface-info', reference: '{sky.100}', category: 'bg', label: 'surface-info' },
	{
		cssVar: '--bg-surface-success',
		reference: '{green.100}',
		category: 'bg',
		label: 'surface-success',
	},
	{
		cssVar: '--bg-surface-warning',
		reference: '{orange.100}',
		category: 'bg',
		label: 'surface-warning',
	},
	{
		cssVar: '--bg-surface-critical',
		reference: '{red.100}',
		category: 'bg',
		label: 'surface-critical',
	},
	{
		cssVar: '--bg-surface-emphasis',
		reference: '{blue.100}',
		category: 'bg',
		label: 'surface-emphasis',
	},
	{
		cssVar: '--bg-surface-inverse',
		reference: '{neutral.950}',
		category: 'bg',
		label: 'surface-inverse',
	},
	{
		cssVar: '--bg-surface-transparent',
		reference: '{Overlays.Black-Alpha.50}',
		category: 'bg',
		label: 'surface-transparent',
	},
	{ cssVar: '--bg-surface-brand', reference: '{pink.100}', category: 'bg', label: 'surface-brand' },
	{
		cssVar: '--bg-surface-brand-2',
		reference: '{jade.100}',
		category: 'bg',
		label: 'surface-brand-2',
	},
	{
		cssVar: '--bg-surface-brand-3',
		reference: '{amber.100}',
		category: 'bg',
		label: 'surface-brand-3',
	},
	{
		cssVar: '--bg-surface-brand-4',
		reference: '{blue.100}',
		category: 'bg',
		label: 'surface-brand-4',
	},
	{
		cssVar: '--bg-surface-brand-5',
		reference: '{green.100}',
		category: 'bg',
		label: 'surface-brand-5',
	},
	{
		cssVar: '--bg-surface-hover',
		reference: '{neutral.200}',
		category: 'bg',
		label: 'surface-hover',
	},
	{
		cssVar: '--bg-fill-default',
		reference: '{neutral.100}',
		category: 'bg',
		label: 'fill-default',
	},
	{
		cssVar: '--bg-fill-primary',
		reference: '{neutral.1000}',
		category: 'bg',
		label: 'fill-primary',
	},
	{ cssVar: '--bg-fill-brand', reference: '{pink.800}', category: 'bg', label: 'fill-brand' },
	{
		cssVar: '--bg-fill-brand-2',
		reference: '{jade.800}',
		category: 'bg',
		label: 'fill-brand-2',
	},
	{
		cssVar: '--bg-fill-brand-3',
		reference: '{amber.800}',
		category: 'bg',
		label: 'fill-brand-3',
	},
	{
		cssVar: '--bg-fill-brand-4',
		reference: '{blue.800}',
		category: 'bg',
		label: 'fill-brand-4',
	},
	{
		cssVar: '--bg-fill-brand-5',
		reference: '{green.800}',
		category: 'bg',
		label: 'fill-brand-5',
	},
	{ cssVar: '--bg-fill-info', reference: '{sky.800}', category: 'bg', label: 'fill-info' },
	{ cssVar: '--bg-fill-success', reference: '{green.800}', category: 'bg', label: 'fill-success' },
	{ cssVar: '--bg-fill-warning', reference: '{orange.800}', category: 'bg', label: 'fill-warning' },
	{ cssVar: '--bg-fill-critical', reference: '{red.800}', category: 'bg', label: 'fill-critical' },
	{ cssVar: '--bg-fill-emphasis', reference: '{blue.800}', category: 'bg', label: 'fill-emphasis' },
	{
		cssVar: '--bg-fill-transparent',
		reference: '{Overlays.Black-Alpha.50}',
		category: 'bg',
		label: 'fill-transparent',
	},
	{
		cssVar: '--bg-fill-secondary',
		reference: '{neutral.1000}',
		category: 'bg',
		label: 'fill-secondary',
	},
	{
		cssVar: '--bg-fill-secondary-inverse',
		reference: '{base.white}',
		category: 'bg',
		label: 'fill-secondary-inverse',
	},

	// Text
	{ cssVar: '--text-default', reference: '{neutral.1000}', category: 'text', label: 'default' },
	{ cssVar: '--text-secondary', reference: '{neutral.950}', category: 'text', label: 'secondary' },
	{ cssVar: '--text-muted', reference: '{neutral.800}', category: 'text', label: 'muted' },
	{ cssVar: '--text-disabled', reference: '{neutral.600}', category: 'text', label: 'disabled' },
	{ cssVar: '--text-inverse', reference: '{base.white}', category: 'text', label: 'inverse' },
	{ cssVar: '--text-info', reference: '{sky.1000}', category: 'text', label: 'info' },
	{ cssVar: '--text-success', reference: '{green.1000}', category: 'text', label: 'success' },
	{ cssVar: '--text-warning', reference: '{orange.1000}', category: 'text', label: 'warning' },
	{ cssVar: '--text-critical', reference: '{red.1000}', category: 'text', label: 'critical' },
	{ cssVar: '--text-emphasis', reference: '{blue.1000}', category: 'text', label: 'emphasis' },
	{ cssVar: '--text-brand', reference: '{pink.1000}', category: 'text', label: 'brand' },
	{ cssVar: '--text-brand-2', reference: '{jade.1000}', category: 'text', label: 'brand-2' },
	{ cssVar: '--text-brand-3', reference: '{amber.1000}', category: 'text', label: 'brand-3' },
	{ cssVar: '--text-brand-4', reference: '{blue.1000}', category: 'text', label: 'brand-4' },
	{ cssVar: '--text-brand-5', reference: '{green.1000}', category: 'text', label: 'brand-5' },
	{ cssVar: '--text-link', reference: '{blue.1000}', category: 'text', label: 'link' },

	// Icon
	{ cssVar: '--icon-default', reference: '{neutral.1000}', category: 'icon', label: 'default' },
	{ cssVar: '--icon-secondary', reference: '{neutral.950}', category: 'icon', label: 'secondary' },
	{ cssVar: '--icon-disabled', reference: '{neutral.300}', category: 'icon', label: 'disabled' },
	{ cssVar: '--icon-inverse', reference: '{neutral.100}', category: 'icon', label: 'inverse' },
	{ cssVar: '--icon-info', reference: '{sky.950}', category: 'icon', label: 'info' },
	{ cssVar: '--icon-success', reference: '{green.950}', category: 'icon', label: 'success' },
	{ cssVar: '--icon-warning', reference: '{orange.950}', category: 'icon', label: 'warning' },
	{ cssVar: '--icon-critical', reference: '{red.950}', category: 'icon', label: 'critical' },
	{ cssVar: '--icon-emphasis', reference: '{blue.950}', category: 'icon', label: 'emphasis' },
	{ cssVar: '--icon-brand', reference: '{pink.950}', category: 'icon', label: 'brand' },
	{ cssVar: '--icon-brand-2', reference: '{jade.950}', category: 'icon', label: 'brand-2' },
	{ cssVar: '--icon-brand-3', reference: '{amber.950}', category: 'icon', label: 'brand-3' },
	{ cssVar: '--icon-brand-4', reference: '{blue.950}', category: 'icon', label: 'brand-4' },
	{ cssVar: '--icon-brand-5', reference: '{green.950}', category: 'icon', label: 'brand-5' },

	// Border
	{ cssVar: '--border-default', reference: '{neutral.600}', category: 'border', label: 'default' },
	{
		cssVar: '--border-secondary',
		reference: '{neutral.500}',
		category: 'border',
		label: 'secondary',
	},
	{
		cssVar: '--border-tertiary',
		reference: '{neutral.700}',
		category: 'border',
		label: 'tertiary',
	},
	{
		cssVar: '--border-disabled',
		reference: '{neutral.500}',
		category: 'border',
		label: 'disabled',
	},
	{ cssVar: '--border-inverse', reference: '{neutral.950}', category: 'border', label: 'inverse' },
	{ cssVar: '--border-focus', reference: '{blue.950}', category: 'border', label: 'focus' },
	{ cssVar: '--border-brand', reference: '{pink.600}', category: 'border', label: 'brand' },
	{ cssVar: '--border-brand-2', reference: '{jade.600}', category: 'border', label: 'brand-2' },
	{ cssVar: '--border-brand-3', reference: '{amber.600}', category: 'border', label: 'brand-3' },
	{ cssVar: '--border-brand-4', reference: '{blue.600}', category: 'border', label: 'brand-4' },
	{ cssVar: '--border-brand-5', reference: '{green.600}', category: 'border', label: 'brand-5' },
	{ cssVar: '--border-info', reference: '{sky.600}', category: 'border', label: 'info' },
	{ cssVar: '--border-success', reference: '{green.600}', category: 'border', label: 'success' },
	{ cssVar: '--border-warning', reference: '{orange.600}', category: 'border', label: 'warning' },
	{ cssVar: '--border-critical', reference: '{red.600}', category: 'border', label: 'critical' },
	{ cssVar: '--border-emphasis', reference: '{blue.700}', category: 'border', label: 'emphasis' },

	// Chart
	{ cssVar: '--chart-1', reference: '{blue.700}', category: 'chart', label: '1' },
	{ cssVar: '--chart-2', reference: '{blue.800}', category: 'chart', label: '2' },
	{ cssVar: '--chart-3', reference: '{violet.700}', category: 'chart', label: '3' },
	{ cssVar: '--chart-4', reference: '{violet.800}', category: 'chart', label: '4' },
	{ cssVar: '--chart-5', reference: '{violet.900}', category: 'chart', label: '5' },
]

export const shadcnCompatAliases: CssAlias[] = [
	{ cssVar: '--background', target: '--bg-default' },
	{ cssVar: '--foreground', target: '--text-default' },
	{ cssVar: '--card', target: '--bg-surface-default' },
	{ cssVar: '--card-foreground', target: '--text-default' },
	{ cssVar: '--popover', target: '--bg-surface-default' },
	{ cssVar: '--popover-foreground', target: '--text-default' },
	{ cssVar: '--primary', target: '--bg-fill-primary' },
	{ cssVar: '--primary-foreground', target: '--text-inverse' },
	{ cssVar: '--secondary', target: '--bg-muted' },
	{ cssVar: '--secondary-foreground', target: '--text-default' },
	{ cssVar: '--muted', target: '--bg-muted' },
	{ cssVar: '--muted-foreground', target: '--text-muted' },
	{ cssVar: '--accent', target: '--bg-muted' },
	{ cssVar: '--accent-foreground', target: '--text-default' },
	{ cssVar: '--destructive', target: '--bg-fill-critical' },
	{ cssVar: '--border', target: '--border-default' },
	{ cssVar: '--input', target: '--border-secondary' },
	{ cssVar: '--ring', target: '--border-focus' },
	{ cssVar: '--sidebar-background', target: '--bg-default' },
	{ cssVar: '--sidebar-foreground', target: '--text-default' },
	{ cssVar: '--sidebar-primary', target: '--bg-fill-primary' },
	{ cssVar: '--sidebar-primary-foreground', target: '--text-inverse' },
	{ cssVar: '--sidebar-accent', target: '--bg-muted' },
	{ cssVar: '--sidebar-accent-foreground', target: '--text-default' },
	{ cssVar: '--sidebar-border', target: '--border-default' },
	{ cssVar: '--sidebar-ring', target: '--border-focus' },
]

export const tailwindColorAliases: TailwindColorAlias[] = [
	...shadcnCompatAliases.map(({ cssVar }) => ({
		cssVar: `--color-${cssVar.slice(2)}`,
		target: cssVar,
	})),
	{ cssVar: '--color-overlay', target: '--color-overlay' },
	{ cssVar: '--color-sidebar', target: '--sidebar-background' },
	{ cssVar: '--color-page', target: '--bg-default' },
	{ cssVar: '--color-stroke', target: '--border-default' },
	{ cssVar: '--color-field', target: '--border-secondary' },
	{ cssVar: '--color-focus', target: '--border-focus' },
	{ cssVar: '--color-danger', target: '--bg-fill-critical' },
	{ cssVar: '--color-sidebar-stroke', target: '--border-default' },
	{ cssVar: '--color-chart-1', target: '--chart-1' },
	{ cssVar: '--color-chart-2', target: '--chart-2' },
	{ cssVar: '--color-chart-3', target: '--chart-3' },
	{ cssVar: '--color-chart-4', target: '--chart-4' },
	{ cssVar: '--color-chart-5', target: '--chart-5' },
	{ cssVar: '--color-success', target: '--text-success' },
	{ cssVar: '--color-warning', target: '--text-warning' },
	{ cssVar: '--color-critical', target: '--text-critical' },
	{ cssVar: '--color-info', target: '--text-info' },
	{ cssVar: '--color-emphasis', target: '--text-emphasis' },
	{ cssVar: '--color-brand', target: '--text-brand' },
	{ cssVar: '--color-brand-2', target: '--text-brand-2' },
	{ cssVar: '--color-brand-3', target: '--text-brand-3' },
	{ cssVar: '--color-brand-4', target: '--text-brand-4' },
	{ cssVar: '--color-brand-5', target: '--text-brand-5' },
	{ cssVar: '--color-surface-success', target: '--bg-surface-success' },
	{ cssVar: '--color-surface-warning', target: '--bg-surface-warning' },
	{ cssVar: '--color-surface-critical', target: '--bg-surface-critical' },
	{ cssVar: '--color-surface-info', target: '--bg-surface-info' },
	{ cssVar: '--color-surface-emphasis', target: '--bg-surface-emphasis' },
	{ cssVar: '--color-surface-brand', target: '--bg-surface-brand' },
	{ cssVar: '--color-surface-brand-2', target: '--bg-surface-brand-2' },
	{ cssVar: '--color-surface-brand-3', target: '--bg-surface-brand-3' },
	{ cssVar: '--color-surface-brand-4', target: '--bg-surface-brand-4' },
	{ cssVar: '--color-surface-brand-5', target: '--bg-surface-brand-5' },
	{ cssVar: '--color-icon-success', target: '--icon-success' },
	{ cssVar: '--color-icon-warning', target: '--icon-warning' },
	{ cssVar: '--color-icon-critical', target: '--icon-critical' },
	{ cssVar: '--color-icon-info', target: '--icon-info' },
	{ cssVar: '--color-icon-emphasis', target: '--icon-emphasis' },
	{ cssVar: '--color-icon-brand', target: '--icon-brand' },
	{ cssVar: '--color-icon-brand-2', target: '--icon-brand-2' },
	{ cssVar: '--color-icon-brand-3', target: '--icon-brand-3' },
	{ cssVar: '--color-icon-brand-4', target: '--icon-brand-4' },
	{ cssVar: '--color-icon-brand-5', target: '--icon-brand-5' },
	{ cssVar: '--color-stroke-critical', target: '--border-critical' },
	{ cssVar: '--color-stroke-success', target: '--border-success' },
	{ cssVar: '--color-stroke-warning', target: '--border-warning' },
	{ cssVar: '--color-stroke-info', target: '--border-info' },
	{ cssVar: '--color-stroke-emphasis', target: '--border-emphasis' },
	{ cssVar: '--color-stroke-brand', target: '--border-brand' },
	{ cssVar: '--color-stroke-brand-2', target: '--border-brand-2' },
	{ cssVar: '--color-stroke-brand-3', target: '--border-brand-3' },
	{ cssVar: '--color-stroke-brand-4', target: '--border-brand-4' },
	{ cssVar: '--color-stroke-brand-5', target: '--border-brand-5' },
]

export const semanticColorCssVars = semanticColorTokens.map((token) => token.cssVar)
export const shadcnCompatCssVars = shadcnCompatAliases.map((alias) => alias.cssVar)
export const tailwindColorCssVars = tailwindColorAliases.map((alias) => alias.cssVar)
