// Generated by scripts/generate-showcase-routes.ts.
import { createFileRoute } from '@tanstack/react-router'
import { ComponentRoute } from '@/component-route'

export const Route = createFileRoute('/button/')({
	component: () => <ComponentRoute slug="button" />,
})
