/**
 * Brutalist — Raw, architectural, uncompromising.
 * Studied references: Bloomberg Terminal aesthetic, Balenciaga.com restraint,
 * Ssense editorial rigour. High contrast without being garish.
 *
 * This is not the parody version (no neon yellow). Real brutalism is
 * about structural honesty: things look exactly like what they are.
 *
 * Fonts:
 *   Heading — Space Grotesk Variable: constructed, slightly mechanical,
 *             pairs well with mono body without feeling like a joke.
 *   Body    — Space Grotesk Variable: the Bloomberg terminal aesthetic. Readable,
 *             functional, carries authority. Uncompromising.
 *
 * Character: zero border-radius, heavy borders, hard offset shadows,
 * instant transitions, high contrast palette with a single editorial red.
 */
export const brutalist: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	'--bg-default': '#FFFFFFFF',
	'--bg-inverse': '#0A0A0AFF',
	'--bg-muted': '#F0F0F0FF',
	'--bg-surface-default': '#FFFFFFFF',
	'--bg-surface-popover': '#FFFFFFFF',
	'--bg-surface-accent': '#F0F0F0FF',
	'--bg-surface-info': '#E8F0F8FF',
	'--bg-surface-success': '#E8F4E8FF',
	'--bg-surface-warning': '#FBF4E0FF',
	'--bg-surface-critical': '#FAE8E8FF',
	'--bg-surface-emphasis': '#E8E8F4FF',
	'--bg-surface-inverse': '#3A3A3AFF',
	'--bg-surface-transparent': '#00000010',
	'--bg-overlay': 'var(--overlays-black-alpha-800)',
	'--bg-surface-brand': '#FFEFEBFF',
	'--bg-surface-brand-2': '#F0F0F0FF',
	'--bg-surface-brand-3': '#FFF8E0FF',
	'--bg-surface-brand-4': '#F0F0F0FF',
	'--bg-surface-brand-5': '#E8F0F8FF',
	'--bg-surface-hover': '#F0F0F0FF',
	'--bg-fill-default': '#FFFFFFFF',
	'--bg-fill-primary': '#0A0A0AFF',
	'--bg-fill-brand': '#CC2200FF',
	'--bg-fill-brand-2': '#111111FF',
	'--bg-fill-brand-3': '#FFD700FF',
	'--bg-fill-brand-4': '#5A5A5AFF',
	'--bg-fill-brand-5': '#0044AAFF',
	'--bg-fill-info': '#0044AAFF',
	'--bg-fill-success': '#007700FF',
	'--bg-fill-warning': '#CC6600FF',
	'--bg-fill-critical': '#CC0000FF',
	'--bg-fill-emphasis': '#0A0A0AFF',
	'--bg-fill-transparent': '#00000010',
	'--bg-fill-secondary': '#F0F0F0FF',
	'--bg-fill-secondary-inverse': '#FFFFFFFF',
	'--text-default': '#0A0A0AFF',
	'--text-secondary': '#2E2E2EFF',
	'--text-muted': '#5A5A5AFF',
	'--text-disabled': '#AAAAAAFF',
	'--text-inverse': '#F8F8F8FF',
	'--text-on-fill-primary': '#FFFFFFFF',
	'--text-on-fill-secondary': '#0A0A0AFF',
	'--text-on-surface-accent': '#0A0A0AFF',
	'--text-info': '#001E5EFF',
	'--text-success': '#003A00FF',
	'--text-warning': '#5E2E00FF',
	'--text-critical': '#5E0000FF',
	'--text-emphasis': '#001E5EFF',
	'--text-brand': '#880000FF',
	'--text-brand-2': '#0A0A0AFF',
	'--text-brand-3': '#6A5000FF',
	'--text-brand-4': '#3A3A3AFF',
	'--text-brand-5': '#002266FF',
	'--text-link': '#CC2200FF',
	'--icon-default': '#0A0A0AFF',
	'--icon-secondary': '#2E2E2EFF',
	'--icon-disabled': '#CCCCCCFF',
	'--icon-inverse': '#F8F8F8FF',
	'--icon-info': '#0044AAFF',
	'--icon-success': '#007700FF',
	'--icon-warning': '#AA5500FF',
	'--icon-critical': '#AA0000FF',
	'--icon-emphasis': '#0044AAFF',
	'--icon-brand': '#CC2200FF',
	'--icon-brand-2': '#111111FF',
	'--icon-brand-3': '#CCA800FF',
	'--icon-brand-4': '#5A5A5AFF',
	'--icon-brand-5': '#0044AAFF',
	'--border-default': '#0A0A0AFF',
	'--border-secondary': '#0A0A0AFF',
	'--border-input': '#C8C8C8FF',
	'--border-tertiary': '#4A4A4AFF',
	'--border-disabled': '#AAAAAAFF',
	'--border-inverse': '#F8F8F8FF',
	'--border-focus': '#CC2200FF',
	'--border-brand': '#CC2200FF',
	'--border-brand-2': '#0A0A0AFF',
	'--border-brand-3': '#E8C840FF',
	'--border-brand-4': '#AAAAAAFF',
	'--border-brand-5': '#4488CCFF',
	'--border-info': '#0044AAFF',
	'--border-success': '#007700FF',
	'--border-warning': '#AA5500FF',
	'--border-critical': '#AA0000FF',
	'--border-emphasis': '#0044AAFF',
	'--chart-1': '#0A0A0AFF',
	'--chart-2': '#CC2200FF',
	'--chart-3': '#4A4A4AFF',
	'--chart-4': '#007700FF',
	'--chart-5': '#0044AAFF',

	// ── Independent sidebar component roles ───────────────────────────────
	'--sidebar-background': '#FFFFFFFF',
	'--sidebar-foreground': '#0A0A0AFF',
	'--sidebar-primary': '#0A0A0AFF',
	'--sidebar-primary-foreground': '#FFFFFFFF',
	'--sidebar-accent': '#F0F0F0FF',
	'--sidebar-accent-foreground': '#0A0A0AFF',
	'--sidebar-border': '#0A0A0AFF',
	'--sidebar-ring': '#CC2200FF',

	// ── Dimension tokens ──────────────────────────────────────────────────
	'--spacing': '0.25rem',
	'--border-width-base': '0.125rem',
	'--radius': '0rem',
	'--font-size-base': '1rem',
	'--leading-base': '1.4',
	'--letter-spacing-base': '0.04em',
	'--opacity-disabled': '0.5',
	// Hard offset shadow — structural, no blur (that's the brutalist shadow)
	'--shadow-offset-y': '4px',
	'--shadow-blur': '0px',
	'--shadow-spread': '0px',
	'--shadow-base-color': 'rgba(0, 0, 0, 1)',
	'--container-sm': '672px',
	'--container-md': '816px',
	'--container-lg': '1104px',
	'--container-xl': '1392px',
	'--container-2xl': '1536px',
	'--dropdown-offset': '0',
	'--overlay-offset': '0',

	// ── Fonts: Space Grotesk for both heading and body ────────────────────
	// Terminal-meets-architecture: mono body, grotesque heading/brand.
	'--font-sans': '"JetBrains Mono Variable", monospace',
	'--font-heading': '"Space Grotesk Variable", "Arial", sans-serif',
	'--font-brand': '"Space Grotesk Variable", "Arial", sans-serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	// Zero radius everywhere — things are what they are
	'--button-radius': '0px',
	'--button-padding-x': 'calc(var(--spacing) * 5)',
	'--button-padding-y': 'calc(var(--spacing) * 2)',
	'--card-radius': '0px',
	'--card-padding': 'calc(var(--spacing) * 6)',
	'--nav-height': 'calc(var(--spacing) * 14)',
	'--section-padding-y': 'calc(var(--spacing) * 20)',
	'--hero-padding-y': 'calc(var(--spacing) * 32)',
	'--input-radius': '0px',
	'--input-height': 'calc(var(--spacing) * 10)',
	'--badge-radius': '0px',

	// ── Phase 1b: Motion — instant. No decorative animation. ─────────────
	'--motion-duration-fast': '0ms',
	'--motion-duration-normal': '0ms',
	'--motion-duration-slow': '50ms',
	'--motion-duration-color': '0ms',
	'--motion-duration-interaction': '0ms',
	'--motion-duration-disclosure': '0ms',
	'--motion-duration-overlay': '0ms',
	'--motion-ease-standard': 'linear',
	'--motion-ease-accelerate': 'linear',
	'--motion-ease-decelerate': 'linear',
	'--motion-ease-linear': 'linear',
	'--transition-default': 'var(--motion-duration-normal) var(--motion-ease-standard)',
	'--transition-fast': 'var(--motion-duration-fast) var(--motion-ease-standard)',
	'--transition-slow': 'var(--motion-duration-slow) var(--motion-ease-linear)',
	'--hover-transform': 'none',
	'--hover-shadow': 'none',
	'--active-scale': '1',

	// ── Phase 1c: Typography — heavy, structural ──────────────────────────
	'--heading-font-weight': '700',
	'--heading-letter-spacing': 'var(--tracking-tight)',
	'--body-letter-spacing': 'var(--tracking-normal)',
	'--hero-font-size': 'var(--text-6xl)',
	'--hero-font-weight': '700',
	'--hero-letter-spacing': 'var(--tracking-tight)',
	'--section-title-size': 'var(--text-3xl)',
	'--section-title-font-weight': '700',
	'--section-title-letter-spacing': 'var(--tracking-tight)',
	'--card-title-size': 'var(--text-base)',
	'--card-title-font-weight': '700',
	'--card-title-letter-spacing': 'var(--tracking-normal)',
}

export const brutalistDark: Record<string, string> = {
	// ── Dark: inverted — paper becomes black, ink becomes off-white ───────
	'--bg-default': '#0A0A0AFF',
	'--bg-inverse': '#F8F8F8FF',
	'--bg-muted': '#1A1A1AFF',
	'--bg-surface-default': '#0A0A0AFF',
	'--bg-surface-popover': '#141414FF',
	'--bg-surface-accent': '#1A1A1AFF',
	'--bg-surface-info': '#0A1828FF',
	'--bg-surface-success': '#0A180AFF',
	'--bg-surface-warning': '#1E1406FF',
	'--bg-surface-critical': '#1E0A0AFF',
	'--bg-surface-emphasis': '#0A0A1EFF',
	'--bg-surface-inverse': '#606060FF',
	'--bg-surface-transparent': '#FFFFFF10',
	'--bg-overlay': 'var(--overlays-black-alpha-800)',
	'--bg-surface-brand': '#1E0A08FF',
	'--bg-surface-brand-2': '#141414FF',
	'--bg-surface-brand-3': '#1E1A08FF',
	'--bg-surface-brand-4': '#141414FF',
	'--bg-surface-brand-5': '#0A1028FF',
	'--bg-surface-hover': '#1A1A1AFF',
	'--bg-fill-default': '#0A0A0AFF',
	'--bg-fill-primary': '#F0F0F0FF',
	'--bg-fill-brand': '#FF3322FF',
	'--bg-fill-brand-2': '#F0F0F0FF',
	'--bg-fill-brand-3': '#FFE033FF',
	'--bg-fill-brand-4': '#888888FF',
	'--bg-fill-brand-5': '#3366CCFF',
	'--bg-fill-info': '#3366CCFF',
	'--bg-fill-success': '#009900FF',
	'--bg-fill-warning': '#DD7700FF',
	'--bg-fill-critical': '#DD2222FF',
	'--bg-fill-emphasis': '#F0F0F0FF',
	'--bg-fill-transparent': '#FFFFFF10',
	'--bg-fill-secondary': '#1A1A1AFF',
	'--bg-fill-secondary-inverse': '#0A0A0AFF',
	'--text-default': '#F0F0F0FF',
	'--text-secondary': '#C0C0C0FF',
	'--text-muted': '#888888FF',
	'--text-disabled': '#444444FF',
	'--text-inverse': '#0A0A0AFF',
	'--text-on-fill-primary': '#0A0A0AFF',
	'--text-on-fill-secondary': '#F0F0F0FF',
	'--text-on-surface-accent': '#F0F0F0FF',
	'--text-info': '#99BBFFFF',
	'--text-success': '#77DD77FF',
	'--text-warning': '#FFBB44FF',
	'--text-critical': '#FF7777FF',
	'--text-emphasis': '#CCCCFFFF',
	'--text-brand': '#FF9988FF',
	'--text-brand-2': '#F0F0F0FF',
	'--text-brand-3': '#FFE066FF',
	'--text-brand-4': '#C0C0C0FF',
	'--text-brand-5': '#88AAEEFF',
	'--text-link': '#FF5533FF',
	'--icon-default': '#F0F0F0FF',
	'--icon-secondary': '#C0C0C0FF',
	'--icon-disabled': '#383838FF',
	'--icon-inverse': '#0A0A0AFF',
	'--icon-info': '#5588EEFF',
	'--icon-success': '#44BB44FF',
	'--icon-warning': '#CC8800FF',
	'--icon-critical': '#DD3333FF',
	'--icon-emphasis': '#5588EEFF',
	'--icon-brand': '#FF4433FF',
	'--icon-brand-2': '#F0F0F0FF',
	'--icon-brand-3': '#FFD700FF',
	'--icon-brand-4': '#888888FF',
	'--icon-brand-5': '#3366CCFF',
	'--border-default': '#F0F0F0FF',
	'--border-secondary': '#C0C0C0FF',
	'--border-input': '#383838FF',
	'--border-tertiary': '#888888FF',
	'--border-disabled': '#444444FF',
	'--border-inverse': '#0A0A0AFF',
	'--border-focus': '#FF3322FF',
	'--border-brand': '#FF3322FF',
	'--border-brand-2': '#888888FF',
	'--border-brand-3': '#806800FF',
	'--border-brand-4': '#444444FF',
	'--border-brand-5': '#1A3366FF',
	'--border-info': '#3366CCFF',
	'--border-success': '#009900FF',
	'--border-warning': '#CC6600FF',
	'--border-critical': '#CC1111FF',
	'--border-emphasis': '#3366CCFF',
	'--chart-1': '#F0F0F0FF',
	'--chart-2': '#FF3322FF',
	'--chart-3': '#888888FF',
	'--chart-4': '#44BB44FF',
	'--chart-5': '#5588EEFF',

	// ── Independent sidebar component roles ───────────────────────────────
	'--sidebar-background': '#0A0A0AFF',
	'--sidebar-foreground': '#F0F0F0FF',
	'--sidebar-primary': '#F0F0F0FF',
	'--sidebar-primary-foreground': '#0A0A0AFF',
	'--sidebar-accent': '#1A1A1AFF',
	'--sidebar-accent-foreground': '#F0F0F0FF',
	'--sidebar-border': '#F0F0F0FF',
	'--sidebar-ring': '#FF3322FF',

	// ── Fonts carry over ──────────────────────────────────────────────────
	'--font-sans': '"JetBrains Mono Variable", monospace',
	'--font-heading': '"Space Grotesk Variable", "Arial", sans-serif',
	'--font-brand': '"Space Grotesk Variable", "Arial", sans-serif',
}
