/**
 * Default — Clean, neutral, Inter-based. The "no opinion" starting point.
 * Think Linear, Vercel. A solid foundation that stays out of the way.
 *
 * Fonts: Inter Variable (all) — the most carefully crafted neutral sans-serif.
 */
export const defaultPreset: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	'--bg-default': '#F9F9F8FF',
	'--bg-inverse': '#21201CFF',
	'--bg-muted': '#F1F0EFFF',
	'--bg-surface-default': '#F9F9F8FF',
	'--bg-surface-popover': '#F9F9F8FF',
	'--bg-surface-accent': '#F1F0EFFF',
	'--bg-surface-info': '#F1FAFDFF',
	'--bg-surface-success': '#F5FBF5FF',
	'--bg-surface-warning': '#FFF7EDFF',
	'--bg-surface-critical': '#FFF7F7FF',
	'--bg-surface-emphasis': '#F4FAFFFF',
	'--bg-surface-inverse': '#63635EFF',
	'--bg-surface-transparent': '#0000000D',
	'--bg-overlay': 'var(--overlays-black-alpha-800)',
	'--bg-surface-brand': '#FEF7FBFF',
	'--bg-surface-brand-2': '#EEFAF8FF',
	'--bg-surface-brand-3': '#FFFAF0FF',
	'--bg-surface-brand-4': '#EEF2FBFF',
	'--bg-surface-brand-5': '#F0FAF0FF',
	'--bg-surface-hover': '#F1F0EFFF',
	'--bg-fill-default': '#F9F9F8FF',
	'--bg-fill-primary': '#21201CFF',
	'--bg-fill-brand': '#D6409FFF',
	'--bg-fill-brand-2': '#12A594FF',
	'--bg-fill-brand-3': '#FFC53DFF',
	'--bg-fill-brand-4': '#3E63DDFF',
	'--bg-fill-brand-5': '#46A758FF',
	'--bg-fill-info': '#7CE2FEFF',
	'--bg-fill-success': '#46A758FF',
	'--bg-fill-warning': '#F76B15FF',
	'--bg-fill-critical': '#E5484DFF',
	'--bg-fill-emphasis': '#0090FFFF',
	'--bg-fill-transparent': '#0000000D',
	'--bg-fill-secondary': '#F1F0EFFF',
	'--bg-fill-secondary-inverse': '#FFFFFFFF',
	'--text-default': '#21201CFF',
	'--text-secondary': '#63635EFF',
	'--text-muted': '#8D8D86FF',
	'--text-disabled': '#CFCECAFF',
	'--text-inverse': '#FFFFFFFF',
	'--text-on-fill-primary': '#FFFFFFFF',
	'--text-on-fill-secondary': '#21201CFF',
	'--text-on-surface-accent': '#21201CFF',
	'--text-info': '#1D3E56FF',
	'--text-success': '#203C25FF',
	'--text-warning': '#582D1DFF',
	'--text-critical': '#641723FF',
	'--text-emphasis': '#113264FF',
	'--text-brand': '#651249FF',
	'--text-brand-2': '#0D6D5EFF',
	'--text-brand-3': '#6F5B1BFF',
	'--text-brand-4': '#1F3780FF',
	'--text-brand-5': '#203C25FF',
	'--text-link': '#113264FF',
	'--icon-default': '#21201CFF',
	'--icon-secondary': '#63635EFF',
	'--icon-disabled': '#E9E8E6FF',
	'--icon-inverse': '#F9F9F8FF',
	'--icon-info': '#00749EFF',
	'--icon-success': '#2A7E3BFF',
	'--icon-warning': '#CC4E00FF',
	'--icon-critical': '#CE2C31FF',
	'--icon-emphasis': '#0D74CEFF',
	'--icon-brand': '#C2298AFF',
	'--icon-brand-2': '#12A594FF',
	'--icon-brand-3': '#E8A317FF',
	'--icon-brand-4': '#3E63DDFF',
	'--icon-brand-5': '#2A7E3BFF',
	'--border-default': '#CFCECAFF',
	'--border-secondary': '#DAD9D6FF',
	'--border-input': '#DAD9D6FF',
	'--border-tertiary': '#BCBBB5FF',
	'--border-disabled': '#DAD9D6FF',
	'--border-inverse': '#63635EFF',
	'--border-focus': '#0D74CEFF',
	'--border-brand': '#E7ACD0FF',
	'--border-brand-2': '#8ECEC6FF',
	'--border-brand-3': '#EDD5A0FF',
	'--border-brand-4': '#93A9E8FF',
	'--border-brand-5': '#94CE9AFF',
	'--border-info': '#8DCAE3FF',
	'--border-success': '#94CE9AFF',
	'--border-warning': '#F5AE73FF',
	'--border-critical': '#F4A9AAFF',
	'--border-emphasis': '#5EB1EFFF',
	'--chart-1': '#5EB1EFFF',
	'--chart-2': '#0090FFFF',
	'--chart-3': '#AA99ECFF',
	'--chart-4': '#6E56CFFF',
	'--chart-5': '#654DC4FF',

	// ── Independent sidebar component roles ───────────────────────────────
	'--sidebar-background': '#F9F9F8FF',
	'--sidebar-foreground': '#21201CFF',
	'--sidebar-primary': '#21201CFF',
	'--sidebar-primary-foreground': '#FFFFFFFF',
	'--sidebar-accent': '#F1F0EFFF',
	'--sidebar-accent-foreground': '#21201CFF',
	'--sidebar-border': '#CFCECAFF',
	'--sidebar-ring': '#0D74CEFF',

	// ── Dimension tokens ──────────────────────────────────────────────────
	'--spacing': '0.25rem',
	'--border-width-base': '0.0625rem',
	'--radius': '0.5rem',
	'--font-size-base': '1rem',
	'--leading-base': '1.33',
	'--letter-spacing-base': '0.025em',
	'--opacity-disabled': '0.5',
	'--shadow-offset-y': '1px',
	'--shadow-blur': '2px',
	'--shadow-spread': '1px',
	'--shadow-base-color': 'rgba(0, 0, 0, 0.1)',
	'--container-sm': '576px',
	'--container-md': '768px',
	'--container-lg': '1056px',
	'--container-xl': '1248px',
	'--container-2xl': '1440px',
	'--dropdown-offset': '4',
	'--overlay-offset': '4',

	// ── Fonts: Inter for body/heading, Bricolage Grotesque for brand ─────
	'--font-sans': '"Inter Variable", sans-serif',
	'--font-heading': '"Inter Variable", sans-serif',
	'--font-brand': '"Bricolage Grotesque Variable", sans-serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	'--button-radius': 'var(--radius-md)',
	'--card-radius': 'var(--radius-lg)',
	'--card-padding': 'calc(var(--spacing) * 4)',
	'--input-radius': 'var(--radius-md)',
	'--input-height': 'calc(var(--spacing) * 7)',
	'--badge-radius': 'var(--radius-4xl)',

	// ── Phase 1b: Motion tokens ────────────────────────────────────────────
	'--motion-duration-fast': '100ms',
	'--motion-duration-normal': '200ms',
	'--motion-duration-slow': '300ms',
	'--motion-duration-color': 'var(--motion-duration-fast)',
	'--motion-duration-interaction': 'var(--motion-duration-fast)',
	'--motion-duration-disclosure': 'var(--motion-duration-normal)',
	'--motion-duration-overlay': 'var(--motion-duration-fast)',
	'--motion-ease-standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
	'--motion-ease-accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
	'--motion-ease-decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
	'--motion-ease-linear': 'linear',
	'--transition-default': 'var(--motion-duration-normal) var(--motion-ease-standard)',
	'--transition-fast': 'var(--motion-duration-fast) var(--motion-ease-standard)',
	'--transition-slow': 'var(--motion-duration-slow) var(--motion-ease-decelerate)',
	'--hover-transform': 'none',
	'--hover-shadow': 'var(--shadow-md)',
	'--active-scale': '0.98',

	// ── Phase 1c: Typography composition tokens ───────────────────────────
	'--heading-font-weight': '700',
	'--heading-letter-spacing': 'var(--tracking-tight)',
	'--body-letter-spacing': 'var(--tracking-normal)',
	'--hero-font-size': 'var(--text-5xl)',
	'--hero-font-weight': '700',
	'--hero-letter-spacing': 'var(--tracking-tight)',
	'--section-title-size': 'var(--text-3xl)',
	'--section-title-font-weight': '700',
	'--section-title-letter-spacing': 'var(--tracking-tight)',
	'--card-title-size': 'var(--text-lg)',
	'--card-title-font-weight': '600',
	'--card-title-letter-spacing': 'var(--tracking-normal)',
}

export const defaultPresetDark: Record<string, string> = {
	// Full dark-mode token set — mirrors tokens.css .dark values so that the
	// injected :root overrides from the light preset are fully superseded when
	// dark mode is toggled.

	// ── Semantic color tokens ─────────────────────────────────────────────
	'--bg-default': '#191918FF',
	'--bg-inverse': '#EEEEECFF',
	'--bg-muted': '#222221FF',
	'--bg-surface-default': '#191918FF',
	'--bg-surface-popover': '#191918FF',
	'--bg-surface-accent': '#222221FF',
	'--bg-surface-info': '#111A27FF',
	'--bg-surface-success': '#141A15FF',
	'--bg-surface-warning': '#1E160FFF',
	'--bg-surface-critical': '#201314FF',
	'--bg-surface-emphasis': '#111927FF',
	'--bg-surface-inverse': '#B5B3ADFF',
	'--bg-surface-transparent': '#0000000D',
	'--bg-overlay': 'var(--overlays-black-alpha-800)',
	'--bg-surface-brand': '#21121DFF',
	'--bg-surface-brand-2': '#0F201EFF',
	'--bg-surface-brand-3': '#231E10FF',
	'--bg-surface-brand-4': '#111828FF',
	'--bg-surface-brand-5': '#141A15FF',
	'--bg-surface-hover': '#222221FF',
	'--bg-fill-default': '#191918FF',
	'--bg-fill-primary': '#EEEEECFF',
	'--bg-fill-brand': '#D6409FFF',
	'--bg-fill-brand-2': '#12A594FF',
	'--bg-fill-brand-3': '#FFC53DFF',
	'--bg-fill-brand-4': '#3E63DDFF',
	'--bg-fill-brand-5': '#46A758FF',
	'--bg-fill-info': '#7CE2FEFF',
	'--bg-fill-success': '#46A758FF',
	'--bg-fill-warning': '#F76B15FF',
	'--bg-fill-critical': '#E5484DFF',
	'--bg-fill-emphasis': '#0090FFFF',
	'--bg-fill-transparent': '#0000000D',
	'--bg-fill-secondary': '#222221FF',
	'--bg-fill-secondary-inverse': '#000000FF',
	'--text-default': '#EEEEECFF',
	'--text-secondary': '#B5B3ADFF',
	'--text-muted': '#6F6D66FF',
	'--text-disabled': '#494844FF',
	'--text-inverse': '#000000FF',
	'--text-on-fill-primary': '#000000FF',
	'--text-on-fill-secondary': '#EEEEECFF',
	'--text-on-surface-accent': '#EEEEECFF',
	'--text-info': '#C2F3FFFF',
	'--text-success': '#C2F0C2FF',
	'--text-warning': '#FFE0C2FF',
	'--text-critical': '#FFD1D9FF',
	'--text-emphasis': '#C2E6FFFF',
	'--text-brand': '#FDD1EAFF',
	'--text-brand-2': '#A8E5DCFF',
	'--text-brand-3': '#FFE6A0FF',
	'--text-brand-4': '#AEBFF0FF',
	'--text-brand-5': '#C2F0C2FF',
	'--text-link': '#C2E6FFFF',
	'--icon-default': '#EEEEECFF',
	'--icon-secondary': '#B5B3ADFF',
	'--icon-disabled': '#31312EFF',
	'--icon-inverse': '#191918FF',
	'--icon-info': '#75C7F0FF',
	'--icon-success': '#71D083FF',
	'--icon-warning': '#FFA057FF',
	'--icon-critical': '#FF9592FF',
	'--icon-emphasis': '#70B8FFFF',
	'--icon-brand': '#FF8DCCFF',
	'--icon-brand-2': '#4DC8BAFF',
	'--icon-brand-3': '#E8B844FF',
	'--icon-brand-4': '#6E8DEFFF',
	'--icon-brand-5': '#71D083FF',
	'--border-default': '#494844FF',
	'--border-secondary': '#494844FF',
	'--border-input': '#494844FF',
	'--border-tertiary': '#62605BFF',
	'--border-disabled': '#494844FF',
	'--border-inverse': '#B5B3ADFF',
	'--border-focus': '#70B8FFFF',
	'--border-brand': '#833869FF',
	'--border-brand-2': '#2A6858FF',
	'--border-brand-3': '#6A5020FF',
	'--border-brand-4': '#2A4480FF',
	'--border-brand-5': '#366740FF',
	'--border-info': '#1F6692FF',
	'--border-success': '#366740FF',
	'--border-warning': '#7E451DFF',
	'--border-critical': '#8C333AFF',
	'--border-emphasis': '#2870BDFF',
	'--chart-1': '#2870BDFF',
	'--chart-2': '#0090FFFF',
	'--chart-3': '#6958ADFF',
	'--chart-4': '#6E56CFFF',
	'--chart-5': '#7D66D9FF',

	// ── Independent sidebar component roles ───────────────────────────────
	'--sidebar-background': '#191918FF',
	'--sidebar-foreground': '#EEEEECFF',
	'--sidebar-primary': '#EEEEECFF',
	'--sidebar-primary-foreground': '#000000FF',
	'--sidebar-accent': '#222221FF',
	'--sidebar-accent-foreground': '#EEEEECFF',
	'--sidebar-border': '#494844FF',
	'--sidebar-ring': '#70B8FFFF',

	// ── Fonts carry over ──────────────────────────────────────────────────
	'--font-sans': '"Inter Variable", sans-serif',
	'--font-heading': '"Inter Variable", sans-serif',
	'--font-brand': '"Bricolage Grotesque Variable", sans-serif',
}
