import { defaultPreset, defaultPresetDark } from './default'

/**
 * Inspired by Cloudflare Kumo's theme and button treatments:
 * https://github.com/cloudflare/kumo/blob/main/packages/kumo/scripts/theme-generator/config.ts
 * https://github.com/cloudflare/kumo/blob/main/packages/kumo/src/components/button/button.tsx
 *
 * Kumo's blue action colour (oklch(0.5772 0.2324 260)) is #056dff in sRGB.
 * Orange is the Cloudflare brand accent; primary actions remain blue.
 * Semantic status surfaces stay tinted; action and brand buttons use solid fills.
 */
type BrandButton = 'brand' | 'brand-2' | 'brand-3' | 'brand-4' | 'brand-5'

function emphasisFinish(
	kind: 'primary' | 'destructive' | BrandButton,
	fill: string,
	gradientMix = { start: 15, hover: 30 },
): Record<string, string> {
	const edge = `color-mix(in oklch, ${fill}, black 10%)`
	const highlight = `color-mix(in oklch, ${fill}, white 30%)`
	return {
		[`--button-${kind}-border`]: edge,
		[`--button-${kind}-hover-border`]: edge,
		[`--button-${kind}-background-image`]: `linear-gradient(to bottom, color-mix(in oklch, ${fill}, white ${gradientMix.start}%), ${fill})`,
		[`--button-${kind}-hover-background-image`]: `linear-gradient(to bottom, color-mix(in oklch, ${fill}, white ${gradientMix.hover}%), ${fill})`,
		[`--button-${kind}-shadow`]: `inset 0 1px 0 ${highlight}, 0 1px 2px #0000000d`,
		[`--button-${kind}-hover-shadow`]: `inset 0 1px 0 ${highlight}, 0 1px 2px #0000000d`,
	}
}

// Vivid body colours and a bright upper edge make the brand actions pop.
// White labels use a heavier weight and a subtle shadow over these gradients.
const brandButtonColors: Record<BrandButton, { top: string; bottom: string; highlight: string }> = {
	brand: { top: '#F45B00', bottom: '#E04400', highlight: '#FF8A00' },
	'brand-2': { top: '#009DB8', bottom: '#007DAB', highlight: '#00D8EA' },
	'brand-3': { top: '#AA0AFF', bottom: '#7C00E5', highlight: '#E04BFF' },
	'brand-4': { top: '#1464FF', bottom: '#0045EF', highlight: '#388BFF' },
	'brand-5': { top: '#00AB38', bottom: '#008D21', highlight: '#63E600' },
}

function brandFinishes(): Record<string, string> {
	return Object.assign(
		{},
		...Object.entries(brandButtonColors).map(([variant, { top, bottom, highlight }]) => {
			const edge = `color-mix(in oklch, ${top}, black 8%)`
			const rim = `color-mix(in oklch, ${highlight}, white 15%)`
			const shadow = `color-mix(in srgb, ${top}, transparent 82%)`
			const hoverShadow = `color-mix(in srgb, ${top}, transparent 75%)`
			return {
				[`--button-${variant}-bg`]: top,
				[`--button-${variant}-text`]: '#FFFFFF',
				[`--button-${variant}-border`]: edge,
				[`--button-${variant}-hover-border`]: top,
				[`--button-${variant}-background-image`]: `linear-gradient(to bottom, ${highlight} 0%, ${top} 20%, ${bottom} 100%)`,
				[`--button-${variant}-hover-background-image`]: `linear-gradient(to bottom, ${highlight} 0%, ${top} 20%, color-mix(in oklch, ${bottom}, ${top} 25%) 100%)`,
				[`--button-${variant}-shadow`]: `inset 0 1px 0 ${rim}, inset 0 -1px 0 ${edge}, 0 2px 3px ${shadow}`,
				[`--button-${variant}-hover-shadow`]: `inset 0 1px 0 ${rim}, inset 0 -1px 0 ${edge}, 0 2px 6px ${hoverShadow}`,
			}
		}),
	)
}

const shape: Record<string, string> = {
	'--spacing': '0.25rem',
	'--border-width-base': '0.0625rem',
	'--radius': '0.5rem',
	'--font-size-base': '0.875rem',
	'--text-xs': '0.75rem',
	'--text-xs--line-height': '1.333333',
	'--text-sm': '0.8125rem',
	'--text-sm--line-height': '1.5',
	'--leading-base': '1.5',
	'--letter-spacing-base': '0.01em',
	'--font-sans': '"Inter Variable", ui-sans-serif, system-ui, sans-serif',
	'--font-heading': '"Inter Variable", ui-sans-serif, system-ui, sans-serif',
	'--font-brand': '"Inter Variable", ui-sans-serif, system-ui, sans-serif',
	'--button-radius': 'var(--radius-lg)',
	'--button-radius-xs': '0.25rem',
	'--button-radius-sm': '0.375rem',
	'--button-height': 'calc(var(--spacing) * 9)',
	'--button-height-xs': 'calc(var(--spacing) * 5)',
	'--button-height-sm': 'calc(var(--spacing) * 6.5)',
	'--button-height-lg': 'calc(var(--spacing) * 10)',
	'--button-font-size': 'var(--text-base)',
	'--button-font-size-xs': 'var(--text-xs)',
	'--button-font-size-sm': 'var(--text-xs)',
	'--button-gap': 'calc(var(--spacing) * 1.5)',
	'--button-brand-font-weight': '600',
	'--button-brand-text-shadow': '0 1px 1px #00000059, 0 0 1px #00000040',
	'--card-radius': 'var(--radius-xl)',
	'--layer-card-radius': 'var(--radius-lg)',
	'--layer-card-shadow': '0 1px 2px #0000000D',
	'--tabs-tab-height': 'calc(var(--spacing) * 8)',
	'--tabs-list-shadow': '0 0 0 1px var(--border-secondary)',
	'--tabs-indicator-shadow': '0 1px 2px #0000000D',
	'--flow-node-shadow': '0 1px 2px #0000000D',
	'--flow-canvas-background-image': 'radial-gradient(var(--border-disabled) 1px, transparent 1px)',
	'--input-radius': 'var(--radius-lg)',
	'--input-height': 'calc(var(--spacing) * 9)',
	'--badge-radius': 'var(--radius-md)',
	'--opacity-disabled': '0.5',
	'--shadow-offset-y': '1px',
	'--shadow-blur': '2px',
	'--shadow-spread': '0px',
	'--shadow-base-color': '#0000000D',
	'--button-secondary-border': 'var(--border-secondary)',
	'--button-secondary-hover-bg': 'var(--bg-surface-hover)',
	'--button-secondary-shadow': '0 1px 2px #0000000d',
	'--button-secondary-hover-shadow': '0 1px 2px #0000000d',
	'--button-outline-shadow': '0 1px 2px #0000000d',
	'--button-outline-hover-shadow': '0 1px 2px #0000000d',
	'--button-quiet-hover-bg': 'var(--bg-surface-hover)',
	'--button-destructive-bg': 'var(--bg-fill-critical)',
	'--button-destructive-text': '#FFFFFF',
	'--focus-ring-width': '2px',
	'--focus-ring-color': 'var(--border-focus)',
	'--hover-ring-width': '0px',
	'--hover-ring-color': 'var(--border-secondary)',
	'--hover-transform': 'none',
	'--hover-shadow': 'none',
	'--active-scale': '0.98',
	'--heading-font-weight': '600',
	'--hero-font-weight': '600',
	'--section-title-font-weight': '600',
	'--card-title-font-weight': '600',
}

export const kumo: Record<string, string> = {
	...defaultPreset,
	...shape,
	...emphasisFinish('primary', 'var(--bg-fill-primary)'),
	...emphasisFinish('destructive', 'var(--bg-fill-critical)'),
	...brandFinishes(),

	'--bg-default': '#FBFBFB',
	'--bg-inverse': '#080808',
	'--bg-muted': '#F2F2F2',
	'--bg-surface-default': '#FFFFFF',
	'--bg-surface-popover': '#FFFFFF',
	'--bg-surface-accent': '#F8F8F8',
	'--bg-surface-field': '#FFFFFF',
	'--bg-surface-hover': '#F5F5F5',
	'--bg-surface-inverse': '#080808',
	'--bg-surface-transparent': '#0000000D',
	'--bg-overlay': '#00000080',
	'--bg-surface-info': '#EFF6FF',
	'--bg-surface-success': '#ECFDF5',
	'--bg-surface-warning': '#FFFBEB',
	'--bg-surface-critical': '#FEF2F2',
	'--bg-surface-emphasis': '#EFF6FF',
	'--bg-surface-brand': '#FFF2E8',
	'--bg-surface-brand-2': '#E7FCFF',
	'--bg-surface-brand-3': '#F6EBFF',
	'--bg-surface-brand-4': '#EDF3FF',
	'--bg-surface-brand-5': '#EBFFF0',
	'--bg-fill-default': '#FFFFFF',
	'--bg-fill-primary': '#056DFF',
	'--bg-fill-secondary': '#FFFFFF',
	'--bg-fill-secondary-inverse': '#171717',
	'--bg-fill-transparent': '#0000000D',
	'--bg-fill-brand': '#FF6A00',
	'--bg-fill-brand-2': '#00C2D6',
	'--bg-fill-brand-3': '#8A00F5',
	'--bg-fill-brand-4': '#0057FF',
	'--bg-fill-brand-5': '#00B83F',
	'--bg-fill-info': '#3B82F6',
	'--bg-fill-success': '#059669',
	'--bg-fill-warning': '#F59E0B',
	'--bg-fill-critical': 'oklch(63.7% 0.237 25.331)',
	'--bg-fill-emphasis': '#056DFF',
	'--text-default': '#171717',
	'--text-secondary': '#737373',
	'--text-muted': '#737373',
	'--text-disabled': '#D4D4D4',
	'--text-inverse': '#F5F5F5',
	'--text-on-fill-primary': '#FFFFFF',
	'--text-on-fill-brand': '#171717',
	'--text-on-fill-secondary': '#171717',
	'--text-on-surface-accent': '#171717',
	'--text-info': '#1E40AF',
	'--text-success': '#065F46',
	'--text-warning': '#A16207',
	'--text-critical': '#B91C1C',
	'--text-emphasis': '#1E40AF',
	'--text-brand': '#A93600',
	'--text-brand-2': '#006778',
	'--text-brand-3': '#7200CA',
	'--text-brand-4': '#0042CC',
	'--text-brand-5': '#006E23',
	'--text-link': '#1E40AF',
	'--icon-default': '#171717',
	'--icon-secondary': '#737373',
	'--icon-disabled': '#D4D4D4',
	'--icon-inverse': '#F5F5F5',
	'--icon-info': '#3B82F6',
	'--icon-success': '#059669',
	'--icon-warning': '#D97706',
	'--icon-critical': '#EF4444',
	'--icon-emphasis': '#056DFF',
	'--icon-brand': '#FF6A00',
	'--icon-brand-2': '#00A5BA',
	'--icon-brand-3': '#8A00F5',
	'--icon-brand-4': '#0057FF',
	'--icon-brand-5': '#00A536',
	'--border-default': '#E9E9E9',
	'--border-secondary': '#1717171A',
	'--border-input': '#1717171A',
	'--border-tertiary': '#D4D4D4',
	'--border-disabled': '#E5E5E5',
	'--border-inverse': '#525252',
	'--border-focus': '#056DFF',
	'--border-info': '#BFDBFE',
	'--border-success': '#A7F3D0',
	'--border-warning': '#FDE68A',
	'--border-critical': '#FECACA',
	'--border-emphasis': '#BFDBFE',
	'--border-brand': '#FFBB8A',
	'--border-brand-2': '#71E5F2',
	'--border-brand-3': '#D1A3FF',
	'--border-brand-4': '#9ABBFF',
	'--border-brand-5': '#80EFA4',
	'--chart-1': '#056DFF',
	'--chart-2': '#FF6A00',
	'--chart-3': '#00B83F',
	'--chart-4': '#8A00F5',
	'--chart-5': '#EF4444',
	'--sidebar-background': '#FBFBFB',
	'--sidebar-foreground': '#171717',
	'--sidebar-primary': '#056DFF',
	'--sidebar-primary-foreground': '#FFFFFF',
	'--sidebar-accent': '#F5F5F5',
	'--sidebar-accent-foreground': '#171717',
	'--sidebar-border': '#E9E9E9',
	'--sidebar-ring': '#056DFF',
}

export const kumoDark: Record<string, string> = {
	...defaultPresetDark,
	...shape,
	...emphasisFinish('primary', 'var(--bg-fill-primary)'),
	...emphasisFinish('destructive', 'var(--bg-fill-critical)'),
	...brandFinishes(),

	'--shadow-base-color': '#0000004D',
	'--bg-default': '#030303',
	'--bg-inverse': '#FBFBFB',
	'--bg-muted': '#0B0B0B',
	'--bg-surface-default': '#0F0F0F',
	'--bg-surface-popover': '#0F0F0F',
	'--bg-surface-accent': '#060606',
	'--bg-surface-field': '#171717',
	'--bg-surface-hover': '#262626',
	'--bg-surface-inverse': '#FBFBFB',
	'--bg-surface-transparent': '#FFFFFF0D',
	'--bg-overlay': '#000000B3',
	'--bg-surface-info': '#101B35',
	'--bg-surface-success': '#0B241B',
	'--bg-surface-warning': '#2B2111',
	'--bg-surface-critical': '#2C1415',
	'--bg-surface-emphasis': '#101B35',
	'--bg-surface-brand': '#311A0A',
	'--bg-surface-brand-2': '#062B31',
	'--bg-surface-brand-3': '#291039',
	'--bg-surface-brand-4': '#0B1C3D',
	'--bg-surface-brand-5': '#082B13',
	'--bg-fill-default': '#0F0F0F',
	'--bg-fill-primary': '#045EDE',
	'--bg-fill-secondary': '#0F0F0F',
	'--bg-fill-secondary-inverse': '#F5F5F5',
	'--bg-fill-transparent': '#FFFFFF0D',
	'--bg-fill-brand': '#FF6A00',
	'--bg-fill-brand-2': '#00D9ED',
	'--bg-fill-brand-3': '#B35CFF',
	'--bg-fill-brand-4': '#4791FF',
	'--bg-fill-brand-5': '#22E65F',
	'--bg-fill-info': '#3B82F6',
	'--bg-fill-success': '#34D399',
	'--bg-fill-warning': '#EA580C',
	'--bg-fill-critical': 'oklch(57.7% 0.245 27.325)',
	'--bg-fill-emphasis': '#045EDE',
	'--text-default': '#F5F5F5',
	'--text-secondary': '#A3A3A3',
	'--text-muted': '#A3A3A3',
	'--text-disabled': '#525252',
	'--text-inverse': '#171717',
	'--text-on-fill-primary': '#FFFFFF',
	'--text-on-fill-brand': '#171717',
	'--text-on-fill-secondary': '#F5F5F5',
	'--text-on-surface-accent': '#F5F5F5',
	'--text-info': '#60A5FA',
	'--text-success': '#A7F3D0',
	'--text-warning': '#FB923C',
	'--text-critical': '#F87171',
	'--text-emphasis': '#60A5FA',
	'--text-brand': '#FFAE70',
	'--text-brand-2': '#66EDFF',
	'--text-brand-3': '#D49AFF',
	'--text-brand-4': '#80B3FF',
	'--text-brand-5': '#6BF593',
	'--text-link': '#60A5FA',
	'--icon-default': '#F5F5F5',
	'--icon-secondary': '#A3A3A3',
	'--icon-disabled': '#525252',
	'--icon-inverse': '#171717',
	'--icon-info': '#60A5FA',
	'--icon-success': '#34D399',
	'--icon-warning': '#FB923C',
	'--icon-critical': '#F87171',
	'--icon-emphasis': '#60A5FA',
	'--icon-brand': '#FF842E',
	'--icon-brand-2': '#00D9ED',
	'--icon-brand-3': '#B35CFF',
	'--icon-brand-4': '#4791FF',
	'--icon-brand-5': '#22E65F',
	'--border-default': '#262626',
	'--border-secondary': '#333333',
	'--border-input': '#333333',
	'--border-tertiary': '#404040',
	'--border-disabled': '#262626',
	'--border-inverse': '#D4D4D4',
	'--border-focus': '#60A5FA',
	'--border-info': '#1E3A8A',
	'--border-success': '#065F46',
	'--border-warning': '#78350F',
	'--border-critical': '#7F1D1D',
	'--border-emphasis': '#1E3A8A',
	'--border-brand': '#A23B00',
	'--border-brand-2': '#007B8A',
	'--border-brand-3': '#7222A8',
	'--border-brand-4': '#174FAD',
	'--border-brand-5': '#00732A',
	'--chart-1': '#60A5FA',
	'--chart-2': '#FF6A00',
	'--chart-3': '#22E65F',
	'--chart-4': '#B35CFF',
	'--chart-5': '#F87171',
	'--sidebar-background': '#030303',
	'--sidebar-foreground': '#F5F5F5',
	'--sidebar-primary': '#045EDE',
	'--sidebar-primary-foreground': '#FFFFFF',
	'--sidebar-accent': '#262626',
	'--sidebar-accent-foreground': '#F5F5F5',
	'--sidebar-border': '#262626',
	'--sidebar-ring': '#60A5FA',
}
