import { defaultPreset, defaultPresetDark } from './default'

/**
 * Signal Pop - bright consumer-tech energy with modular widget shapes.
 *
 * References: electric weather widgets, capsule controls, Swiss-ish brand
 * boards, sticker-like phone graphics. The preset keeps a stable neutral base,
 * then lets semantic brand/status tokens carry the loud color.
 *
 * Fonts:
 *   Body    - IBM Plex Sans: readable product UI.
 *   Heading - Space Grotesk Variable: techy, geometric, still approachable.
 *   Brand   - JetBrains Mono Variable: code/device labels and hero accents.
 */
export const signalPop: Record<string, string> = {
	...defaultPreset,

	// Semantic color tokens
	'--bg-default': '#F4F5F1FF',
	'--bg-inverse': '#050507FF',
	'--bg-muted': '#E8EEF2FF',
	'--bg-surface-default': '#FFFFFFFF',
	'--bg-surface-info': '#DDF2FFFF',
	'--bg-surface-success': '#E3FFD8FF',
	'--bg-surface-warning': '#FFF1B8FF',
	'--bg-surface-critical': '#FFE3DDFF',
	'--bg-surface-emphasis': '#E9E0FFFF',
	'--bg-surface-inverse': '#111217FF',
	'--bg-surface-transparent': '#0B0B0F12',
	'--bg-surface-brand': '#BCE7FFFF',
	'--bg-surface-brand-2': '#F0FF00FF',
	'--bg-surface-brand-3': '#FFE0F4FF',
	'--bg-surface-brand-4': '#FFE0D6FF',
	'--bg-surface-brand-5': '#E0FFD0FF',
	'--bg-surface-hover': '#E7EFF7FF',
	'--bg-fill-default': '#F4F5F1FF',
	'--bg-fill-primary': '#149CFFFF',
	'--bg-fill-brand': '#149CFFFF',
	'--bg-fill-brand-2': '#E7FF00FF',
	'--bg-fill-brand-3': '#FF4DB8FF',
	'--bg-fill-brand-4': '#FF3B16FF',
	'--bg-fill-brand-5': '#4CFF3AFF',
	'--bg-fill-info': '#149CFFFF',
	'--bg-fill-success': '#15C85CFF',
	'--bg-fill-warning': '#FF9F1AFF',
	'--bg-fill-critical': '#FF3B16FF',
	'--bg-fill-emphasis': '#7A5CFFFF',
	'--bg-fill-transparent': '#0B0B0F12',
	'--bg-fill-secondary': '#E7FF00FF',
	'--bg-fill-secondary-inverse': '#050507FF',
	'--text-default': '#0B0B0FFF',
	'--text-secondary': '#2B2D35FF',
	'--text-muted': '#62656FFF',
	'--text-disabled': '#B9BDC6FF',
	'--text-inverse': '#F9FAF2FF',
	'--text-info': '#003B73FF',
	'--text-success': '#064319FF',
	'--text-warning': '#6A3E00FF',
	'--text-critical': '#791500FF',
	'--text-emphasis': '#2B1B8DFF',
	'--text-brand': '#003B73FF',
	'--text-brand-2': '#242900FF',
	'--text-brand-3': '#770044FF',
	'--text-brand-4': '#7A1300FF',
	'--text-brand-5': '#154B00FF',
	'--text-link': '#005DCCFF',
	'--icon-default': '#0B0B0FFF',
	'--icon-secondary': '#2B2D35FF',
	'--icon-disabled': '#C7CBD3FF',
	'--icon-inverse': '#F9FAF2FF',
	'--icon-info': '#149CFFFF',
	'--icon-success': '#15C85CFF',
	'--icon-warning': '#FF9F1AFF',
	'--icon-critical': '#FF3B16FF',
	'--icon-emphasis': '#7A5CFFFF',
	'--icon-brand': '#149CFFFF',
	'--icon-brand-2': '#B7CC00FF',
	'--icon-brand-3': '#FF4DB8FF',
	'--icon-brand-4': '#FF3B16FF',
	'--icon-brand-5': '#2CCB20FF',
	'--border-default': '#0B0B0FFF',
	'--border-secondary': '#2B2D35FF',
	'--border-tertiary': '#70737DFF',
	'--border-disabled': '#C7CBD3FF',
	'--border-inverse': '#F9FAF2FF',
	'--border-focus': '#FF4DB8FF',
	'--border-brand': '#149CFFFF',
	'--border-brand-2': '#B7CC00FF',
	'--border-brand-3': '#FF4DB8FF',
	'--border-brand-4': '#FF3B16FF',
	'--border-brand-5': '#2CCB20FF',
	'--border-info': '#149CFFFF',
	'--border-success': '#15C85CFF',
	'--border-warning': '#FF9F1AFF',
	'--border-critical': '#FF3B16FF',
	'--border-emphasis': '#7A5CFFFF',
	'--chart-1': '#149CFFFF',
	'--chart-2': '#E7FF00FF',
	'--chart-3': '#FF4DB8FF',
	'--chart-4': '#FF3B16FF',
	'--chart-5': '#4CFF3AFF',

	// shadcn / ui compatibility
	'--background': '#F4F5F1FF',
	'--foreground': '#0B0B0FFF',
	'--card': '#FFFFFFFF',
	'--card-foreground': '#0B0B0FFF',
	'--popover': '#FFFFFFFF',
	'--popover-foreground': '#0B0B0FFF',
	'--primary': '#149CFFFF',
	'--primary-foreground': '#050507FF',
	'--secondary': '#E7FF00FF',
	'--secondary-foreground': '#050507FF',
	'--muted': '#E8EEF2FF',
	'--muted-foreground': '#62656FFF',
	'--accent': '#FFE0F4FF',
	'--accent-foreground': '#0B0B0FFF',
	'--destructive': '#FF3B16FF',
	'--border': '#0B0B0FFF',
	'--input': '#0B0B0FFF',
	'--ring': '#FF4DB8FF',
	'--sidebar-background': '#050507FF',
	'--sidebar-foreground': '#F9FAF2FF',
	'--sidebar-primary': '#E7FF00FF',
	'--sidebar-primary-foreground': '#050507FF',
	'--sidebar-accent': '#15161CFF',
	'--sidebar-accent-foreground': '#F9FAF2FF',
	'--sidebar-border': '#050507FF',
	'--sidebar-ring': '#FF4DB8FF',

	// Dimension tokens
	'--border-width-base': '0.125rem',
	'--radius': '1.125rem',
	'--font-size-base': '1rem',
	'--leading-base': '1.25',
	'--letter-spacing-base': '0.01em',
	'--shadow-offset-y': '0px',
	'--shadow-blur': '0px',
	'--shadow-spread': '0px',
	'--shadow-base-color': 'transparent',
	'--dropdown-offset': '8',
	'--overlay-offset': '8',

	// Fonts
	'--font-sans': '"IBM Plex Sans", sans-serif',
	'--font-heading': '"Space Grotesk Variable", "IBM Plex Sans", sans-serif',
	'--font-brand': '"JetBrains Mono Variable", "IBM Plex Mono", monospace',

	// Component tokens
	'--button-radius': 'var(--radius-4xl)',
	'--button-padding-x': 'calc(var(--spacing) * 5)',
	'--button-padding-y': 'calc(var(--spacing) * 2)',
	'--card-radius': 'var(--radius-2xl)',
	'--card-padding': 'calc(var(--spacing) * 6)',
	'--nav-height': 'calc(var(--spacing) * 15)',
	'--section-padding-y': 'calc(var(--spacing) * 24)',
	'--hero-padding-y': 'calc(var(--spacing) * 36)',
	'--input-radius': 'var(--radius-xl)',
	'--input-height': 'calc(var(--spacing) * 11)',
	'--badge-radius': 'var(--radius-4xl)',
	'--border-style': 'solid',
	'--focus-ring-color': '#FF4DB8FF',
	'--focus-ring-width': '0.1875rem',
	'--focus-ring-offset': '0px',
	'--focus-ring-style': 'solid',
	'--hover-ring-color': '#149CFFFF',
	'--hover-ring-width': '0.125rem',
	'--bento-gap': '0.125rem',
	'--space-layout-sm': 'calc(var(--spacing) * 8)',
	'--space-layout-md': 'calc(var(--spacing) * 14)',
	'--space-layout-lg': 'calc(var(--spacing) * 24)',

	// Motion tokens
	'--motion-duration-fast': '120ms',
	'--motion-duration-normal': '180ms',
	'--motion-duration-slow': '260ms',
	'--motion-duration-color': '120ms',
	'--motion-duration-interaction': '140ms',
	'--motion-duration-disclosure': '180ms',
	'--motion-duration-overlay': '140ms',
	'--motion-ease-standard': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
	'--motion-ease-accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
	'--motion-ease-decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
	'--transition-default': 'var(--motion-duration-normal) var(--motion-ease-standard)',
	'--transition-fast': 'var(--motion-duration-fast) var(--motion-ease-standard)',
	'--transition-slow': 'var(--motion-duration-slow) var(--motion-ease-decelerate)',
	'--hover-shadow': 'none',
	'--active-scale': '0.96',

	// Typography composition tokens
	'--heading-font-weight': '700',
	'--heading-letter-spacing': 'var(--tracking-normal)',
	'--body-letter-spacing': 'var(--tracking-normal)',
	'--hero-font-size': 'var(--text-6xl)',
	'--hero-font-weight': '700',
	'--hero-letter-spacing': 'var(--tracking-normal)',
	'--section-title-size': 'var(--text-3xl)',
	'--section-title-font-weight': '700',
	'--section-title-letter-spacing': 'var(--tracking-normal)',
	'--card-title-size': 'var(--text-lg)',
	'--card-title-font-weight': '700',
	'--card-title-letter-spacing': 'var(--tracking-normal)',
}

export const signalPopDark: Record<string, string> = {
	...defaultPresetDark,

	// Semantic color tokens
	'--bg-default': '#202124FF',
	'--bg-inverse': '#F7F8F2FF',
	'--bg-muted': '#121318FF',
	'--bg-surface-default': '#050507FF',
	'--bg-surface-info': '#031D35FF',
	'--bg-surface-success': '#072714FF',
	'--bg-surface-warning': '#2A1E00FF',
	'--bg-surface-critical': '#2C0C07FF',
	'--bg-surface-emphasis': '#160F3DFF',
	'--bg-surface-inverse': '#E7E8E2FF',
	'--bg-surface-transparent': '#FFFFFF12',
	'--bg-surface-brand': '#05233AFF',
	'--bg-surface-brand-2': '#2D3300FF',
	'--bg-surface-brand-3': '#351026FF',
	'--bg-surface-brand-4': '#3A1007FF',
	'--bg-surface-brand-5': '#0D2B08FF',
	'--bg-surface-hover': '#17191FFF',
	'--bg-fill-default': '#202124FF',
	'--bg-fill-primary': '#E7FF00FF',
	'--bg-fill-brand': '#149CFFFF',
	'--bg-fill-brand-2': '#E7FF00FF',
	'--bg-fill-brand-3': '#FF4DB8FF',
	'--bg-fill-brand-4': '#FF3B16FF',
	'--bg-fill-brand-5': '#4CFF3AFF',
	'--bg-fill-info': '#149CFFFF',
	'--bg-fill-success': '#15C85CFF',
	'--bg-fill-warning': '#FFB01FFF',
	'--bg-fill-critical': '#FF3B16FF',
	'--bg-fill-emphasis': '#9D86FFFF',
	'--bg-fill-transparent': '#FFFFFF12',
	'--bg-fill-secondary': '#149CFFFF',
	'--bg-fill-secondary-inverse': '#050507FF',
	'--text-default': '#F7F8F2FF',
	'--text-secondary': '#D7DAD2FF',
	'--text-muted': '#9FA4AEFF',
	'--text-disabled': '#5B606AFF',
	'--text-inverse': '#050507FF',
	'--text-info': '#9CDCFFFF',
	'--text-success': '#A8FF98FF',
	'--text-warning': '#FFE280FF',
	'--text-critical': '#FFB2A6FF',
	'--text-emphasis': '#C5B8FFFF',
	'--text-brand': '#9CDCFFFF',
	'--text-brand-2': '#F0FF65FF',
	'--text-brand-3': '#FF9BDAFF',
	'--text-brand-4': '#FF9A86FF',
	'--text-brand-5': '#A8FF98FF',
	'--text-link': '#71C7FFFF',
	'--icon-default': '#F7F8F2FF',
	'--icon-secondary': '#D7DAD2FF',
	'--icon-disabled': '#494E58FF',
	'--icon-inverse': '#050507FF',
	'--icon-info': '#149CFFFF',
	'--icon-success': '#15C85CFF',
	'--icon-warning': '#FFB01FFF',
	'--icon-critical': '#FF3B16FF',
	'--icon-emphasis': '#9D86FFFF',
	'--icon-brand': '#149CFFFF',
	'--icon-brand-2': '#E7FF00FF',
	'--icon-brand-3': '#FF4DB8FF',
	'--icon-brand-4': '#FF3B16FF',
	'--icon-brand-5': '#4CFF3AFF',
	'--border-default': '#3A3C43FF',
	'--border-secondary': '#4A4C54FF',
	'--border-tertiary': '#6C7078FF',
	'--border-disabled': '#343842FF',
	'--border-inverse': '#F7F8F2FF',
	'--border-focus': '#FF4DB8FF',
	'--border-brand': '#149CFFFF',
	'--border-brand-2': '#E7FF00FF',
	'--border-brand-3': '#FF4DB8FF',
	'--border-brand-4': '#FF3B16FF',
	'--border-brand-5': '#4CFF3AFF',
	'--border-info': '#149CFFFF',
	'--border-success': '#15C85CFF',
	'--border-warning': '#FFB01FFF',
	'--border-critical': '#FF3B16FF',
	'--border-emphasis': '#9D86FFFF',
	'--chart-1': '#149CFFFF',
	'--chart-2': '#E7FF00FF',
	'--chart-3': '#FF4DB8FF',
	'--chart-4': '#FF3B16FF',
	'--chart-5': '#4CFF3AFF',

	// shadcn / ui compatibility
	'--background': '#202124FF',
	'--foreground': '#F7F8F2FF',
	'--card': '#050507FF',
	'--card-foreground': '#F7F8F2FF',
	'--popover': '#050507FF',
	'--popover-foreground': '#F7F8F2FF',
	'--primary': '#E7FF00FF',
	'--primary-foreground': '#050507FF',
	'--secondary': '#149CFFFF',
	'--secondary-foreground': '#050507FF',
	'--muted': '#17191FFF',
	'--muted-foreground': '#9FA4AEFF',
	'--accent': '#351026FF',
	'--accent-foreground': '#F7F8F2FF',
	'--destructive': '#FF3B16FF',
	'--border': '#3A3C43FF',
	'--input': '#4A4C54FF',
	'--ring': '#FF4DB8FF',
	'--sidebar-background': '#050507FF',
	'--sidebar-foreground': '#F7F8F2FF',
	'--sidebar-primary': '#E7FF00FF',
	'--sidebar-primary-foreground': '#050507FF',
	'--sidebar-accent': '#17191FFF',
	'--sidebar-accent-foreground': '#F7F8F2FF',
	'--sidebar-border': '#202124FF',
	'--sidebar-ring': '#FF4DB8FF',

	// Dimension tokens
	'--border-width-base': '0.125rem',
	'--radius': '1.125rem',
	'--font-size-base': '1rem',
	'--leading-base': '1.25',
	'--letter-spacing-base': '0.01em',
	'--shadow-offset-y': '0px',
	'--shadow-blur': '0px',
	'--shadow-spread': '0px',
	'--shadow-base-color': 'transparent',
	'--dropdown-offset': '8',
	'--overlay-offset': '8',

	// Fonts
	'--font-sans': '"IBM Plex Sans", sans-serif',
	'--font-heading': '"Space Grotesk Variable", "IBM Plex Sans", sans-serif',
	'--font-brand': '"JetBrains Mono Variable", "IBM Plex Mono", monospace',

	// Component tokens
	'--button-radius': 'var(--radius-4xl)',
	'--button-padding-x': 'calc(var(--spacing) * 5)',
	'--button-padding-y': 'calc(var(--spacing) * 2)',
	'--card-radius': 'var(--radius-2xl)',
	'--card-padding': 'calc(var(--spacing) * 6)',
	'--nav-height': 'calc(var(--spacing) * 15)',
	'--section-padding-y': 'calc(var(--spacing) * 24)',
	'--hero-padding-y': 'calc(var(--spacing) * 36)',
	'--input-radius': 'var(--radius-xl)',
	'--input-height': 'calc(var(--spacing) * 11)',
	'--badge-radius': 'var(--radius-4xl)',
	'--border-style': 'solid',
	'--focus-ring-color': '#FF4DB8FF',
	'--focus-ring-width': '0.1875rem',
	'--focus-ring-offset': '0px',
	'--focus-ring-style': 'solid',
	'--hover-ring-color': '#149CFFFF',
	'--hover-ring-width': '0.125rem',
	'--bento-gap': '0.125rem',
	'--space-layout-sm': 'calc(var(--spacing) * 8)',
	'--space-layout-md': 'calc(var(--spacing) * 14)',
	'--space-layout-lg': 'calc(var(--spacing) * 24)',

	// Motion tokens
	'--motion-duration-fast': '120ms',
	'--motion-duration-normal': '180ms',
	'--motion-duration-slow': '260ms',
	'--motion-duration-color': '120ms',
	'--motion-duration-interaction': '140ms',
	'--motion-duration-disclosure': '180ms',
	'--motion-duration-overlay': '140ms',
	'--motion-ease-standard': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
	'--motion-ease-accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
	'--motion-ease-decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
	'--transition-default': 'var(--motion-duration-normal) var(--motion-ease-standard)',
	'--transition-fast': 'var(--motion-duration-fast) var(--motion-ease-standard)',
	'--transition-slow': 'var(--motion-duration-slow) var(--motion-ease-decelerate)',
	'--hover-shadow': 'none',
	'--active-scale': '0.96',

	// Typography composition tokens
	'--heading-font-weight': '700',
	'--heading-letter-spacing': 'var(--tracking-normal)',
	'--body-letter-spacing': 'var(--tracking-normal)',
	'--hero-font-size': 'var(--text-6xl)',
	'--hero-font-weight': '700',
	'--hero-letter-spacing': 'var(--tracking-normal)',
	'--section-title-size': 'var(--text-3xl)',
	'--section-title-font-weight': '700',
	'--section-title-letter-spacing': 'var(--tracking-normal)',
	'--card-title-size': 'var(--text-lg)',
	'--card-title-font-weight': '700',
	'--card-title-letter-spacing': 'var(--tracking-normal)',
}
