import { defaultPreset, defaultPresetDark } from './default'

/**
 * Signal Pop - bright consumer-tech energy with modular widget shapes.
 *
 * References: electric weather widgets, capsule controls, Swiss-ish brand
 * boards, sticker-like phone graphics. The preset keeps a stable neutral base,
 * then lets semantic brand/status tokens carry the loud color.
 *
 * Fonts:
 *   Body    - IBM Plex Sans: readable product UI.
 *   Heading - Space Grotesk Variable: techy, geometric, still approachable.
 *   Brand   - JetBrains Mono Variable: code/device labels and hero accents.
 */
export const signalPop: Record<string, string> = {
	...defaultPreset,

	// Semantic color tokens
	'--bg-default': '#F4F5F1FF',
	'--bg-inverse': '#050507FF',
	'--bg-muted': '#E8EEF2FF',
	'--bg-surface-default': '#FFFFFFFF',
	'--bg-surface-info': '#8DE0FFFF',
	'--bg-surface-success': '#B8FF5CFF',
	'--bg-surface-warning': '#FFD43DFF',
	'--bg-surface-critical': '#FFB7A8FF',
	'--bg-surface-emphasis': '#BBA6FFFF',
	'--bg-surface-inverse': '#111217FF',
	'--bg-surface-transparent': '#0B0B0F12',
	'--bg-surface-brand': '#8DE0FFFF',
	'--bg-surface-brand-2': '#EEFF00FF',
	'--bg-surface-brand-3': '#FF8BD3FF',
	'--bg-surface-brand-4': '#FF8A70FF',
	'--bg-surface-brand-5': '#A7FF5AFF',
	'--bg-surface-hover': '#E7EFF7FF',
	'--bg-fill-default': '#F4F5F1FF',
	'--bg-fill-primary': '#006FE6FF',
	'--bg-fill-brand': '#006FE6FF',
	'--bg-fill-brand-2': '#EEFF00FF',
	'--bg-fill-brand-3': '#FF4DB8FF',
	'--bg-fill-brand-4': '#FF3B16FF',
	'--bg-fill-brand-5': '#39F21EFF',
	'--bg-fill-info': '#006FE6FF',
	'--bg-fill-success': '#00D85BFF',
	'--bg-fill-warning': '#FFB000FF',
	'--bg-fill-critical': '#A61B00FF',
	'--bg-fill-emphasis': '#7A5CFFFF',
	'--bg-fill-transparent': '#0B0B0F12',
	'--bg-fill-secondary': '#EEFF00FF',
	'--bg-fill-secondary-inverse': '#050507FF',
	'--text-default': '#0B0B0FFF',
	'--text-secondary': '#2B2D35FF',
	'--text-muted': '#62656FFF',
	'--text-disabled': '#B9BDC6FF',
	'--text-inverse': '#F9FAF2FF',
	'--text-info': '#003B73FF',
	'--text-success': '#064319FF',
	'--text-warning': '#4A2600FF',
	'--text-critical': '#A61B00FF',
	'--text-emphasis': '#2B1B8DFF',
	'--text-brand': '#003B73FF',
	'--text-brand-2': '#242900FF',
	'--text-brand-3': '#770044FF',
	'--text-brand-4': '#7A1300FF',
	'--text-brand-5': '#154B00FF',
	'--text-link': '#005DCCFF',
	'--icon-default': '#0B0B0FFF',
	'--icon-secondary': '#2B2D35FF',
	'--icon-disabled': '#C7CBD3FF',
	'--icon-inverse': '#F9FAF2FF',
	'--icon-info': '#006FE6FF',
	'--icon-success': '#00D85BFF',
	'--icon-warning': '#FFB000FF',
	'--icon-critical': '#FF3B16FF',
	'--icon-emphasis': '#7A5CFFFF',
	'--icon-brand': '#006FE6FF',
	'--icon-brand-2': '#B7CC00FF',
	'--icon-brand-3': '#FF4DB8FF',
	'--icon-brand-4': '#FF3B16FF',
	'--icon-brand-5': '#39F21EFF',
	'--border-default': '#00000000',
	'--border-secondary': '#00000000',
	'--border-tertiary': '#00000000',
	'--border-disabled': '#00000000',
	'--border-inverse': '#F9FAF2FF',
	'--border-focus': '#FF4DB8FF',
	'--border-brand': '#006FE6FF',
	'--border-brand-2': '#B7CC00FF',
	'--border-brand-3': '#FF4DB8FF',
	'--border-brand-4': '#FF3B16FF',
	'--border-brand-5': '#39F21EFF',
	'--border-info': '#006FE6FF',
	'--border-success': '#00D85BFF',
	'--border-warning': '#FFB000FF',
	'--border-critical': '#FF3B16FF',
	'--border-emphasis': '#7A5CFFFF',
	'--chart-1': '#006FE6FF',
	'--chart-2': '#EEFF00FF',
	'--chart-3': '#FF4DB8FF',
	'--chart-4': '#FF3B16FF',
	'--chart-5': '#39F21EFF',

	// shadcn / ui compatibility
	'--background': '#F4F5F1FF',
	'--foreground': '#0B0B0FFF',
	'--card': '#FFFFFFFF',
	'--card-foreground': '#0B0B0FFF',
	'--popover': '#FFFFFFFF',
	'--popover-foreground': '#0B0B0FFF',
	'--primary': '#006FE6FF',
	'--primary-foreground': '#FFFFFFFF',
	'--secondary': '#EEFF00FF',
	'--secondary-foreground': '#050507FF',
	'--muted': '#E8EEF2FF',
	'--muted-foreground': '#62656FFF',
	'--accent': '#FF8BD3FF',
	'--accent-foreground': '#0B0B0FFF',
	'--destructive': '#A61B00FF',
	'--border': '#00000000',
	'--input': '#00000000',
	'--ring': '#FF4DB8FF',
	'--sidebar-background': '#050507FF',
	'--sidebar-foreground': '#F9FAF2FF',
	'--sidebar-primary': '#EEFF00FF',
	'--sidebar-primary-foreground': '#050507FF',
	'--sidebar-accent': '#15161CFF',
	'--sidebar-accent-foreground': '#F9FAF2FF',
	'--sidebar-border': '#00000000',
	'--sidebar-ring': '#FF4DB8FF',

	// Dimension tokens
	'--spacing': '0.328125rem',
	'--border-width-base': '0rem',
	'--radius': '1.125rem',
	'--font-size-base': '1rem',
	'--leading-base': '1.25',
	'--letter-spacing-base': '0.01em',
	'--shadow-offset-y': '0px',
	'--shadow-blur': '0px',
	'--shadow-spread': '0px',
	'--shadow-base-color': 'transparent',
	'--dropdown-offset': '8',
	'--overlay-offset': '8',

	// Fonts
	'--font-sans': '"IBM Plex Sans", sans-serif',
	'--font-heading': '"Space Grotesk Variable", "IBM Plex Sans", sans-serif',
	'--font-brand': '"JetBrains Mono Variable", "IBM Plex Mono", monospace',

	// Component tokens
	'--button-radius': 'var(--radius-4xl)',
	'--button-padding-x': 'calc(var(--spacing) * 6)',
	'--button-padding-y': 'calc(var(--spacing) * 2.5)',
	'--card-radius': 'var(--radius-2xl)',
	'--card-padding': 'calc(var(--spacing) * 7)',
	'--nav-height': 'calc(var(--spacing) * 16)',
	'--section-padding-y': 'calc(var(--spacing) * 28)',
	'--hero-padding-y': 'calc(var(--spacing) * 40)',
	'--input-radius': 'var(--radius-xl)',
	'--input-height': 'calc(var(--spacing) * 12)',
	'--badge-radius': 'var(--radius-4xl)',
	'--border-style': 'solid',
	'--focus-ring-color': '#FF4DB8FF',
	'--focus-ring-width': '0.1875rem',
	'--focus-ring-offset': '0px',
	'--focus-ring-style': 'solid',
	'--hover-ring-color': '#006FE6FF',
	'--hover-ring-width': '0rem',
	'--bento-gap': 'calc(var(--spacing) * 3)',
	'--space-layout-sm': 'calc(var(--spacing) * 9)',
	'--space-layout-md': 'calc(var(--spacing) * 15)',
	'--space-layout-lg': 'calc(var(--spacing) * 26)',

	// Motion tokens
	'--motion-duration-fast': '120ms',
	'--motion-duration-normal': '180ms',
	'--motion-duration-slow': '260ms',
	'--motion-duration-color': '120ms',
	'--motion-duration-interaction': '140ms',
	'--motion-duration-disclosure': '180ms',
	'--motion-duration-overlay': '140ms',
	'--motion-ease-standard': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
	'--motion-ease-accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
	'--motion-ease-decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
	'--transition-default': 'var(--motion-duration-normal) var(--motion-ease-standard)',
	'--transition-fast': 'var(--motion-duration-fast) var(--motion-ease-standard)',
	'--transition-slow': 'var(--motion-duration-slow) var(--motion-ease-decelerate)',
	'--hover-shadow': 'none',
	'--active-scale': '0.96',

	// Typography composition tokens
	'--heading-font-weight': '700',
	'--heading-letter-spacing': 'var(--tracking-normal)',
	'--body-letter-spacing': 'var(--tracking-normal)',
	'--hero-font-size': 'var(--text-6xl)',
	'--hero-font-weight': '700',
	'--hero-letter-spacing': 'var(--tracking-normal)',
	'--section-title-size': 'var(--text-3xl)',
	'--section-title-font-weight': '700',
	'--section-title-letter-spacing': 'var(--tracking-normal)',
	'--card-title-size': 'var(--text-lg)',
	'--card-title-font-weight': '700',
	'--card-title-letter-spacing': 'var(--tracking-normal)',
}

export const signalPopDark: Record<string, string> = {
	...defaultPresetDark,

	// Semantic color tokens
	'--bg-default': '#202124FF',
	'--bg-inverse': '#F7F8F2FF',
	'--bg-muted': '#121318FF',
	'--bg-surface-default': '#050507FF',
	'--bg-surface-info': '#053B63FF',
	'--bg-surface-success': '#093A18FF',
	'--bg-surface-warning': '#3A2900FF',
	'--bg-surface-critical': '#3A1208FF',
	'--bg-surface-emphasis': '#251064FF',
	'--bg-surface-inverse': '#E7E8E2FF',
	'--bg-surface-transparent': '#FFFFFF12',
	'--bg-surface-brand': '#053B63FF',
	'--bg-surface-brand-2': '#343A00FF',
	'--bg-surface-brand-3': '#451331FF',
	'--bg-surface-brand-4': '#471508FF',
	'--bg-surface-brand-5': '#113A08FF',
	'--bg-surface-hover': '#17191FFF',
	'--bg-fill-default': '#202124FF',
	'--bg-fill-primary': '#006FE6FF',
	'--bg-fill-brand': '#006FE6FF',
	'--bg-fill-brand-2': '#EEFF00FF',
	'--bg-fill-brand-3': '#FF4DB8FF',
	'--bg-fill-brand-4': '#FF3B16FF',
	'--bg-fill-brand-5': '#4CFF3AFF',
	'--bg-fill-info': '#006FE6FF',
	'--bg-fill-success': '#15C85CFF',
	'--bg-fill-warning': '#FFB000FF',
	'--bg-fill-critical': '#FF6A4DFF',
	'--bg-fill-emphasis': '#9D86FFFF',
	'--bg-fill-transparent': '#FFFFFF12',
	'--bg-fill-secondary': '#EEFF00FF',
	'--bg-fill-secondary-inverse': '#050507FF',
	'--text-default': '#F7F8F2FF',
	'--text-secondary': '#D7DAD2FF',
	'--text-muted': '#9FA4AEFF',
	'--text-disabled': '#5B606AFF',
	'--text-inverse': '#050507FF',
	'--text-info': '#9CDCFFFF',
	'--text-success': '#B8FF5CFF',
	'--text-warning': '#FFD43DFF',
	'--text-critical': '#FF8A70FF',
	'--text-emphasis': '#C5B8FFFF',
	'--text-brand': '#9CDCFFFF',
	'--text-brand-2': '#F0FF65FF',
	'--text-brand-3': '#FF8BD3FF',
	'--text-brand-4': '#FF9A86FF',
	'--text-brand-5': '#B8FF5CFF',
	'--text-link': '#71C7FFFF',
	'--icon-default': '#F7F8F2FF',
	'--icon-secondary': '#D7DAD2FF',
	'--icon-disabled': '#494E58FF',
	'--icon-inverse': '#050507FF',
	'--icon-info': '#149CFFFF',
	'--icon-success': '#15C85CFF',
	'--icon-warning': '#FFB000FF',
	'--icon-critical': '#FF3B16FF',
	'--icon-emphasis': '#9D86FFFF',
	'--icon-brand': '#149CFFFF',
	'--icon-brand-2': '#EEFF00FF',
	'--icon-brand-3': '#FF4DB8FF',
	'--icon-brand-4': '#FF3B16FF',
	'--icon-brand-5': '#4CFF3AFF',
	'--border-default': '#00000000',
	'--border-secondary': '#00000000',
	'--border-tertiary': '#00000000',
	'--border-disabled': '#00000000',
	'--border-inverse': '#F7F8F2FF',
	'--border-focus': '#FF4DB8FF',
	'--border-brand': '#149CFFFF',
	'--border-brand-2': '#EEFF00FF',
	'--border-brand-3': '#FF4DB8FF',
	'--border-brand-4': '#FF3B16FF',
	'--border-brand-5': '#4CFF3AFF',
	'--border-info': '#149CFFFF',
	'--border-success': '#15C85CFF',
	'--border-warning': '#FFB000FF',
	'--border-critical': '#FF6A4DFF',
	'--border-emphasis': '#9D86FFFF',
	'--chart-1': '#149CFFFF',
	'--chart-2': '#EEFF00FF',
	'--chart-3': '#FF4DB8FF',
	'--chart-4': '#FF3B16FF',
	'--chart-5': '#4CFF3AFF',

	// shadcn / ui compatibility
	'--background': '#202124FF',
	'--foreground': '#F7F8F2FF',
	'--card': '#050507FF',
	'--card-foreground': '#F7F8F2FF',
	'--popover': '#050507FF',
	'--popover-foreground': '#F7F8F2FF',
	'--primary': '#006FE6FF',
	'--primary-foreground': '#FFFFFFFF',
	'--secondary': '#EEFF00FF',
	'--secondary-foreground': '#050507FF',
	'--muted': '#17191FFF',
	'--muted-foreground': '#9FA4AEFF',
	'--accent': '#351026FF',
	'--accent-foreground': '#F7F8F2FF',
	'--destructive': '#FF6A4DFF',
	'--border': '#00000000',
	'--input': '#00000000',
	'--ring': '#FF4DB8FF',
	'--sidebar-background': '#050507FF',
	'--sidebar-foreground': '#F7F8F2FF',
	'--sidebar-primary': '#EEFF00FF',
	'--sidebar-primary-foreground': '#050507FF',
	'--sidebar-accent': '#17191FFF',
	'--sidebar-accent-foreground': '#F7F8F2FF',
	'--sidebar-border': '#00000000',
	'--sidebar-ring': '#FF4DB8FF',

	// Dimension tokens
	'--spacing': '0.328125rem',
	'--border-width-base': '0rem',
	'--radius': '1.125rem',
	'--font-size-base': '1rem',
	'--leading-base': '1.25',
	'--letter-spacing-base': '0.01em',
	'--shadow-offset-y': '0px',
	'--shadow-blur': '0px',
	'--shadow-spread': '0px',
	'--shadow-base-color': 'transparent',
	'--dropdown-offset': '8',
	'--overlay-offset': '8',

	// Fonts
	'--font-sans': '"IBM Plex Sans", sans-serif',
	'--font-heading': '"Space Grotesk Variable", "IBM Plex Sans", sans-serif',
	'--font-brand': '"JetBrains Mono Variable", "IBM Plex Mono", monospace',

	// Component tokens
	'--button-radius': 'var(--radius-4xl)',
	'--button-padding-x': 'calc(var(--spacing) * 6)',
	'--button-padding-y': 'calc(var(--spacing) * 2.5)',
	'--card-radius': 'var(--radius-2xl)',
	'--card-padding': 'calc(var(--spacing) * 7)',
	'--nav-height': 'calc(var(--spacing) * 16)',
	'--section-padding-y': 'calc(var(--spacing) * 28)',
	'--hero-padding-y': 'calc(var(--spacing) * 40)',
	'--input-radius': 'var(--radius-xl)',
	'--input-height': 'calc(var(--spacing) * 12)',
	'--badge-radius': 'var(--radius-4xl)',
	'--border-style': 'solid',
	'--focus-ring-color': '#FF4DB8FF',
	'--focus-ring-width': '0.1875rem',
	'--focus-ring-offset': '0px',
	'--focus-ring-style': 'solid',
	'--hover-ring-color': '#006FE6FF',
	'--hover-ring-width': '0rem',
	'--bento-gap': 'calc(var(--spacing) * 3)',
	'--space-layout-sm': 'calc(var(--spacing) * 9)',
	'--space-layout-md': 'calc(var(--spacing) * 15)',
	'--space-layout-lg': 'calc(var(--spacing) * 26)',

	// Motion tokens
	'--motion-duration-fast': '120ms',
	'--motion-duration-normal': '180ms',
	'--motion-duration-slow': '260ms',
	'--motion-duration-color': '120ms',
	'--motion-duration-interaction': '140ms',
	'--motion-duration-disclosure': '180ms',
	'--motion-duration-overlay': '140ms',
	'--motion-ease-standard': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
	'--motion-ease-accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
	'--motion-ease-decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
	'--transition-default': 'var(--motion-duration-normal) var(--motion-ease-standard)',
	'--transition-fast': 'var(--motion-duration-fast) var(--motion-ease-standard)',
	'--transition-slow': 'var(--motion-duration-slow) var(--motion-ease-decelerate)',
	'--hover-shadow': 'none',
	'--active-scale': '0.96',

	// Typography composition tokens
	'--heading-font-weight': '700',
	'--heading-letter-spacing': 'var(--tracking-normal)',
	'--body-letter-spacing': 'var(--tracking-normal)',
	'--hero-font-size': 'var(--text-6xl)',
	'--hero-font-weight': '700',
	'--hero-letter-spacing': 'var(--tracking-normal)',
	'--section-title-size': 'var(--text-3xl)',
	'--section-title-font-weight': '700',
	'--section-title-letter-spacing': 'var(--tracking-normal)',
	'--card-title-size': 'var(--text-lg)',
	'--card-title-font-weight': '700',
	'--card-title-letter-spacing': 'var(--tracking-normal)',
}
