export {
	Attachments as AIAttachments,
	Attachment as AIAttachment,
	AttachmentPreview as AIAttachmentPreview,
	AttachmentInfo as AIAttachmentInfo,
	AttachmentRemove as AIAttachmentRemove,
	AttachmentHoverCard as AIAttachmentHoverCard,
	AttachmentHoverCardTrigger as AIAttachmentHoverCardTrigger,
	AttachmentHoverCardContent as AIAttachmentHoverCardContent,
	AttachmentEmpty as AIAttachmentEmpty,
	useAttachmentsContext,
	useAttachmentContext,
	getMediaCategory,
	getAttachmentLabel,
	type AttachmentsProps as AIAttachmentsProps,
	type AttachmentProps as AIAttachmentProps,
	type AttachmentPreviewProps as AIAttachmentPreviewProps,
	type AttachmentInfoProps as AIAttachmentInfoProps,
	type AttachmentRemoveProps as AIAttachmentRemoveProps,
	type AttachmentHoverCardProps as AIAttachmentHoverCardProps,
	type AttachmentHoverCardTriggerProps as AIAttachmentHoverCardTriggerProps,
	type AttachmentHoverCardContentProps as AIAttachmentHoverCardContentProps,
	type AttachmentEmptyProps as AIAttachmentEmptyProps,
	type AttachmentData,
	type AttachmentMediaCategory,
	type AttachmentVariant,
} from '../_internal/ai-elements/attachments'
