export {
	PromptInput as AIPromptInput,
	PromptInputProvider as AIPromptInputProvider,
	PromptInputTextarea as AIPromptInputTextarea,
	PromptInputHeader as AIPromptInputHeader,
	PromptInputFooter as AIPromptInputFooter,
	PromptInputBody as AIPromptInputBody,
	PromptInputTools as AIPromptInputTools,
	PromptInputButton as AIPromptInputButton,
	PromptInputSubmit as AIPromptInputSubmit,
	PromptInputActionMenu as AIPromptInputActionMenu,
	PromptInputActionMenuTrigger as AIPromptInputActionMenuTrigger,
	PromptInputActionMenuContent as AIPromptInputActionMenuContent,
	PromptInputActionMenuItem as AIPromptInputActionMenuItem,
	PromptInputActionAddAttachments as AIPromptInputActionAddAttachments,
	PromptInputActionAddScreenshot as AIPromptInputActionAddScreenshot,
	PromptInputSelect as AIPromptInputSelect,
	PromptInputSelectTrigger as AIPromptInputSelectTrigger,
	PromptInputSelectContent as AIPromptInputSelectContent,
	PromptInputSelectItem as AIPromptInputSelectItem,
	PromptInputSelectValue as AIPromptInputSelectValue,
	usePromptInputController,
	usePromptInputAttachments,
	usePromptInputReferencedSources,
	useProviderAttachments,
	type PromptInputProps as AIPromptInputProps,
	type PromptInputSubmitProps as AIPromptInputSubmitProps,
	type PromptInputMessage,
} from '../_internal/ai-elements/prompt-input'
