// Generated by scripts/generate-showcase-routes.ts.
import { createFileRoute } from '@tanstack/react-router'
import { AIElementRoute } from '@/ai-element-route'

export const Route = createFileRoute('/ai-elements/chain-of-thought/')({
	component: () => <AIElementRoute slug="chain-of-thought" />,
})
