/**
 * Brutalist — Raw, architectural, uncompromising.
 * Studied references: Bloomberg Terminal aesthetic, Balenciaga.com restraint,
 * Ssense editorial rigour. High contrast without being garish.
 *
 * This is not the parody version (no neon yellow). Real brutalism is
 * about structural honesty: things look exactly like what they are.
 *
 * Fonts:
 *   Heading — Space Grotesk Variable: constructed, slightly mechanical,
 *             pairs well with mono body without feeling like a joke.
 *   Body    — IBM Plex Mono: the Bloomberg terminal aesthetic. Readable,
 *             functional, carries authority. Uncompromising.
 *
 * Character: zero border-radius, heavy borders, hard offset shadows,
 * instant transitions, high contrast palette with a single editorial red.
 */
export const brutalist: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	"--bg-default": "#FFFFFFFF",
	"--bg-inverse": "#0A0A0AFF",
	"--bg-muted": "#F0F0F0FF",
	"--bg-surface-default": "#FFFFFFFF",
	"--bg-surface-info": "#E8F0F8FF",
	"--bg-surface-success": "#E8F4E8FF",
	"--bg-surface-warning": "#FBF4E0FF",
	"--bg-surface-critical": "#FAE8E8FF",
	"--bg-surface-emphasis": "#E8E8F4FF",
	"--bg-surface-inverse": "#3A3A3AFF",
	"--bg-surface-transparent": "#00000010",
	"--bg-surface-brand": "#FFEFEBFF",
	"--bg-surface-hover": "#F0F0F0FF",
	"--bg-fill-default": "#FFFFFFFF",
	"--bg-fill-primary": "#0A0A0AFF",
	"--bg-fill-brand": "#CC2200FF",
	"--bg-fill-info": "#0044AAFF",
	"--bg-fill-success": "#007700FF",
	"--bg-fill-warning": "#CC6600FF",
	"--bg-fill-critical": "#CC0000FF",
	"--bg-fill-emphasis": "#0A0A0AFF",
	"--bg-fill-transparent": "#00000010",
	"--bg-fill-secondary": "#0A0A0AFF",
	"--bg-fill-secondary-inverse": "#FFFFFFFF",
	"--text-default": "#0A0A0AFF",
	"--text-secondary": "#2E2E2EFF",
	"--text-muted": "#5A5A5AFF",
	"--text-disabled": "#AAAAAAFF",
	"--text-inverse": "#F8F8F8FF",
	"--text-info": "#001E5EFF",
	"--text-success": "#003A00FF",
	"--text-warning": "#5E2E00FF",
	"--text-critical": "#5E0000FF",
	"--text-emphasis": "#001E5EFF",
	"--text-brand": "#880000FF",
	"--text-link": "#CC2200FF",
	"--icon-default": "#0A0A0AFF",
	"--icon-secondary": "#2E2E2EFF",
	"--icon-disabled": "#CCCCCCFF",
	"--icon-inverse": "#F8F8F8FF",
	"--icon-info": "#0044AAFF",
	"--icon-success": "#007700FF",
	"--icon-warning": "#AA5500FF",
	"--icon-critical": "#AA0000FF",
	"--icon-emphasis": "#0044AAFF",
	"--icon-brand": "#CC2200FF",
	"--border-default": "#0A0A0AFF",
	"--border-secondary": "#0A0A0AFF",
	"--border-tertiary": "#4A4A4AFF",
	"--border-disabled": "#AAAAAAFF",
	"--border-inverse": "#F8F8F8FF",
	"--border-focus": "#CC2200FF",
	"--border-brand": "#CC2200FF",
	"--border-info": "#0044AAFF",
	"--border-success": "#007700FF",
	"--border-warning": "#AA5500FF",
	"--border-critical": "#AA0000FF",
	"--border-emphasis": "#0044AAFF",
	"--chart-1": "#0A0A0AFF",
	"--chart-2": "#CC2200FF",
	"--chart-3": "#4A4A4AFF",
	"--chart-4": "#007700FF",
	"--chart-5": "#0044AAFF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#FFFFFFFF",
	"--foreground": "#0A0A0AFF",
	"--card": "#FFFFFFFF",
	"--card-foreground": "#0A0A0AFF",
	"--popover": "#FFFFFFFF",
	"--popover-foreground": "#0A0A0AFF",
	"--primary": "#0A0A0AFF",
	"--primary-foreground": "#FFFFFFFF",
	"--secondary": "#F0F0F0FF",
	"--secondary-foreground": "#0A0A0AFF",
	"--muted": "#F0F0F0FF",
	"--muted-foreground": "#5A5A5AFF",
	"--accent": "#F0F0F0FF",
	"--accent-foreground": "#0A0A0AFF",
	"--destructive": "#CC0000FF",
	"--border": "#0A0A0AFF",
	"--input": "#C8C8C8FF",
	"--ring": "#CC2200FF",
	"--sidebar-background": "#FFFFFFFF",
	"--sidebar-foreground": "#0A0A0AFF",
	"--sidebar-primary": "#0A0A0AFF",
	"--sidebar-primary-foreground": "#FFFFFFFF",
	"--sidebar-accent": "#F0F0F0FF",
	"--sidebar-accent-foreground": "#0A0A0AFF",
	"--sidebar-border": "#0A0A0AFF",
	"--sidebar-ring": "#CC2200FF",

	// ── Dimension tokens ──────────────────────────────────────────────────
	"--spacing": "0.25rem",
	"--border-width-base": "0.125rem",
	"--radius": "0rem",
	"--font-size-base": "1rem",
	"--leading-base": "1.4",
	"--letter-spacing-base": "0.04em",
	"--opacity-hover": "1",
	"--opacity-active": "1",
	"--opacity-disabled": "0.5",
	// Hard offset shadow — structural, no blur (that's the brutalist shadow)
	"--shadow-offset-y": "4px",
	"--shadow-blur": "0px",
	"--shadow-spread": "0px",
	"--shadow-base-color": "rgba(0, 0, 0, 1)",
	"--container-sm": "680px",
	"--container-md": "820px",
	"--container-lg": "1100px",
	"--container-xl": "1380px",
	"--container-2xl": "1560px",
	"--dropdown-offset": "0",
	"--overlay-offset": "0",

	// ── Fonts: Space Grotesk for both heading and body ────────────────────
	// Real editorial brutalism (Bloomberg, Ssense) uses grotesque sans for body;
	// mono is reserved for accents/code — not the entire body text.
	"--font-sans": '"Space Grotesk Variable", "Arial", sans-serif',
	"--font-heading": '"Space Grotesk Variable", "Arial", sans-serif',
	"--font-brand": '"Space Grotesk Variable", "Arial", sans-serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	// Zero radius everywhere — things are what they are
	"--button-radius": "0px",
	"--button-padding-x": "calc(var(--spacing) * 5)",
	"--button-padding-y": "calc(var(--spacing) * 2)",
	"--card-radius": "0px",
	"--card-padding": "calc(var(--spacing) * 6)",
	"--nav-height": "calc(var(--spacing) * 14)",
	"--section-padding-y": "calc(var(--spacing) * 20)",
	"--hero-padding-y": "calc(var(--spacing) * 32)",
	"--input-radius": "0px",
	"--input-height": "calc(var(--spacing) * 10)",
	"--badge-radius": "0px",

	// ── Phase 1b: Motion — instant. No decorative animation. ─────────────
	"--transition-default": "0ms linear",
	"--transition-fast": "0ms linear",
	"--transition-slow": "50ms linear",
	"--hover-transform": "none",
	"--hover-shadow": "none",
	"--active-scale": "1",

	// ── Phase 1c: Typography — heavy, structural ──────────────────────────
	"--heading-font-weight": "700",
	"--heading-letter-spacing": "var(--tracking-tight)",
	"--body-letter-spacing": "var(--tracking-normal)",
	"--hero-font-size": "var(--text-6xl)",
	"--hero-font-weight": "700",
	"--hero-letter-spacing": "var(--tracking-tight)",
	"--section-title-size": "var(--text-3xl)",
	"--section-title-font-weight": "700",
	"--section-title-letter-spacing": "var(--tracking-tight)",
	"--card-title-size": "var(--text-base)",
	"--card-title-font-weight": "700",
	"--card-title-letter-spacing": "var(--tracking-normal)",
}

export const brutalistDark: Record<string, string> = {
	// ── Dark: inverted — paper becomes black, ink becomes off-white ───────
	"--bg-default": "#0A0A0AFF",
	"--bg-inverse": "#F8F8F8FF",
	"--bg-muted": "#141414FF",
	"--bg-surface-default": "#0A0A0AFF",
	"--bg-surface-info": "#0A1828FF",
	"--bg-surface-success": "#0A180AFF",
	"--bg-surface-warning": "#1E1406FF",
	"--bg-surface-critical": "#1E0A0AFF",
	"--bg-surface-emphasis": "#0A0A1EFF",
	"--bg-surface-inverse": "#606060FF",
	"--bg-surface-transparent": "#FFFFFF10",
	"--bg-surface-brand": "#1E0A08FF",
	"--bg-surface-hover": "#1A1A1AFF",
	"--bg-fill-default": "#0A0A0AFF",
	"--bg-fill-primary": "#F0F0F0FF",
	"--bg-fill-brand": "#FF3322FF",
	"--bg-fill-info": "#3366CCFF",
	"--bg-fill-success": "#009900FF",
	"--bg-fill-warning": "#DD7700FF",
	"--bg-fill-critical": "#DD2222FF",
	"--bg-fill-emphasis": "#F0F0F0FF",
	"--bg-fill-transparent": "#FFFFFF10",
	"--bg-fill-secondary": "#F0F0F0FF",
	"--bg-fill-secondary-inverse": "#0A0A0AFF",
	"--text-default": "#F0F0F0FF",
	"--text-secondary": "#C0C0C0FF",
	"--text-muted": "#888888FF",
	"--text-disabled": "#444444FF",
	"--text-inverse": "#0A0A0AFF",
	"--text-info": "#99BBFFFF",
	"--text-success": "#77DD77FF",
	"--text-warning": "#FFBB44FF",
	"--text-critical": "#FF7777FF",
	"--text-emphasis": "#CCCCFFFF",
	"--text-brand": "#FF9988FF",
	"--text-link": "#FF5533FF",
	"--icon-default": "#F0F0F0FF",
	"--icon-secondary": "#C0C0C0FF",
	"--icon-disabled": "#383838FF",
	"--icon-inverse": "#0A0A0AFF",
	"--icon-info": "#5588EEFF",
	"--icon-success": "#44BB44FF",
	"--icon-warning": "#CC8800FF",
	"--icon-critical": "#DD3333FF",
	"--icon-emphasis": "#5588EEFF",
	"--icon-brand": "#FF4433FF",
	"--border-default": "#F0F0F0FF",
	"--border-secondary": "#C0C0C0FF",
	"--border-tertiary": "#888888FF",
	"--border-disabled": "#444444FF",
	"--border-inverse": "#0A0A0AFF",
	"--border-focus": "#FF3322FF",
	"--border-brand": "#FF3322FF",
	"--border-info": "#3366CCFF",
	"--border-success": "#009900FF",
	"--border-warning": "#CC6600FF",
	"--border-critical": "#CC1111FF",
	"--border-emphasis": "#3366CCFF",
	"--chart-1": "#F0F0F0FF",
	"--chart-2": "#FF3322FF",
	"--chart-3": "#888888FF",
	"--chart-4": "#44BB44FF",
	"--chart-5": "#5588EEFF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#0A0A0AFF",
	"--foreground": "#F0F0F0FF",
	"--card": "#0A0A0AFF",
	"--card-foreground": "#F0F0F0FF",
	"--popover": "#141414FF",
	"--popover-foreground": "#F0F0F0FF",
	"--primary": "#F0F0F0FF",
	"--primary-foreground": "#0A0A0AFF",
	"--secondary": "#1A1A1AFF",
	"--secondary-foreground": "#F0F0F0FF",
	"--muted": "#1A1A1AFF",
	"--muted-foreground": "#888888FF",
	"--accent": "#1A1A1AFF",
	"--accent-foreground": "#F0F0F0FF",
	"--destructive": "#DD2222FF",
	"--border": "#F0F0F0FF",
	"--input": "#383838FF",
	"--ring": "#FF3322FF",
	"--sidebar-background": "#0A0A0AFF",
	"--sidebar-foreground": "#F0F0F0FF",
	"--sidebar-primary": "#F0F0F0FF",
	"--sidebar-primary-foreground": "#0A0A0AFF",
	"--sidebar-accent": "#1A1A1AFF",
	"--sidebar-accent-foreground": "#F0F0F0FF",
	"--sidebar-border": "#F0F0F0FF",
	"--sidebar-ring": "#FF3322FF",

	// ── Fonts carry over ──────────────────────────────────────────────────
	"--font-sans": '"Space Grotesk Variable", "Arial", sans-serif',
	"--font-heading": '"Space Grotesk Variable", "Arial", sans-serif',
	"--font-brand": '"Space Grotesk Variable", "Arial", sans-serif',
}
