/**
 * Default — Clean, neutral, Inter-based. The "no opinion" starting point.
 * Think Linear, Vercel. A solid foundation that stays out of the way.
 *
 * Fonts: Inter Variable (all) — the most carefully crafted neutral sans-serif.
 */
export const defaultPreset: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	"--bg-default": "#F9F9F8FF",
	"--bg-inverse": "#21201CFF",
	"--bg-muted": "#F1F0EFFF",
	"--bg-surface-default": "#F9F9F8FF",
	"--bg-surface-info": "#F1FAFDFF",
	"--bg-surface-success": "#F5FBF5FF",
	"--bg-surface-warning": "#FFF7EDFF",
	"--bg-surface-critical": "#FFF7F7FF",
	"--bg-surface-emphasis": "#F4FAFFFF",
	"--bg-surface-inverse": "#63635EFF",
	"--bg-surface-transparent": "#0000000D",
	"--bg-surface-brand": "#FEF7FBFF",
	"--bg-surface-hover": "#F1F0EFFF",
	"--bg-fill-default": "#F9F9F8FF",
	"--bg-fill-primary": "#21201CFF",
	"--bg-fill-brand": "#D6409FFF",
	"--bg-fill-info": "#7CE2FEFF",
	"--bg-fill-success": "#46A758FF",
	"--bg-fill-warning": "#F76B15FF",
	"--bg-fill-critical": "#E5484DFF",
	"--bg-fill-emphasis": "#0090FFFF",
	"--bg-fill-transparent": "#0000000D",
	"--bg-fill-secondary": "#21201CFF",
	"--bg-fill-secondary-inverse": "#FFFFFFFF",
	"--text-default": "#21201CFF",
	"--text-secondary": "#63635EFF",
	"--text-muted": "#8D8D86FF",
	"--text-disabled": "#CFCECAFF",
	"--text-inverse": "#FFFFFFFF",
	"--text-info": "#1D3E56FF",
	"--text-success": "#203C25FF",
	"--text-warning": "#582D1DFF",
	"--text-critical": "#641723FF",
	"--text-emphasis": "#113264FF",
	"--text-brand": "#651249FF",
	"--text-link": "#113264FF",
	"--icon-default": "#21201CFF",
	"--icon-secondary": "#63635EFF",
	"--icon-disabled": "#E9E8E6FF",
	"--icon-inverse": "#F9F9F8FF",
	"--icon-info": "#00749EFF",
	"--icon-success": "#2A7E3BFF",
	"--icon-warning": "#CC4E00FF",
	"--icon-critical": "#CE2C31FF",
	"--icon-emphasis": "#0D74CEFF",
	"--icon-brand": "#C2298AFF",
	"--border-default": "#CFCECAFF",
	"--border-secondary": "#DAD9D6FF",
	"--border-tertiary": "#BCBBB5FF",
	"--border-disabled": "#DAD9D6FF",
	"--border-inverse": "#63635EFF",
	"--border-focus": "#0D74CEFF",
	"--border-brand": "#E7ACD0FF",
	"--border-info": "#8DCAE3FF",
	"--border-success": "#94CE9AFF",
	"--border-warning": "#F5AE73FF",
	"--border-critical": "#F4A9AAFF",
	"--border-emphasis": "#5EB1EFFF",
	"--chart-1": "#5EB1EFFF",
	"--chart-2": "#0090FFFF",
	"--chart-3": "#AA99ECFF",
	"--chart-4": "#6E56CFFF",
	"--chart-5": "#654DC4FF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#F9F9F8FF",
	"--foreground": "#21201CFF",
	"--card": "#F9F9F8FF",
	"--card-foreground": "#21201CFF",
	"--popover": "#F9F9F8FF",
	"--popover-foreground": "#21201CFF",
	"--primary": "#21201CFF",
	"--primary-foreground": "#FFFFFFFF",
	"--secondary": "#F1F0EFFF",
	"--secondary-foreground": "#21201CFF",
	"--muted": "#F1F0EFFF",
	"--muted-foreground": "#8D8D86FF",
	"--accent": "#F1F0EFFF",
	"--accent-foreground": "#21201CFF",
	"--destructive": "#E5484DFF",
	"--border": "#CFCECAFF",
	"--input": "#DAD9D6FF",
	"--ring": "#0D74CEFF",
	"--sidebar-background": "#F9F9F8FF",
	"--sidebar-foreground": "#21201CFF",
	"--sidebar-primary": "#21201CFF",
	"--sidebar-primary-foreground": "#FFFFFFFF",
	"--sidebar-accent": "#F1F0EFFF",
	"--sidebar-accent-foreground": "#21201CFF",
	"--sidebar-border": "#CFCECAFF",
	"--sidebar-ring": "#0D74CEFF",

	// ── Dimension tokens ──────────────────────────────────────────────────
	"--spacing": "0.25rem",
	"--border-width-base": "0.0625rem",
	"--radius": "0.5rem",
	"--font-size-base": "1rem",
	"--leading-base": "1.33",
	"--letter-spacing-base": "0.025em",
	"--opacity-hover": "0.8",
	"--opacity-active": "0.7",
	"--opacity-disabled": "0.5",
	"--shadow-offset-y": "1px",
	"--shadow-blur": "2px",
	"--shadow-spread": "1px",
	"--shadow-base-color": "rgba(0, 0, 0, 0.1)",
	"--container-sm": "624px",
	"--container-md": "768px",
	"--container-lg": "1056px",
	"--container-xl": "1296px",
	"--container-2xl": "1440px",
	"--dropdown-offset": "4",
	"--overlay-offset": "4",

	// ── Fonts: Inter for body/heading, Bricolage Grotesque for brand ─────
	"--font-sans": '"Inter Variable", sans-serif',
	"--font-heading": '"Inter Variable", sans-serif',
	"--font-brand": '"Bricolage Grotesque Variable", sans-serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	"--button-radius": "var(--radius-md)",
	"--button-padding-x": "calc(var(--spacing) * 4)",
	"--button-padding-y": "calc(var(--spacing) * 2)",
	"--card-radius": "var(--radius-lg)",
	"--card-padding": "calc(var(--spacing) * 6)",
	"--nav-height": "calc(var(--spacing) * 16)",
	"--section-padding-y": "calc(var(--spacing) * 24)",
	"--hero-padding-y": "calc(var(--spacing) * 40)",
	"--input-radius": "var(--radius-md)",
	"--input-height": "calc(var(--spacing) * 10)",
	"--badge-radius": "var(--radius-4xl)",

	// ── Phase 1b: Motion tokens ────────────────────────────────────────────
	"--transition-default": "200ms cubic-bezier(0.4, 0, 0.2, 1)",
	"--transition-fast": "100ms cubic-bezier(0.4, 0, 0.2, 1)",
	"--transition-slow": "300ms cubic-bezier(0, 0, 0.2, 1)",
	"--hover-transform": "none",
	"--hover-shadow": "var(--shadow-md)",
	"--active-scale": "0.98",

	// ── Phase 1c: Typography composition tokens ───────────────────────────
	"--heading-font-weight": "700",
	"--heading-letter-spacing": "var(--tracking-tight)",
	"--body-letter-spacing": "var(--tracking-normal)",
	"--hero-font-size": "var(--text-5xl)",
	"--hero-font-weight": "700",
	"--hero-letter-spacing": "var(--tracking-tight)",
	"--section-title-size": "var(--text-3xl)",
	"--section-title-font-weight": "700",
	"--section-title-letter-spacing": "var(--tracking-tight)",
	"--card-title-size": "var(--text-lg)",
	"--card-title-font-weight": "600",
	"--card-title-letter-spacing": "var(--tracking-normal)",
}

export const defaultPresetDark: Record<string, string> = {
	// Full dark-mode token set — mirrors tokens.css .dark values so that the
	// injected :root overrides from the light preset are fully superseded when
	// dark mode is toggled.

	// ── Semantic color tokens ─────────────────────────────────────────────
	"--bg-default": "#191918FF",
	"--bg-inverse": "#EEEEECFF",
	"--bg-muted": "#222221FF",
	"--bg-surface-default": "#191918FF",
	"--bg-surface-info": "#111A27FF",
	"--bg-surface-success": "#141A15FF",
	"--bg-surface-warning": "#1E160FFF",
	"--bg-surface-critical": "#201314FF",
	"--bg-surface-emphasis": "#111927FF",
	"--bg-surface-inverse": "#B5B3ADFF",
	"--bg-surface-transparent": "#0000000D",
	"--bg-surface-brand": "#21121DFF",
	"--bg-surface-hover": "#222221FF",
	"--bg-fill-default": "#191918FF",
	"--bg-fill-primary": "#EEEEECFF",
	"--bg-fill-brand": "#D6409FFF",
	"--bg-fill-info": "#7CE2FEFF",
	"--bg-fill-success": "#46A758FF",
	"--bg-fill-warning": "#F76B15FF",
	"--bg-fill-critical": "#E5484DFF",
	"--bg-fill-emphasis": "#0090FFFF",
	"--bg-fill-transparent": "#0000000D",
	"--bg-fill-secondary": "#EEEEECFF",
	"--bg-fill-secondary-inverse": "#000000FF",
	"--text-default": "#EEEEECFF",
	"--text-secondary": "#B5B3ADFF",
	"--text-muted": "#6F6D66FF",
	"--text-disabled": "#494844FF",
	"--text-inverse": "#000000FF",
	"--text-info": "#C2F3FFFF",
	"--text-success": "#C2F0C2FF",
	"--text-warning": "#FFE0C2FF",
	"--text-critical": "#FFD1D9FF",
	"--text-emphasis": "#C2E6FFFF",
	"--text-brand": "#FDD1EAFF",
	"--text-link": "#C2E6FFFF",
	"--icon-default": "#EEEEECFF",
	"--icon-secondary": "#B5B3ADFF",
	"--icon-disabled": "#31312EFF",
	"--icon-inverse": "#191918FF",
	"--icon-info": "#75C7F0FF",
	"--icon-success": "#71D083FF",
	"--icon-warning": "#FFA057FF",
	"--icon-critical": "#FF9592FF",
	"--icon-emphasis": "#70B8FFFF",
	"--icon-brand": "#FF8DCCFF",
	"--border-default": "#494844FF",
	"--border-secondary": "#494844FF",
	"--border-tertiary": "#62605BFF",
	"--border-disabled": "#494844FF",
	"--border-inverse": "#B5B3ADFF",
	"--border-focus": "#70B8FFFF",
	"--border-brand": "#833869FF",
	"--border-info": "#1F6692FF",
	"--border-success": "#366740FF",
	"--border-warning": "#7E451DFF",
	"--border-critical": "#8C333AFF",
	"--border-emphasis": "#2870BDFF",
	"--chart-1": "#2870BDFF",
	"--chart-2": "#0090FFFF",
	"--chart-3": "#6958ADFF",
	"--chart-4": "#6E56CFFF",
	"--chart-5": "#7D66D9FF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#191918FF",
	"--foreground": "#EEEEECFF",
	"--card": "#191918FF",
	"--card-foreground": "#EEEEECFF",
	"--popover": "#191918FF",
	"--popover-foreground": "#EEEEECFF",
	"--primary": "#EEEEECFF",
	"--primary-foreground": "#000000FF",
	"--secondary": "#222221FF",
	"--secondary-foreground": "#EEEEECFF",
	"--muted": "#222221FF",
	"--muted-foreground": "#6F6D66FF",
	"--accent": "#222221FF",
	"--accent-foreground": "#EEEEECFF",
	"--destructive": "#E5484DFF",
	"--border": "#494844FF",
	"--input": "#494844FF",
	"--ring": "#70B8FFFF",
	"--sidebar-background": "#191918FF",
	"--sidebar-foreground": "#EEEEECFF",
	"--sidebar-primary": "#EEEEECFF",
	"--sidebar-primary-foreground": "#000000FF",
	"--sidebar-accent": "#222221FF",
	"--sidebar-accent-foreground": "#EEEEECFF",
	"--sidebar-border": "#494844FF",
	"--sidebar-ring": "#70B8FFFF",

	// ── Fonts carry over ──────────────────────────────────────────────────
	"--font-sans": '"Inter Variable", sans-serif',
	"--font-heading": '"Inter Variable", sans-serif',
	"--font-brand": '"Bricolage Grotesque Variable", sans-serif',
}
