/**
 * Leitware — Monospaced industrial aesthetic.
 * Built on IBM Plex Mono throughout for a cohesive terminal-like feel.
 * Zero border-radius, no shadows, generous spacing and slightly larger type.
 * Light mode: orange brand. Dark mode: lime green brand.
 */
export const leitware: Record<string, string> = {
	"--bg-default": "#F8F8F8FF",
	"--bg-inverse": "#0A0A0AFF",
	"--bg-muted": "#EFEFEFFF",
	"--bg-surface-default": "#F8F8F8FF",
	"--bg-surface-info": "#E8F0F8FF",
	"--bg-surface-success": "#E8F4E8FF",
	"--bg-surface-warning": "#FBF4E0FF",
	"--bg-surface-critical": "#FAE8E8FF",
	"--bg-surface-emphasis": "#E8E8F4FF",
	"--bg-surface-inverse": "#606060FF",
	"--bg-surface-transparent": "#00000010",
	"--bg-surface-brand": "#FFF0E0FF",
	"--bg-surface-hover": "#EFEFEFFF",
	"--bg-fill-default": "#F8F8F8FF",
	"--bg-fill-primary": "#0A0A0AFF",
	"--bg-fill-brand": "#E87000FF",
	"--bg-fill-info": "#3366CCFF",
	"--bg-fill-success": "#007700FF",
	"--bg-fill-warning": "#CC6600FF",
	"--bg-fill-critical": "#CC0000FF",
	"--bg-fill-emphasis": "#0A0A0AFF",
	"--bg-fill-transparent": "#00000010",
	"--bg-fill-secondary": "#0A0A0AFF",
	"--bg-fill-secondary-inverse": "#F8F8F8FF",
	"--text-default": "#0A0A0AFF",
	"--text-secondary": "#2E2E2EFF",
	"--text-muted": "#5A5A5AFF",
	"--text-disabled": "#AAAAAAFF",
	"--text-inverse": "#F8F8F8FF",
	"--text-info": "#001E5EFF",
	"--text-success": "#003A00FF",
	"--text-warning": "#5E2E00FF",
	"--text-critical": "#5E0000FF",
	"--text-emphasis": "#001E5EFF",
	"--text-brand": "#A04D00FF",
	"--text-link": "#E87000FF",
	"--icon-default": "#0A0A0AFF",
	"--icon-secondary": "#2E2E2EFF",
	"--icon-disabled": "#CCCCCCFF",
	"--icon-inverse": "#F8F8F8FF",
	"--icon-info": "#3366CCFF",
	"--icon-success": "#007700FF",
	"--icon-warning": "#AA5500FF",
	"--icon-critical": "#AA0000FF",
	"--icon-emphasis": "#3366CCFF",
	"--icon-brand": "#E87000FF",
	"--border-default": "#0A0A0AFF",
	"--border-secondary": "#2E2E2EFF",
	"--border-tertiary": "#5A5A5AFF",
	"--border-disabled": "#AAAAAAFF",
	"--border-inverse": "#F8F8F8FF",
	"--border-focus": "#E8700099",
	"--border-brand": "#E87000FF",
	"--ring": "#E8700099",
	"--border-info": "#3366CCFF",
	"--border-success": "#007700FF",
	"--border-warning": "#AA5500FF",
	"--border-critical": "#AA0000FF",
	"--border-emphasis": "#3366CCFF",
	"--chart-1": "#0A0A0AFF",
	"--chart-2": "#E87000FF",
	"--chart-3": "#5A5A5AFF",
	"--chart-4": "#007700FF",
	"--chart-5": "#3366CCFF",
	"--spacing": "0.375rem",
	"--border-width-base": "0.125rem",
	"--radius": "0rem",
	"--font-size-base": "1.15rem",
	"--leading-base": "1.3",
	"--letter-spacing-base": "0.04em",
	"--opacity-hover": "1",
	"--opacity-active": "1",
	"--opacity-disabled": "0.5",
	"--shadow-offset-y": "0px",
	"--shadow-blur": "0px",
	"--shadow-spread": "0px",
	"--container-sm": "672px",
	"--container-md": "816px",
	"--container-lg": "1104px",
	"--container-xl": "1392px",
	"--container-2xl": "1536px",
	"--dropdown-offset": "0",
	"--overlay-offset": "0",
	"--shadow-base-color": "rgba(0, 0, 0, 1)",
	"--font-sans": "\"IBM Plex Mono\", sans-serif",
	"--font-heading": "\"IBM Plex Mono\", sans-serif",
	"--font-brand": "\"IBM Plex Mono\", sans-serif",
}

export const leitwareDark: Record<string, string> = {
	"--bg-default": "#0A0A0AFF",
	"--bg-inverse": "#F8F8F8FF",
	"--bg-muted": "#141414FF",
	"--bg-surface-default": "#0A0A0AFF",
	"--bg-surface-info": "#0A1828FF",
	"--bg-surface-success": "#0A180AFF",
	"--bg-surface-warning": "#1E1406FF",
	"--bg-surface-critical": "#1E0A0AFF",
	"--bg-surface-emphasis": "#0A0A1EFF",
	"--bg-surface-inverse": "#606060FF",
	"--bg-surface-transparent": "#FFFFFF10",
	"--bg-surface-brand": "#0A1E08FF",
	"--bg-surface-hover": "#1A1A1AFF",
	"--bg-fill-default": "#0A0A0AFF",
	"--bg-fill-primary": "#F0F0F0FF",
	"--bg-fill-brand": "#88CC00FF",
	"--bg-fill-info": "#3366CCFF",
	"--bg-fill-success": "#009900FF",
	"--bg-fill-warning": "#DD7700FF",
	"--bg-fill-critical": "#DD2222FF",
	"--bg-fill-emphasis": "#F0F0F0FF",
	"--bg-fill-transparent": "#FFFFFF10",
	"--bg-fill-secondary": "#F0F0F0FF",
	"--bg-fill-secondary-inverse": "#0A0A0AFF",
	"--text-default": "#F0F0F0FF",
	"--text-secondary": "#C0C0C0FF",
	"--text-muted": "#888888FF",
	"--text-disabled": "#444444FF",
	"--text-inverse": "#0A0A0AFF",
	"--text-info": "#99BBFFFF",
	"--text-success": "#77DD77FF",
	"--text-warning": "#FFBB44FF",
	"--text-critical": "#FF7777FF",
	"--text-emphasis": "#CCCCFFFF",
	"--text-brand": "#AADD44FF",
	"--text-link": "#88CC00FF",
	"--icon-default": "#F0F0F0FF",
	"--icon-secondary": "#C0C0C0FF",
	"--icon-disabled": "#383838FF",
	"--icon-inverse": "#0A0A0AFF",
	"--icon-info": "#5588EEFF",
	"--icon-success": "#44BB44FF",
	"--icon-warning": "#CC8800FF",
	"--icon-critical": "#DD3333FF",
	"--icon-emphasis": "#5588EEFF",
	"--icon-brand": "#88CC00FF",
	"--border-default": "#F0F0F0FF",
	"--border-secondary": "#C0C0C0FF",
	"--border-tertiary": "#888888FF",
	"--border-disabled": "#444444FF",
	"--border-inverse": "#0A0A0AFF",
	"--border-focus": "#88CC0099",
	"--border-brand": "#88CC00FF",
	"--ring": "#88CC0099",
	"--border-info": "#3366CCFF",
	"--border-success": "#009900FF",
	"--border-warning": "#CC6600FF",
	"--border-critical": "#CC1111FF",
	"--border-emphasis": "#3366CCFF",
	"--chart-1": "#F0F0F0FF",
	"--chart-2": "#88CC00FF",
	"--chart-3": "#888888FF",
	"--chart-4": "#44BB44FF",
	"--chart-5": "#5588EEFF",
	"--spacing": "0.375rem",
	"--border-width-base": "0.125rem",
	"--radius": "0rem",
	"--font-size-base": "1.15rem",
	"--leading-base": "1.3",
	"--letter-spacing-base": "0.04em",
	"--opacity-hover": "1",
	"--opacity-active": "1",
	"--opacity-disabled": "0.5",
	"--shadow-offset-y": "0px",
	"--shadow-blur": "0px",
	"--shadow-spread": "0px",
	"--container-sm": "672px",
	"--container-md": "816px",
	"--container-lg": "1104px",
	"--container-xl": "1392px",
	"--container-2xl": "1536px",
	"--dropdown-offset": "0",
	"--overlay-offset": "0",
	"--shadow-base-color": "rgba(0, 0, 0, 1)",
	"--font-sans": "\"IBM Plex Mono\", sans-serif",
	"--font-heading": "\"IBM Plex Mono\", sans-serif",
	"--font-brand": "\"IBM Plex Mono\", sans-serif",
}
