/**
 * Midnight — Dark-first premium theme.
 * References: Raycast, Warp terminal, Arc browser dark mode, Linear dark.
 * Deep blue-black backgrounds with an electric indigo accent — not GitHub's
 * navy-green, not pure black. Premium feels expensive because it uses depth.
 *
 * Fonts:
 *   Heading — Space Grotesk Variable: slightly mechanical, purposeful,
 *             feels at home in a premium dark UI. Pairs beautifully with
 *             Inter's neutrality at body sizes.
 *   Body    — Inter Variable: the standard bearer for legible UI text.
 *             At small sizes on dark backgrounds, nothing else comes close.
 *
 * Character: deep blue-black backgrounds (Raycast-style #131320), electric
 * indigo accent (#6E7AFF), glow-style shadows (indigo-tinted, diffuse),
 * smooth transitions, subtle translateY hover.
 */
export const midnight: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	"--bg-default": "#131320FF",
	"--bg-inverse": "#E8E8F2FF",
	"--bg-muted": "#1C1C2EFF",
	"--bg-surface-default": "#1C1C2EFF",
	"--bg-surface-info": "#0F1830FF",
	"--bg-surface-success": "#0F1C18FF",
	"--bg-surface-warning": "#1A150AFF",
	"--bg-surface-critical": "#1E0F12FF",
	"--bg-surface-emphasis": "#141430FF",
	"--bg-surface-inverse": "#8888A8FF",
	"--bg-surface-transparent": "#FFFFFF0A",
	"--bg-surface-brand": "#1A102EFF",
	"--bg-surface-hover": "#25253CFF",
	"--bg-fill-default": "#1C1C2EFF",
	"--bg-fill-primary": "#6E7AFFFF",
	"--bg-fill-brand": "#7C3AEDFF",
	"--bg-fill-info": "#38BDF8FF",
	"--bg-fill-success": "#22C55EFF",
	"--bg-fill-warning": "#F59E0BFF",
	"--bg-fill-critical": "#EF4444FF",
	"--bg-fill-emphasis": "#6E7AFFFF",
	"--bg-fill-transparent": "#FFFFFF0A",
	"--bg-fill-secondary": "#2A2A42FF",
	"--bg-fill-secondary-inverse": "#131320FF",
	"--text-default": "#E8E8F2FF",
	"--text-secondary": "#9898B8FF",
	"--text-muted": "#585878FF",
	"--text-disabled": "#303050FF",
	"--text-inverse": "#131320FF",
	"--text-info": "#7AB8FFFF",
	"--text-success": "#56D364FF",
	"--text-warning": "#E3B341FF",
	"--text-critical": "#F85149FF",
	"--text-emphasis": "#A8B8FFFF",
	"--text-brand": "#C8A8FFFF",
	"--text-link": "#9AAAFFFF",
	"--icon-default": "#E8E8F2FF",
	"--icon-secondary": "#9898B8FF",
	"--icon-disabled": "#25253CFF",
	"--icon-inverse": "#131320FF",
	"--icon-info": "#38BDF8FF",
	"--icon-success": "#22C55EFF",
	"--icon-warning": "#F59E0BFF",
	"--icon-critical": "#EF4444FF",
	"--icon-emphasis": "#6E7AFFFF",
	"--icon-brand": "#9D6FE8FF",
	"--border-default": "#2A2A42FF",
	"--border-secondary": "#333358FF",
	"--border-tertiary": "#3D3D5AFF",
	"--border-disabled": "#2A2A42FF",
	"--border-inverse": "#9898B8FF",
	"--border-focus": "#6E7AFFFF",
	"--border-brand": "#6E3EBDFF",
	"--border-info": "#1158A7FF",
	"--border-success": "#196C2EFF",
	"--border-warning": "#9E6A03FF",
	"--border-critical": "#6E0000FF",
	"--border-emphasis": "#3B52BCFF",
	"--chart-1": "#6E7AFFFF",
	"--chart-2": "#38BDF8FF",
	"--chart-3": "#22C55EFF",
	"--chart-4": "#F59E0BFF",
	"--chart-5": "#C8A8FFFF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#131320FF",
	"--foreground": "#E8E8F2FF",
	"--card": "#1C1C2EFF",
	"--card-foreground": "#E8E8F2FF",
	"--popover": "#1C1C2EFF",
	"--popover-foreground": "#E8E8F2FF",
	"--primary": "#6E7AFFFF",
	"--primary-foreground": "#FFFFFFFF",
	"--secondary": "#25253CFF",
	"--secondary-foreground": "#E8E8F2FF",
	"--muted": "#25253CFF",
	"--muted-foreground": "#585878FF",
	"--accent": "#25253CFF",
	"--accent-foreground": "#E8E8F2FF",
	"--destructive": "#EF4444FF",
	"--border": "#2A2A42FF",
	"--input": "#2A2A42FF",
	"--ring": "#6E7AFFFF",
	"--sidebar-background": "#0F0F20FF",
	"--sidebar-foreground": "#E8E8F2FF",
	"--sidebar-primary": "#6E7AFFFF",
	"--sidebar-primary-foreground": "#FFFFFFFF",
	"--sidebar-accent": "#25253CFF",
	"--sidebar-accent-foreground": "#E8E8F2FF",
	"--sidebar-border": "#2A2A42FF",
	"--sidebar-ring": "#6E7AFFFF",

	// ── Dimension tokens ──────────────────────────────────────────────────
	"--spacing": "0.25rem",
	"--border-width-base": "0.0625rem",
	"--radius": "0.625rem",
	"--font-size-base": "0.9375rem",
	"--leading-base": "1.5",
	"--letter-spacing-base": "0.02em",
	"--opacity-hover": "0.85",
	"--opacity-active": "0.7",
	"--opacity-disabled": "0.3",
	// Indigo glow shadow — diffuse, coloured, low opacity
	"--shadow-offset-y": "4px",
	"--shadow-blur": "24px",
	"--shadow-spread": "0px",
	"--shadow-base-color": "rgba(110, 122, 255, 0.2)",
	"--container-sm": "640px",
	"--container-md": "768px",
	"--container-lg": "1024px",
	"--container-xl": "1280px",
	"--container-2xl": "1400px",
	"--dropdown-offset": "8",
	"--overlay-offset": "8",

	// ── Fonts: Space Grotesk heading × Inter body ─────────────────────────
	"--font-sans": '"Inter Variable", sans-serif',
	"--font-heading": '"Space Grotesk Variable", sans-serif',
	"--font-brand": '"Space Grotesk Variable", sans-serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	"--button-radius": "var(--radius-md)",
	"--button-padding-x": "calc(var(--spacing) * 4)",
	"--button-padding-y": "calc(var(--spacing) * 2.5)",
	"--card-radius": "var(--radius-lg)",
	"--card-padding": "calc(var(--spacing) * 6)",
	"--nav-height": "calc(var(--spacing) * 16)",
	"--section-padding-y": "calc(var(--spacing) * 24)",
	"--hero-padding-y": "calc(var(--spacing) * 40)",
	"--input-radius": "var(--radius-md)",
	"--input-height": "calc(var(--spacing) * 10)",
	"--badge-radius": "var(--radius-2xl)",

	// ── Phase 1b: Motion — smooth, slightly slower than default ───────────
	"--transition-default": "220ms cubic-bezier(0.4, 0, 0.2, 1)",
	"--transition-fast": "120ms cubic-bezier(0.4, 0, 0.2, 1)",
	"--transition-slow": "360ms cubic-bezier(0, 0, 0.2, 1)",
	"--hover-transform": "translateY(-1px)",
	"--hover-shadow": "var(--shadow-lg)",
	"--active-scale": "0.97",

	// ── Phase 1c: Typography — clear hierarchy on dark backgrounds ────────
	"--heading-font-weight": "600",
	"--heading-letter-spacing": "var(--tracking-tight)",
	"--body-letter-spacing": "var(--tracking-normal)",
	"--hero-font-size": "var(--text-5xl)",
	"--hero-font-weight": "600",
	"--hero-letter-spacing": "var(--tracking-tight)",
	"--section-title-size": "var(--text-3xl)",
	"--section-title-font-weight": "600",
	"--section-title-letter-spacing": "var(--tracking-tight)",
	"--card-title-size": "var(--text-lg)",
	"--card-title-font-weight": "500",
	"--card-title-letter-spacing": "var(--tracking-normal)",
}

export const midnightDark: Record<string, string> = {
	// Midnight is dark-first. In dark-toggle mode, deepen the already-dark
	// backgrounds slightly and carry over all other tokens unchanged.

	// ── Background tokens: deepen for ultra-dark mode ─────────────────────
	"--bg-default": "#0B0B18FF",
	"--bg-muted": "#141424FF",
	"--bg-surface-default": "#141424FF",
	"--bg-surface-info": "#0A1228FF",
	"--bg-surface-success": "#0A1412FF",
	"--bg-surface-warning": "#14100AFF",
	"--bg-surface-critical": "#180A0EFF",
	"--bg-surface-emphasis": "#0E0E28FF",
	"--bg-surface-hover": "#1E1E34FF",
	"--bg-fill-default": "#141424FF",
	"--bg-fill-secondary": "#222238FF",

	// ── Text, icon, border, chart carry over from midnight ────────────────
	"--bg-inverse": "#E8E8F2FF",
	"--bg-surface-inverse": "#8888A8FF",
	"--bg-surface-transparent": "#FFFFFF0A",
	"--bg-surface-brand": "#140C28FF",
	"--bg-fill-primary": "#6E7AFFFF",
	"--bg-fill-brand": "#7C3AEDFF",
	"--bg-fill-info": "#38BDF8FF",
	"--bg-fill-success": "#22C55EFF",
	"--bg-fill-warning": "#F59E0BFF",
	"--bg-fill-critical": "#EF4444FF",
	"--bg-fill-emphasis": "#6E7AFFFF",
	"--bg-fill-transparent": "#FFFFFF0A",
	"--bg-fill-secondary-inverse": "#0B0B18FF",
	"--text-default": "#E8E8F2FF",
	"--text-secondary": "#9898B8FF",
	"--text-muted": "#585878FF",
	"--text-disabled": "#282845FF",
	"--text-inverse": "#0B0B18FF",
	"--text-info": "#7AB8FFFF",
	"--text-success": "#56D364FF",
	"--text-warning": "#E3B341FF",
	"--text-critical": "#F85149FF",
	"--text-emphasis": "#A8B8FFFF",
	"--text-brand": "#C8A8FFFF",
	"--text-link": "#9AAAFFFF",
	"--icon-default": "#E8E8F2FF",
	"--icon-secondary": "#9898B8FF",
	"--icon-disabled": "#1E1E34FF",
	"--icon-inverse": "#0B0B18FF",
	"--icon-info": "#38BDF8FF",
	"--icon-success": "#22C55EFF",
	"--icon-warning": "#F59E0BFF",
	"--icon-critical": "#EF4444FF",
	"--icon-emphasis": "#6E7AFFFF",
	"--icon-brand": "#9D6FE8FF",
	"--border-default": "#222238FF",
	"--border-secondary": "#2A2A48FF",
	"--border-tertiary": "#33334EFF",
	"--border-disabled": "#222238FF",
	"--border-inverse": "#9898B8FF",
	"--border-focus": "#6E7AFFFF",
	"--border-brand": "#6E3EBDFF",
	"--border-info": "#1158A7FF",
	"--border-success": "#196C2EFF",
	"--border-warning": "#9E6A03FF",
	"--border-critical": "#6E0000FF",
	"--border-emphasis": "#3B52BCFF",
	"--chart-1": "#6E7AFFFF",
	"--chart-2": "#38BDF8FF",
	"--chart-3": "#22C55EFF",
	"--chart-4": "#F59E0BFF",
	"--chart-5": "#C8A8FFFF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#0B0B18FF",
	"--foreground": "#E8E8F2FF",
	"--card": "#141424FF",
	"--card-foreground": "#E8E8F2FF",
	"--popover": "#141424FF",
	"--popover-foreground": "#E8E8F2FF",
	"--primary": "#6E7AFFFF",
	"--primary-foreground": "#FFFFFFFF",
	"--secondary": "#1E1E34FF",
	"--secondary-foreground": "#E8E8F2FF",
	"--muted": "#1E1E34FF",
	"--muted-foreground": "#585878FF",
	"--accent": "#1E1E34FF",
	"--accent-foreground": "#E8E8F2FF",
	"--destructive": "#EF4444FF",
	"--border": "#222238FF",
	"--input": "#222238FF",
	"--ring": "#6E7AFFFF",
	"--sidebar-background": "#07071AFF",
	"--sidebar-foreground": "#E8E8F2FF",
	"--sidebar-primary": "#6E7AFFFF",
	"--sidebar-primary-foreground": "#FFFFFFFF",
	"--sidebar-accent": "#1E1E34FF",
	"--sidebar-accent-foreground": "#E8E8F2FF",
	"--sidebar-border": "#222238FF",
	"--sidebar-ring": "#6E7AFFFF",

	// ── Fonts carry over ──────────────────────────────────────────────────
	"--font-sans": '"Inter Variable", sans-serif',
	"--font-heading": '"Space Grotesk Variable", sans-serif',
	"--font-brand": '"Space Grotesk Variable", sans-serif',
}
