/**
 * Nature — Organic, earthy, grounded. Feels like a forest cabin with
 * great wifi. Warm greens, rich browns, natural tones.
 *
 * Fonts:
 *   Heading — Playfair Display Variable: elegant serif with organic
 *             character. Classic, warm, slightly editorial.
 *   Body    — Lora Variable: a well-balanced serif that pairs beautifully
 *             with Playfair and keeps long text comfortable to read.
 *
 * Character: warm green-brown palette, medium radius, earthy shadows,
 * understated transitions, serif typography for an organic feel.
 */
export const nature: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	"--bg-default": "#F6F4EFFF",
	"--bg-inverse": "#1A2418FF",
	"--bg-muted": "#EDE8DCFF",
	"--bg-surface-default": "#F6F4EFFF",
	"--bg-surface-info": "#E8F0F2FF",
	"--bg-surface-success": "#E8F2E8FF",
	"--bg-surface-warning": "#F8F0E0FF",
	"--bg-surface-critical": "#F8EBEBFF",
	"--bg-surface-emphasis": "#E8EEE8FF",
	"--bg-surface-inverse": "#5A7050FF",
	"--bg-surface-transparent": "#0000000A",
	"--bg-surface-brand": "#EEF2E8FF",
	"--bg-surface-hover": "#E8E4D8FF",
	"--bg-fill-default": "#F6F4EFFF",
	"--bg-fill-primary": "#3A6838FF",
	"--bg-fill-brand": "#4A7848FF",
	"--bg-fill-info": "#4888A0FF",
	"--bg-fill-success": "#3A8840FF",
	"--bg-fill-warning": "#C08828FF",
	"--bg-fill-critical": "#B84040FF",
	"--bg-fill-emphasis": "#3A6838FF",
	"--bg-fill-transparent": "#0000000A",
	"--bg-fill-secondary": "#2A3828FF",
	"--bg-fill-secondary-inverse": "#F6F4EFFF",
	"--text-default": "#1A2418FF",
	"--text-secondary": "#4A5848FF",
	"--text-muted": "#7A8878FF",
	"--text-disabled": "#B8C0B8FF",
	"--text-inverse": "#F6F4EFFF",
	"--text-info": "#1A4050FF",
	"--text-success": "#1A4020FF",
	"--text-warning": "#5A4010FF",
	"--text-critical": "#5A1A1AFF",
	"--text-emphasis": "#1A3818FF",
	"--text-brand": "#2A5828FF",
	"--text-link": "#3A6838FF",
	"--icon-default": "#1A2418FF",
	"--icon-secondary": "#4A5848FF",
	"--icon-disabled": "#C8D0C8FF",
	"--icon-inverse": "#F6F4EFFF",
	"--icon-info": "#3A7890FF",
	"--icon-success": "#308038FF",
	"--icon-warning": "#A87820FF",
	"--icon-critical": "#A83838FF",
	"--icon-emphasis": "#306030FF",
	"--icon-brand": "#4A7848FF",
	"--border-default": "#C8C0B0FF",
	"--border-secondary": "#D8D0C0FF",
	"--border-tertiary": "#B0A898FF",
	"--border-disabled": "#D8D0C0FF",
	"--border-inverse": "#5A7050FF",
	"--border-focus": "#3A6838FF",
	"--border-brand": "#90B888FF",
	"--border-info": "#90B8C8FF",
	"--border-success": "#90C898FF",
	"--border-warning": "#D8C090FF",
	"--border-critical": "#D8A0A0FF",
	"--border-emphasis": "#78A878FF",
	"--chart-1": "#4A7848FF",
	"--chart-2": "#4888A0FF",
	"--chart-3": "#C08828FF",
	"--chart-4": "#A85838FF",
	"--chart-5": "#7868A0FF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#F6F4EFFF",
	"--foreground": "#1A2418FF",
	"--card": "#F0EDE4FF",
	"--card-foreground": "#1A2418FF",
	"--popover": "#F6F4EFFF",
	"--popover-foreground": "#1A2418FF",
	"--primary": "#3A6838FF",
	"--primary-foreground": "#F6F4EFFF",
	"--secondary": "#E8E4D8FF",
	"--secondary-foreground": "#1A2418FF",
	"--muted": "#EDE8DCFF",
	"--muted-foreground": "#7A8878FF",
	"--accent": "#E8E4D8FF",
	"--accent-foreground": "#1A2418FF",
	"--destructive": "#B84040FF",
	"--border": "#C8C0B0FF",
	"--input": "#D8D0C0FF",
	"--ring": "#3A6838FF",
	"--sidebar-background": "#F0EDE4FF",
	"--sidebar-foreground": "#1A2418FF",
	"--sidebar-primary": "#3A6838FF",
	"--sidebar-primary-foreground": "#F6F4EFFF",
	"--sidebar-accent": "#E8E4D8FF",
	"--sidebar-accent-foreground": "#1A2418FF",
	"--sidebar-border": "#C8C0B0FF",
	"--sidebar-ring": "#3A6838FF",

	// ── Dimension tokens ──────────────────────────────────────────────────
	"--spacing": "0.25rem",
	"--border-width-base": "0.0625rem",
	"--radius": "0.375rem",
	"--font-size-base": "1rem",
	"--leading-base": "1.6",
	"--letter-spacing-base": "0.01em",
	"--opacity-hover": "0.9",
	"--opacity-active": "0.8",
	"--opacity-disabled": "0.45",
	"--shadow-offset-y": "2px",
	"--shadow-blur": "8px",
	"--shadow-spread": "0px",
	"--shadow-base-color": "rgba(40, 60, 30, 0.1)",
	"--container-sm": "576px",
	"--container-md": "768px",
	"--container-lg": "1056px",
	"--container-xl": "1248px",
	"--container-2xl": "1440px",
	"--dropdown-offset": "6",
	"--overlay-offset": "6",

	// ── Fonts: Playfair Display heading × Lora body ──────────────────────
	"--font-sans": '"Lora Variable", "Georgia", serif',
	"--font-heading": '"Playfair Display Variable", "Georgia", serif',
	"--font-brand": '"Playfair Display Variable", "Georgia", serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	"--button-radius": "var(--radius)",
	"--button-padding-x": "calc(var(--spacing) * 5)",
	"--button-padding-y": "calc(var(--spacing) * 2.5)",
	"--card-radius": "var(--radius-lg)",
	"--card-padding": "calc(var(--spacing) * 6)",
	"--nav-height": "calc(var(--spacing) * 16)",
	"--section-padding-y": "calc(var(--spacing) * 24)",
	"--hero-padding-y": "calc(var(--spacing) * 36)",
	"--input-radius": "var(--radius)",
	"--input-height": "calc(var(--spacing) * 11)",
	"--badge-radius": "var(--radius-4xl)",

	// ── Phase 1b: Motion — gentle, organic ───────────────────────────────
	"--transition-default": "200ms cubic-bezier(0.4, 0, 0.2, 1)",
	"--transition-fast": "120ms cubic-bezier(0.4, 0, 0.2, 1)",
	"--transition-slow": "300ms cubic-bezier(0, 0, 0.2, 1)",
	"--hover-transform": "translateY(-1px)",
	"--hover-shadow": "var(--shadow-md)",
	"--active-scale": "0.98",

	// ── Phase 1c: Typography — warm serif ────────────────────────────────
	"--heading-font-weight": "700",
	"--heading-letter-spacing": "var(--tracking-tight)",
	"--body-letter-spacing": "var(--tracking-normal)",
	"--hero-font-size": "var(--text-5xl)",
	"--hero-font-weight": "700",
	"--hero-letter-spacing": "var(--tracking-tight)",
	"--section-title-size": "var(--text-3xl)",
	"--section-title-font-weight": "700",
	"--section-title-letter-spacing": "var(--tracking-tight)",
	"--card-title-size": "var(--text-lg)",
	"--card-title-font-weight": "600",
	"--card-title-letter-spacing": "var(--tracking-normal)",
}

export const natureDark: Record<string, string> = {
	// ── Dark: deep forest at night ───────────────────────────────────────
	"--bg-default": "#0E1410FF",
	"--bg-inverse": "#E8E4D8FF",
	"--bg-muted": "#161E18FF",
	"--bg-surface-default": "#161E18FF",
	"--bg-surface-info": "#0E1820FF",
	"--bg-surface-success": "#0E1C10FF",
	"--bg-surface-warning": "#1C1808FF",
	"--bg-surface-critical": "#1E1010FF",
	"--bg-surface-emphasis": "#101C10FF",
	"--bg-surface-inverse": "#708068FF",
	"--bg-surface-transparent": "#FFFFFF08",
	"--bg-surface-brand": "#142018FF",
	"--bg-surface-hover": "#1E2820FF",
	"--bg-fill-default": "#161E18FF",
	"--bg-fill-primary": "#58A058FF",
	"--bg-fill-brand": "#609860FF",
	"--bg-fill-info": "#5898B0FF",
	"--bg-fill-success": "#48A850FF",
	"--bg-fill-warning": "#D09830FF",
	"--bg-fill-critical": "#C85050FF",
	"--bg-fill-emphasis": "#58A058FF",
	"--bg-fill-transparent": "#FFFFFF08",
	"--bg-fill-secondary": "#1E2820FF",
	"--bg-fill-secondary-inverse": "#0E1410FF",
	"--text-default": "#D8D4C4FF",
	"--text-secondary": "#98A090FF",
	"--text-muted": "#586858FF",
	"--text-disabled": "#303830FF",
	"--text-inverse": "#0E1410FF",
	"--text-info": "#90C8D8FF",
	"--text-success": "#78D888FF",
	"--text-warning": "#E0C060FF",
	"--text-critical": "#E89090FF",
	"--text-emphasis": "#90D090FF",
	"--text-brand": "#78C878FF",
	"--text-link": "#58A058FF",
	"--icon-default": "#D8D4C4FF",
	"--icon-secondary": "#98A090FF",
	"--icon-disabled": "#283028FF",
	"--icon-inverse": "#161E18FF",
	"--icon-info": "#6898B0FF",
	"--icon-success": "#58B860FF",
	"--icon-warning": "#C09030FF",
	"--icon-critical": "#C05050FF",
	"--icon-emphasis": "#58A058FF",
	"--icon-brand": "#609860FF",
	"--border-default": "#283028FF",
	"--border-secondary": "#384038FF",
	"--border-tertiary": "#485048FF",
	"--border-disabled": "#283028FF",
	"--border-inverse": "#98A090FF",
	"--border-focus": "#58A058FF",
	"--border-brand": "#406840FF",
	"--border-info": "#184050FF",
	"--border-success": "#184830FF",
	"--border-warning": "#483818FF",
	"--border-critical": "#482828FF",
	"--border-emphasis": "#386038FF",
	"--chart-1": "#58A058FF",
	"--chart-2": "#6898B0FF",
	"--chart-3": "#D09830FF",
	"--chart-4": "#C06848FF",
	"--chart-5": "#8878A8FF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#0E1410FF",
	"--foreground": "#D8D4C4FF",
	"--card": "#161E18FF",
	"--card-foreground": "#D8D4C4FF",
	"--popover": "#161E18FF",
	"--popover-foreground": "#D8D4C4FF",
	"--primary": "#58A058FF",
	"--primary-foreground": "#0E1410FF",
	"--secondary": "#1E2820FF",
	"--secondary-foreground": "#D8D4C4FF",
	"--muted": "#1E2820FF",
	"--muted-foreground": "#586858FF",
	"--accent": "#283028FF",
	"--accent-foreground": "#D8D4C4FF",
	"--destructive": "#C85050FF",
	"--border": "#283028FF",
	"--input": "#283028FF",
	"--ring": "#58A058FF",
	"--sidebar-background": "#0E1410FF",
	"--sidebar-foreground": "#D8D4C4FF",
	"--sidebar-primary": "#58A058FF",
	"--sidebar-primary-foreground": "#0E1410FF",
	"--sidebar-accent": "#1E2820FF",
	"--sidebar-accent-foreground": "#D8D4C4FF",
	"--sidebar-border": "#283028FF",
	"--sidebar-ring": "#58A058FF",

	// ── Fonts carry over ──────────────────────────────────────────────────
	"--font-sans": '"Lora Variable", "Georgia", serif',
	"--font-heading": '"Playfair Display Variable", "Georgia", serif',
	"--font-brand": '"Playfair Display Variable", "Georgia", serif',
}
