/**
 * Swiss — International Typographic Style.
 * References: Müller-Brockmann grid systems, Armin Hofmann's Basel School,
 * Max Bill's geometric functionalism. The original design system.
 *
 * Fonts: Helvetica Neue / Arial system stack. The Swiss style is defined
 * by Helvetica — no substitution. No import needed: these are system fonts.
 * Fallback to Arial ensures cross-platform consistency.
 *
 * Character: absolute grid discipline. Zero radius. Zero shadow.
 * Black ink + one accent (red — the Swiss colour). Compressed containers.
 * High tracking on body text. Aggressive heading weight.
 * Opacity-based hover states, not colour changes.
 */
export const swiss: Record<string, string> = {
	// ── Semantic color tokens ─────────────────────────────────────────────
	"--bg-default": "#FFFFFFFF",
	"--bg-inverse": "#111111FF",
	"--bg-muted": "#F5F5F5FF",
	"--bg-surface-default": "#FFFFFFFF",
	"--bg-surface-info": "#F0F4F8FF",
	"--bg-surface-success": "#F0F8F0FF",
	"--bg-surface-warning": "#FBF7F0FF",
	"--bg-surface-critical": "#FBF0F0FF",
	"--bg-surface-emphasis": "#F0F0F5FF",
	"--bg-surface-inverse": "#555555FF",
	"--bg-surface-transparent": "#00000008",
	"--bg-surface-brand": "#FFF0F0FF",
	"--bg-surface-hover": "#EEEEEEFF",
	"--bg-fill-default": "#FFFFFFFF",
	"--bg-fill-primary": "#111111FF",
	"--bg-fill-brand": "#E53B3BFF",
	"--bg-fill-info": "#4A80C4FF",
	"--bg-fill-success": "#2E8C4AFF",
	"--bg-fill-warning": "#CC7700FF",
	"--bg-fill-critical": "#CC2222FF",
	"--bg-fill-emphasis": "#111111FF",
	"--bg-fill-transparent": "#00000008",
	"--bg-fill-secondary": "#333333FF",
	"--bg-fill-secondary-inverse": "#FFFFFFFF",
	"--text-default": "#111111FF",
	"--text-secondary": "#444444FF",
	"--text-muted": "#777777FF",
	"--text-disabled": "#BBBBBBFF",
	"--text-inverse": "#FFFFFFFF",
	"--text-info": "#1A3A5CFF",
	"--text-success": "#1A4828FF",
	"--text-warning": "#6A3800FF",
	"--text-critical": "#881818FF",
	"--text-emphasis": "#111111FF",
	"--text-brand": "#BB1818FF",
	"--text-link": "#E53B3BFF",
	"--icon-default": "#111111FF",
	"--icon-secondary": "#444444FF",
	"--icon-disabled": "#DDDDDDFF",
	"--icon-inverse": "#FFFFFFFF",
	"--icon-info": "#4A80C4FF",
	"--icon-success": "#2E8C4AFF",
	"--icon-warning": "#CC7700FF",
	"--icon-critical": "#CC2222FF",
	"--icon-emphasis": "#111111FF",
	"--icon-brand": "#E53B3BFF",
	"--border-default": "#DDDDDDFF",
	"--border-secondary": "#EEEEEEFF",
	"--border-tertiary": "#BBBBBBFF",
	"--border-disabled": "#EEEEEEFF",
	"--border-inverse": "#555555FF",
	"--border-focus": "#111111FF",
	"--border-brand": "#E53B3BFF",
	"--border-info": "#A0C0E0FF",
	"--border-success": "#88C8A0FF",
	"--border-warning": "#E8C880FF",
	"--border-critical": "#E8A0A0FF",
	"--border-emphasis": "#111111FF",
	"--chart-1": "#111111FF",
	"--chart-2": "#E53B3BFF",
	"--chart-3": "#555555FF",
	"--chart-4": "#888888FF",
	"--chart-5": "#BBBBBBFF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#FFFFFFFF",
	"--foreground": "#111111FF",
	"--card": "#FFFFFFFF",
	"--card-foreground": "#111111FF",
	"--popover": "#FFFFFFFF",
	"--popover-foreground": "#111111FF",
	"--primary": "#111111FF",
	"--primary-foreground": "#FFFFFFFF",
	"--secondary": "#F5F5F5FF",
	"--secondary-foreground": "#111111FF",
	"--muted": "#F5F5F5FF",
	"--muted-foreground": "#777777FF",
	"--accent": "#EEEEEEFF",
	"--accent-foreground": "#111111FF",
	"--destructive": "#CC2222FF",
	"--border": "#DDDDDDFF",
	"--input": "#EEEEEEFF",
	"--ring": "#111111FF",
	"--sidebar-background": "#FFFFFFFF",
	"--sidebar-foreground": "#111111FF",
	"--sidebar-primary": "#111111FF",
	"--sidebar-primary-foreground": "#FFFFFFFF",
	"--sidebar-accent": "#F5F5F5FF",
	"--sidebar-accent-foreground": "#111111FF",
	"--sidebar-border": "#DDDDDDFF",
	"--sidebar-ring": "#111111FF",

	// ── Dimension tokens ──────────────────────────────────────────────────
	"--spacing": "0.25rem",
	"--border-width-base": "0.0625rem",
	"--radius": "0rem",
	"--font-size-base": "0.9375rem",
	"--leading-base": "1.45",
	"--letter-spacing-base": "0.04em",
	"--opacity-hover": "0.6",
	"--opacity-active": "0.5",
	"--opacity-disabled": "0.35",
	"--shadow-offset-y": "0px",
	"--shadow-blur": "0px",
	"--shadow-spread": "0px",
	"--shadow-base-color": "rgba(0, 0, 0, 0)",
	"--container-sm": "576px",
	"--container-md": "720px",
	"--container-lg": "960px",
	"--container-xl": "1200px",
	"--container-2xl": "1296px",
	"--dropdown-offset": "2",
	"--overlay-offset": "2",

	// ── Fonts: Helvetica Neue system stack ────────────────────────────────
	"--font-sans": '"Helvetica Neue", "Arial", system-ui, sans-serif',
	"--font-heading": '"Helvetica Neue", "Arial", system-ui, sans-serif',
	"--font-brand": '"Helvetica Neue", "Arial", system-ui, sans-serif',

	// ── Phase 1a: Component tokens ────────────────────────────────────────
	// Grid-aligned. Zero radius. Everything is a rectangle.
	"--button-radius": "0px",
	"--button-padding-x": "calc(var(--spacing) * 4)",
	"--button-padding-y": "calc(var(--spacing) * 2)",
	"--card-radius": "0px",
	"--card-padding": "calc(var(--spacing) * 6)",
	"--nav-height": "calc(var(--spacing) * 14)",
	"--section-padding-y": "calc(var(--spacing) * 20)",
	"--hero-padding-y": "calc(var(--spacing) * 32)",
	"--input-radius": "0px",
	"--input-height": "calc(var(--spacing) * 10)",
	"--badge-radius": "0px",

	// ── Phase 1b: Motion — opacity-based, no transforms ───────────────────
	"--transition-default": "100ms linear",
	"--transition-fast": "60ms linear",
	"--transition-slow": "180ms linear",
	"--hover-transform": "none",
	"--hover-shadow": "none",
	"--active-scale": "1",

	// ── Phase 1c: Typography — Helvetica at its most authoritative ────────
	"--heading-font-weight": "700",
	"--heading-letter-spacing": "var(--tracking-tight)",
	"--body-letter-spacing": "var(--tracking-wide)",
	"--hero-font-size": "var(--text-6xl)",
	"--hero-font-weight": "700",
	"--hero-letter-spacing": "var(--tracking-tight)",
	"--section-title-size": "var(--text-4xl)",
	"--section-title-font-weight": "700",
	"--section-title-letter-spacing": "var(--tracking-tight)",
	"--card-title-size": "var(--text-base)",
	"--card-title-font-weight": "700",
	"--card-title-letter-spacing": "var(--tracking-normal)",
}

export const swissDark: Record<string, string> = {
	// ── Dark: ink inverted, grid maintained ───────────────────────────────
	"--bg-default": "#0C0C0CFF",
	"--bg-inverse": "#F2F2F2FF",
	"--bg-muted": "#161616FF",
	"--bg-surface-default": "#0C0C0CFF",
	"--bg-surface-info": "#0A1828FF",
	"--bg-surface-success": "#0A1A0AFF",
	"--bg-surface-warning": "#1E1508FF",
	"--bg-surface-critical": "#1E0808FF",
	"--bg-surface-emphasis": "#161616FF",
	"--bg-surface-inverse": "#707070FF",
	"--bg-surface-transparent": "#FFFFFF08",
	"--bg-surface-brand": "#1E0808FF",
	"--bg-surface-hover": "#1E1E1EFF",
	"--bg-fill-default": "#0C0C0CFF",
	"--bg-fill-primary": "#F2F2F2FF",
	"--bg-fill-brand": "#FF4444FF",
	"--bg-fill-info": "#5590D4FF",
	"--bg-fill-success": "#3EA858FF",
	"--bg-fill-warning": "#DD8800FF",
	"--bg-fill-critical": "#DD2828FF",
	"--bg-fill-emphasis": "#F2F2F2FF",
	"--bg-fill-transparent": "#FFFFFF08",
	"--bg-fill-secondary": "#2A2A2AFF",
	"--bg-fill-secondary-inverse": "#0C0C0CFF",
	"--text-default": "#F2F2F2FF",
	"--text-secondary": "#C0C0C0FF",
	"--text-muted": "#888888FF",
	"--text-disabled": "#444444FF",
	"--text-inverse": "#0C0C0CFF",
	"--text-info": "#99BBEEFF",
	"--text-success": "#77DD88FF",
	"--text-warning": "#FFCC55FF",
	"--text-critical": "#FF7777FF",
	"--text-emphasis": "#F2F2F2FF",
	"--text-brand": "#FF8888FF",
	"--text-link": "#FF4444FF",
	"--icon-default": "#F2F2F2FF",
	"--icon-secondary": "#C0C0C0FF",
	"--icon-disabled": "#383838FF",
	"--icon-inverse": "#0C0C0CFF",
	"--icon-info": "#5590D4FF",
	"--icon-success": "#3EA858FF",
	"--icon-warning": "#DD8800FF",
	"--icon-critical": "#DD2828FF",
	"--icon-emphasis": "#F2F2F2FF",
	"--icon-brand": "#FF4444FF",
	"--border-default": "#3A3A3AFF",
	"--border-secondary": "#2A2A2AFF",
	"--border-tertiary": "#4A4A4AFF",
	"--border-disabled": "#2A2A2AFF",
	"--border-inverse": "#888888FF",
	"--border-focus": "#F2F2F2FF",
	"--border-brand": "#FF4444FF",
	"--border-info": "#284860FF",
	"--border-success": "#285A38FF",
	"--border-warning": "#4A3A10FF",
	"--border-critical": "#4A1818FF",
	"--border-emphasis": "#3A3A3AFF",
	"--chart-1": "#F2F2F2FF",
	"--chart-2": "#FF4444FF",
	"--chart-3": "#888888FF",
	"--chart-4": "#3EA858FF",
	"--chart-5": "#5590D4FF",

	// ── shadcn / ui compatibility ─────────────────────────────────────────
	"--background": "#0C0C0CFF",
	"--foreground": "#F2F2F2FF",
	"--card": "#0C0C0CFF",
	"--card-foreground": "#F2F2F2FF",
	"--popover": "#161616FF",
	"--popover-foreground": "#F2F2F2FF",
	"--primary": "#F2F2F2FF",
	"--primary-foreground": "#0C0C0CFF",
	"--secondary": "#1E1E1EFF",
	"--secondary-foreground": "#F2F2F2FF",
	"--muted": "#1E1E1EFF",
	"--muted-foreground": "#888888FF",
	"--accent": "#1E1E1EFF",
	"--accent-foreground": "#F2F2F2FF",
	"--destructive": "#DD2828FF",
	"--border": "#3A3A3AFF",
	"--input": "#2A2A2AFF",
	"--ring": "#F2F2F2FF",
	"--sidebar-background": "#0C0C0CFF",
	"--sidebar-foreground": "#F2F2F2FF",
	"--sidebar-primary": "#F2F2F2FF",
	"--sidebar-primary-foreground": "#0C0C0CFF",
	"--sidebar-accent": "#1E1E1EFF",
	"--sidebar-accent-foreground": "#F2F2F2FF",
	"--sidebar-border": "#3A3A3AFF",
	"--sidebar-ring": "#F2F2F2FF",

	// ── Fonts carry over ──────────────────────────────────────────────────
	"--font-sans": '"Helvetica Neue", "Arial", system-ui, sans-serif',
	"--font-heading": '"Helvetica Neue", "Arial", system-ui, sans-serif',
	"--font-brand": '"Helvetica Neue", "Arial", system-ui, sans-serif',
}
