export interface ComponentEntry {
	name: string;
	description: string;
	files: { src: string; dest: string }[];
	deps: string[];
	internalDeps: string[];
	tags: string[];
	postInstallNote?: string;
}

export const registry: Record<string, ComponentEntry> = {
	// ─── Foundation ──────────────────────────────────────────────────────
	utils: {
		name: "utils",
		description: "Utility functions for className merging and focus ring styles",
		files: [{ src: "templates/lib/utils.ts", dest: "lib/utils.ts" }],
		deps: ["clsx", "tailwind-merge"],
		internalDeps: [],
		tags: ["foundation"],
	},
	styles: {
		name: "styles",
		description: "Base design system CSS styles and theme tokens",
		files: [{ src: "templates/styles/composable.css", dest: "styles/composable.css" }],
		deps: ["tailwindcss"],
		internalDeps: [],
		tags: ["foundation"],
	},
	"numeric-input": {
		name: "numeric-input",
		description: "Numeric input parsing and formatting utilities",
		files: [{ src: "templates/lib/numeric-input.ts", dest: "lib/numeric-input.ts" }],
		deps: [],
		internalDeps: [],
		tags: ["foundation"],
	},

	// ─── Hooks ───────────────────────────────────────────────────────────
	"use-mobile": {
		name: "use-mobile",
		description: "Hook to detect mobile viewport breakpoint",
		files: [{ src: "templates/hooks/use-mobile.ts", dest: "hooks/use-mobile.ts" }],
		deps: [],
		internalDeps: [],
		tags: ["hook"],
	},
	"use-numeric-input": {
		name: "use-numeric-input",
		description: "Hook for numeric input handling with sanitization and parsing",
		files: [{ src: "templates/hooks/use-numeric-input.ts", dest: "hooks/use-numeric-input.ts" }],
		deps: [],
		internalDeps: ["numeric-input"],
		tags: ["hook"],
	},

	// ─── Tooling ─────────────────────────────────────────────────────────
	"biome-ui-restricted": {
		name: "biome-ui-restricted",
		description: "Biome lint rule restricting direct UI component imports",
		files: [{ src: "templates/rules/biome-ui-restricted.json", dest: "rules/biome-ui-restricted.json" }],
		deps: [],
		internalDeps: [],
		tags: ["tooling"],
		postInstallNote:
			'Add to your biome.json to activate:\n  "extends": ["./src/rules/biome-ui-restricted.json"]',
	},
	"biome-no-direct-icons": {
		name: "biome-no-direct-icons",
		description: "Biome lint rule discouraging direct lucide-react imports in app code",
		files: [
			{
				src: "templates/rules/biome-no-direct-icons.json",
				dest: "rules/biome-no-direct-icons.json",
			},
		],
		deps: [],
		internalDeps: [],
		tags: ["tooling"],
		postInstallNote:
			'Add to your biome.json to activate:\n  "extends": ["./src/rules/biome-no-direct-icons.json"]',
	},
	"biome-a11y": {
		name: "biome-a11y",
		description: "Biome lint rule set with enhanced accessibility enforcement",
		files: [{ src: "templates/rules/biome-a11y.json", dest: "rules/biome-a11y.json" }],
		deps: [],
		internalDeps: [],
		tags: ["tooling"],
		postInstallNote:
			'Add to your biome.json to activate:\n  "extends": ["./src/rules/biome-a11y.json"]',
	},

	"lint-no-arbitrary": {
		name: "lint-no-arbitrary",
		description: "Script that detects arbitrary Tailwind CSS values in TSX/TS files and exits non-zero if found",
		files: [
			{
				src: "templates/scripts/lint-no-arbitrary.ts",
				dest: "scripts/lint-no-arbitrary.ts",
			},
		],
		deps: [],
		internalDeps: [],
		tags: ["tooling"],
		postInstallNote:
			'Run with: bun scripts/lint-no-arbitrary.ts [dir]\nAdd to CI: bun scripts/lint-no-arbitrary.ts src',
	},

	// ─── Primitive UI Components ─────────────────────────────────────────
	accordion: {
		name: "accordion",
		description: "Vertically collapsible content sections",
		files: [{ src: "templates/_internal/accordion.tsx", dest: "components/_internal/accordion.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	alert: {
		name: "alert",
		description: "Contextual feedback messages for user actions",
		files: [{ src: "templates/_internal/alert.tsx", dest: "components/_internal/alert.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"alert-dialog": {
		name: "alert-dialog",
		description: "Modal dialog for important confirmations",
		files: [{ src: "templates/_internal/alert-dialog.tsx", dest: "components/_internal/alert-dialog.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	"aspect-ratio": {
		name: "aspect-ratio",
		description: "Container that maintains a fixed aspect ratio",
		files: [{ src: "templates/_internal/aspect-ratio.tsx", dest: "components/_internal/aspect-ratio.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	avatar: {
		name: "avatar",
		description: "Circular image element for user profiles",
		files: [{ src: "templates/_internal/avatar.tsx", dest: "components/_internal/avatar.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	badge: {
		name: "badge",
		description: "Small status label with color variants",
		files: [{ src: "templates/_internal/badge.tsx", dest: "components/_internal/badge.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	breadcrumb: {
		name: "breadcrumb",
		description: "Navigation trail showing page hierarchy",
		files: [{ src: "templates/_internal/breadcrumb.tsx", dest: "components/_internal/breadcrumb.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	button: {
		name: "button",
		description: "Clickable button element with size and style variants",
		files: [{ src: "templates/_internal/button.tsx", dest: "components/_internal/button.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	calendar: {
		name: "calendar",
		description: "Date picker calendar powered by react-day-picker",
		files: [{ src: "templates/_internal/calendar.tsx", dest: "components/_internal/calendar.tsx" }],
		deps: ["lucide-react", "react-day-picker"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	card: {
		name: "card",
		description: "Bordered content container with header and footer slots",
		files: [{ src: "templates/_internal/card.tsx", dest: "components/_internal/card.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	carousel: {
		name: "carousel",
		description: "Horizontally scrollable content slider with navigation",
		files: [{ src: "templates/_internal/carousel.tsx", dest: "components/_internal/carousel.tsx" }],
		deps: ["embla-carousel-react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	checkbox: {
		name: "checkbox",
		description: "Toggle checkbox input with checked state",
		files: [{ src: "templates/_internal/checkbox.tsx", dest: "components/_internal/checkbox.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	collapsible: {
		name: "collapsible",
		description: "Expandable and collapsible content panel",
		files: [{ src: "templates/_internal/collapsible.tsx", dest: "components/_internal/collapsible.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: [],
		tags: ["primitive"],
	},
	combobox: {
		name: "combobox",
		description: "Searchable select dropdown with autocomplete",
		files: [{ src: "templates/_internal/combobox.tsx", dest: "components/_internal/combobox.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["button", "input-group", "utils"],
		tags: ["primitive"],
	},
	container: {
		name: "container",
		description: "Centered max-width content wrapper",
		files: [{ src: "templates/_internal/container.tsx", dest: "components/_internal/container.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	dialog: {
		name: "dialog",
		description: "Modal dialog overlay with header, body, and footer",
		files: [{ src: "templates/_internal/dialog.tsx", dest: "components/_internal/dialog.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	divider: {
		name: "divider",
		description: "Horizontal or vertical divider with solid, dots, and pills variants",
		files: [{ src: "templates/_internal/divider.tsx", dest: "components/_internal/divider.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"dropdown-menu": {
		name: "dropdown-menu",
		description: "Contextual menu triggered by a button",
		files: [{ src: "templates/_internal/dropdown-menu.tsx", dest: "components/_internal/dropdown-menu.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	dropzone: {
		name: "dropzone",
		description: "Drag-and-drop file upload area",
		files: [{ src: "templates/_internal/dropzone.tsx", dest: "components/_internal/dropzone.tsx" }],
		deps: ["lucide-react", "react-dropzone"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	empty: {
		name: "empty",
		description: "Empty state placeholder with icon, title, and description",
		files: [{ src: "templates/_internal/empty.tsx", dest: "components/_internal/empty.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	field: {
		name: "field",
		description: "Form field wrapper with label, description, and error slots",
		files: [{ src: "templates/_internal/field.tsx", dest: "components/_internal/field.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["label", "separator", "utils"],
		tags: ["primitive"],
	},
	grid: {
		name: "grid",
		description: "Responsive CSS grid layout component",
		files: [{ src: "templates/_internal/grid.tsx", dest: "components/_internal/grid.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	"hover-card": {
		name: "hover-card",
		description: "Preview card shown on hover",
		files: [{ src: "templates/_internal/hover-card.tsx", dest: "components/_internal/hover-card.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	icon: {
		name: "icon",
		description: "Icon wrapper with size and color variants",
		files: [{ src: "templates/_internal/icon.tsx", dest: "components/_internal/icon.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	input: {
		name: "input",
		description: "Text input field with focus ring styling",
		files: [{ src: "templates/_internal/input.tsx", dest: "components/_internal/input.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"input-group": {
		name: "input-group",
		description: "Input with addons, buttons, and text segments",
		files: [{ src: "templates/_internal/input-group.tsx", dest: "components/_internal/input-group.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["button", "input", "textarea", "utils"],
		tags: ["primitive"],
	},
	item: {
		name: "item",
		description: "Flexible list item with media, content, and actions",
		files: [{ src: "templates/_internal/item.tsx", dest: "components/_internal/item.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["separator", "utils"],
		tags: ["primitive"],
	},
	label: {
		name: "label",
		description: "Accessible text label for form controls",
		files: [{ src: "templates/_internal/label.tsx", dest: "components/_internal/label.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	pagination: {
		name: "pagination",
		description: "Page navigation with previous, next, and page links",
		files: [{ src: "templates/_internal/pagination.tsx", dest: "components/_internal/pagination.tsx" }],
		deps: ["lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	popover: {
		name: "popover",
		description: "Floating content panel anchored to a trigger",
		files: [{ src: "templates/_internal/popover.tsx", dest: "components/_internal/popover.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	progress: {
		name: "progress",
		description: "Horizontal progress bar indicator",
		files: [{ src: "templates/_internal/progress.tsx", dest: "components/_internal/progress.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"radio-group": {
		name: "radio-group",
		description: "Group of mutually exclusive radio options",
		files: [{ src: "templates/_internal/radio-group.tsx", dest: "components/_internal/radio-group.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	resizable: {
		name: "resizable",
		description: "Resizable split pane panels",
		files: [{ src: "templates/_internal/resizable.tsx", dest: "components/_internal/resizable.tsx" }],
		deps: ["react-resizable-panels"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"scroll-area": {
		name: "scroll-area",
		description: "Custom scrollbar container with overflow handling",
		files: [{ src: "templates/_internal/scroll-area.tsx", dest: "components/_internal/scroll-area.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	select: {
		name: "select",
		description: "Dropdown select menu with scrollable options",
		files: [{ src: "templates/_internal/select.tsx", dest: "components/_internal/select.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	separator: {
		name: "separator",
		description: "Visual divider line between content sections",
		files: [{ src: "templates/_internal/separator.tsx", dest: "components/_internal/separator.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	sheet: {
		name: "sheet",
		description: "Slide-out panel from screen edge",
		files: [{ src: "templates/_internal/sheet.tsx", dest: "components/_internal/sheet.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	sidebar: {
		name: "sidebar",
		description: "Application sidebar with collapsible navigation groups",
		files: [{ src: "templates/_internal/sidebar.tsx", dest: "components/_internal/sidebar.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority", "lucide-react"],
		internalDeps: ["button", "input", "separator", "sheet", "skeleton", "tooltip", "use-mobile", "utils"],
		tags: ["primitive"],
	},
	skeleton: {
		name: "skeleton",
		description: "Animated placeholder for loading content",
		files: [{ src: "templates/_internal/skeleton.tsx", dest: "components/_internal/skeleton.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	slider: {
		name: "slider",
		description: "Draggable range slider input",
		files: [{ src: "templates/_internal/slider.tsx", dest: "components/_internal/slider.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	sonner: {
		name: "sonner",
		description: "Toast notification system powered by Sonner",
		files: [{ src: "templates/_internal/sonner.tsx", dest: "components/_internal/sonner.tsx" }],
		deps: ["sonner"],
		internalDeps: [],
		tags: ["primitive"],
	},
	spacer: {
		name: "spacer",
		description: "Flexible whitespace component for spacing",
		files: [{ src: "templates/_internal/spacer.tsx", dest: "components/_internal/spacer.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	stack: {
		name: "stack",
		description: "Flex-based vertical or horizontal stack layout",
		files: [{ src: "templates/_internal/stack.tsx", dest: "components/_internal/stack.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	switch: {
		name: "switch",
		description: "Toggle switch for on/off states",
		files: [{ src: "templates/_internal/switch.tsx", dest: "components/_internal/switch.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	table: {
		name: "table",
		description: "Semantic HTML table with styled rows and cells",
		files: [{ src: "templates/_internal/table.tsx", dest: "components/_internal/table.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	tabs: {
		name: "tabs",
		description: "Tabbed content navigation with line and pill variants",
		files: [{ src: "templates/_internal/tabs.tsx", dest: "components/_internal/tabs.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	textarea: {
		name: "textarea",
		description: "Multi-line text input with auto-sizing",
		files: [{ src: "templates/_internal/textarea.tsx", dest: "components/_internal/textarea.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	toggle: {
		name: "toggle",
		description: "Pressable toggle button with active state",
		files: [{ src: "templates/_internal/toggle.tsx", dest: "components/_internal/toggle.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	tooltip: {
		name: "tooltip",
		description: "Informational popup on hover or focus",
		files: [{ src: "templates/_internal/tooltip.tsx", dest: "components/_internal/tooltip.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	typography: {
		name: "typography",
		description: "Polymorphic text component with typographic scale variants",
		files: [{ src: "templates/_internal/typography.tsx", dest: "components/_internal/typography.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},

	"line-item": {
		name: "line-item",
		description: "Key-value row primitive with dot/solid/pills divider leader between label and value. Variants: default, fill, bold, compact.",
		files: [{ src: "templates/_internal/line-item.tsx", dest: "components/_internal/line-item.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["divider", "utils"],
		tags: ["primitive"],
	},
	"line-item-header": {
		name: "line-item-header",
		description: "Section header label for receipt/list layouts. Variants: default (filled), bordered.",
		files: [{ src: "templates/_internal/line-item-header.tsx", dest: "components/_internal/line-item-header.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	glyph: {
		name: "glyph",
		description: "Fixed-size square containing a centred character or symbol. Variants: default, filled, circle, circle-inverted.",
		files: [{ src: "templates/_internal/glyph.tsx", dest: "components/_internal/glyph.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"layout-bento": {
		name: "layout-bento",
		description:
			"Bento grid layout primitives: BentoGrid, BentoCell, BentoSplit, BentoLeader, BentoQuad, BentoTriple, CellGrid, CellRow, StatCell. Gap-as-border system using base tokens (--border, --radius) with configurable --bento-gap.",
		files: [{ src: "templates/_internal/layout-bento.tsx", dest: "components/_internal/layout-bento.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	layout: {
		name: "layout",
		description:
			"Rigid layout primitives: Section (macro spacing tokens), FlexSpacer (flex-1 aria-hidden), NewspaperGrid and NewspaperCell (newspaper-border pattern — container border-t/l, cells border-b/r, each edge drawn once). All spacing via --space-layout-sm/md/lg tokens.",
		files: [{ src: "templates/_internal/layout.tsx", dest: "components/_internal/layout.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},

	// ─── Opinionated UI Components ───────────────────────────────────────
	"pricing-card": {
		name: "pricing-card",
		description: "Pricing card with ledger-style layout using composables primitives. Accepts a PricingProduct data shape and renders a full card with header, feature list, total, and CTA button.",
		files: [{ src: "templates/ui-opinionated/pricing-card.tsx", dest: "components/ui-opinionated/pricing-card.tsx" }],
		deps: [],
		internalDeps: ["button", "divider", "line-item-header", "typography"],
		tags: ["opinionated"],
	},

	"accordion-opinionated": {
		name: "accordion-opinionated",
		description: "Opinionated accordion with items array API",
		files: [{ src: "templates/ui-opinionated/accordion.tsx", dest: "components/ui-opinionated/accordion.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["accordion"],
		tags: ["opinionated"],
	},
	"alert-opinionated": {
		name: "alert-opinionated",
		description: "Opinionated alert with type-based icon and variant mapping",
		files: [{ src: "templates/ui-opinionated/alert.tsx", dest: "components/ui-opinionated/alert.tsx" }],
		deps: ["lucide-react"],
		internalDeps: ["alert"],
		tags: ["opinionated"],
	},
	"badge-opinionated": {
		name: "badge-opinionated",
		description: "Opinionated badge with simplified variant prop",
		files: [{ src: "templates/ui-opinionated/badge.tsx", dest: "components/ui-opinionated/badge.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["badge"],
		tags: ["opinionated"],
	},
	"button-opinionated": {
		name: "button-opinionated",
		description: "Opinionated button with loading spinner support",
		files: [{ src: "templates/ui-opinionated/button.tsx", dest: "components/ui-opinionated/button.tsx" }],
		deps: ["class-variance-authority", "lucide-react"],
		internalDeps: ["button"],
		tags: ["opinionated"],
	},
	"card-opinionated": {
		name: "card-opinionated",
		description: "Opinionated card with title, description, action, and footer props",
		files: [{ src: "templates/ui-opinionated/card.tsx", dest: "components/ui-opinionated/card.tsx" }],
		deps: [],
		internalDeps: ["card"],
		tags: ["opinionated"],
	},
	"collapsible-opinionated": {
		name: "collapsible-opinionated",
		description: "Opinionated collapsible with trigger prop and chevron icons",
		files: [{ src: "templates/ui-opinionated/collapsible.tsx", dest: "components/ui-opinionated/collapsible.tsx" }],
		deps: ["lucide-react"],
		internalDeps: ["collapsible", "utils"],
		tags: ["opinionated"],
	},
	"dialog-opinionated": {
		name: "dialog-opinionated",
		description: "Opinionated modal dialog with trigger, title, and footer props",
		files: [{ src: "templates/ui-opinionated/dialog.tsx", dest: "components/ui-opinionated/dialog.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["dialog"],
		tags: ["opinionated"],
	},
	"empty-opinionated": {
		name: "empty-opinionated",
		description: "Opinionated empty state with table row variant",
		files: [{ src: "templates/ui-opinionated/empty.tsx", dest: "components/ui-opinionated/empty.tsx" }],
		deps: [],
		internalDeps: ["empty", "table-opinionated", "typography-opinionated"],
		tags: ["opinionated"],
	},
	"form-calendar-popover": {
		name: "form-calendar-popover",
		description: "Date picker field with calendar popover",
		files: [{ src: "templates/ui-opinionated/form-calendar-popover.tsx", dest: "components/ui-opinionated/form-calendar-popover.tsx" }],
		deps: ["class-variance-authority", "lucide-react"],
		internalDeps: ["button", "calendar", "field", "popover", "utils"],
		tags: ["opinionated", "form"],
	},
	"form-checkbox": {
		name: "form-checkbox",
		description: "Checkbox field with label, description, and error handling",
		files: [{ src: "templates/ui-opinionated/form-checkbox.tsx", dest: "components/ui-opinionated/form-checkbox.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["checkbox", "field"],
		tags: ["opinionated", "form"],
	},
	"form-combobox": {
		name: "form-combobox",
		description: "Searchable select field with options array API",
		files: [{ src: "templates/ui-opinionated/form-combobox.tsx", dest: "components/ui-opinionated/form-combobox.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["combobox", "field"],
		tags: ["opinionated", "form"],
	},
	"form-date-of-birth": {
		name: "form-date-of-birth",
		description: "Three-field date of birth input with auto-advance",
		files: [{ src: "templates/ui-opinionated/form-date-of-birth.tsx", dest: "components/ui-opinionated/form-date-of-birth.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "input", "utils"],
		tags: ["opinionated", "form"],
	},
	"form-dropzone": {
		name: "form-dropzone",
		description: "Single file upload field with drag-and-drop",
		files: [{ src: "templates/ui-opinionated/form-dropzone.tsx", dest: "components/ui-opinionated/form-dropzone.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["dropzone", "field"],
		tags: ["opinionated", "form"],
	},
	"form-input": {
		name: "form-input",
		description: "Text input field with label, error, and numeric mode support",
		files: [{ src: "templates/ui-opinionated/form-input.tsx", dest: "components/ui-opinionated/form-input.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "input", "use-numeric-input"],
		tags: ["opinionated", "form"],
	},
	"form-input-group": {
		name: "form-input-group",
		description: "Input group field with addons, buttons, and numeric support",
		files: [{ src: "templates/ui-opinionated/form-input-group.tsx", dest: "components/ui-opinionated/form-input-group.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "input-group", "use-numeric-input"],
		tags: ["opinionated", "form"],
	},
	"form-multi-combobox": {
		name: "form-multi-combobox",
		description: "Multi-select combobox field with chip display",
		files: [{ src: "templates/ui-opinionated/form-multi-combobox.tsx", dest: "components/ui-opinionated/form-multi-combobox.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["combobox", "field"],
		tags: ["opinionated", "form"],
	},
	"form-multi-dropzone": {
		name: "form-multi-dropzone",
		description: "Multi-file upload field with drag-and-drop",
		files: [{ src: "templates/ui-opinionated/form-multi-dropzone.tsx", dest: "components/ui-opinionated/form-multi-dropzone.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["dropzone", "field"],
		tags: ["opinionated", "form"],
	},
	"form-radiogroup": {
		name: "form-radiogroup",
		description: "Radio group field with options array API",
		files: [{ src: "templates/ui-opinionated/form-radiogroup.tsx", dest: "components/ui-opinionated/form-radiogroup.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["field", "label", "radio-group"],
		tags: ["opinionated", "form"],
	},
	"form-select": {
		name: "form-select",
		description: "Select dropdown field with options array API",
		files: [{ src: "templates/ui-opinionated/form-select.tsx", dest: "components/ui-opinionated/form-select.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "select"],
		tags: ["opinionated", "form"],
	},
	"form-slider": {
		name: "form-slider",
		description: "Slider field with label, value display, and error handling",
		files: [{ src: "templates/ui-opinionated/form-slider.tsx", dest: "components/ui-opinionated/form-slider.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["field", "slider"],
		tags: ["opinionated", "form"],
	},
	"form-switch": {
		name: "form-switch",
		description: "Switch toggle field with label and description",
		files: [{ src: "templates/ui-opinionated/form-switch.tsx", dest: "components/ui-opinionated/form-switch.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["field", "switch"],
		tags: ["opinionated", "form"],
	},
	"form-textarea": {
		name: "form-textarea",
		description: "Textarea field with label, description, and error handling",
		files: [{ src: "templates/ui-opinionated/form-textarea.tsx", dest: "components/ui-opinionated/form-textarea.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "textarea"],
		tags: ["opinionated", "form"],
	},
	"item-opinionated": {
		name: "item-opinionated",
		description: "Opinionated list item with title, description, icon, and actions props",
		files: [{ src: "templates/ui-opinionated/item.tsx", dest: "components/ui-opinionated/item.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["item", "typography-opinionated"],
		tags: ["opinionated"],
	},
	"pagination-opinionated": {
		name: "pagination-opinionated",
		description: "Opinionated pagination with currentPage and totalPages API",
		files: [{ src: "templates/ui-opinionated/pagination.tsx", dest: "components/ui-opinionated/pagination.tsx" }],
		deps: [],
		internalDeps: ["pagination"],
		tags: ["opinionated"],
	},
	"resizable-opinionated": {
		name: "resizable-opinionated",
		description: "Re-exported resizable panel components",
		files: [{ src: "templates/ui-opinionated/resizable.tsx", dest: "components/ui-opinionated/resizable.tsx" }],
		deps: [],
		internalDeps: ["resizable"],
		tags: ["opinionated"],
	},
	"scroll-area-opinionated": {
		name: "scroll-area-opinionated",
		description: "Opinionated scroll area with maxHeight presets",
		files: [{ src: "templates/ui-opinionated/scroll-area.tsx", dest: "components/ui-opinionated/scroll-area.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["scroll-area", "utils"],
		tags: ["opinionated"],
	},
	"sheet-opinionated": {
		name: "sheet-opinionated",
		description: "Opinionated sheet with trigger, title, and footer props",
		files: [{ src: "templates/ui-opinionated/sheet.tsx", dest: "components/ui-opinionated/sheet.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["sheet"],
		tags: ["opinionated"],
	},
	"skeleton-opinionated": {
		name: "skeleton-opinionated",
		description: "Opinionated skeleton with shape variants and preset helpers",
		files: [{ src: "templates/ui-opinionated/skeleton.tsx", dest: "components/ui-opinionated/skeleton.tsx" }],
		deps: [],
		internalDeps: ["skeleton", "utils"],
		tags: ["opinionated"],
	},
	"table-opinionated": {
		name: "table-opinionated",
		description: "Re-exported table components for opinionated layer",
		files: [{ src: "templates/ui-opinionated/table.tsx", dest: "components/ui-opinionated/table.tsx" }],
		deps: [],
		internalDeps: ["table"],
		tags: ["opinionated"],
	},
	"tabs-opinionated": {
		name: "tabs-opinionated",
		description: "Opinionated tabs with items array API",
		files: [{ src: "templates/ui-opinionated/tabs.tsx", dest: "components/ui-opinionated/tabs.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["tabs"],
		tags: ["opinionated"],
	},
	"toggle-opinionated": {
		name: "toggle-opinionated",
		description: "Opinionated toggle with left and right icon slots",
		files: [{ src: "templates/ui-opinionated/toggle.tsx", dest: "components/ui-opinionated/toggle.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["toggle"],
		tags: ["opinionated"],
	},
	"tooltip-opinionated": {
		name: "tooltip-opinionated",
		description: "Opinionated tooltip with content prop shorthand",
		files: [{ src: "templates/ui-opinionated/tooltip.tsx", dest: "components/ui-opinionated/tooltip.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["tooltip"],
		tags: ["opinionated"],
	},
	"typography-opinionated": {
		name: "typography-opinionated",
		description: "Re-exported typography component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/typography.tsx", dest: "components/ui-opinionated/typography.tsx" }],
		deps: [],
		internalDeps: ["typography"],
		tags: ["opinionated"],
	},

	// ─── New Opinionated Wrappers ────────────────────────────────────────
	"alert-dialog-opinionated": {
		name: "alert-dialog-opinionated",
		description: "Opinionated alert dialog with trigger, title, description, and action props",
		files: [{ src: "templates/ui-opinionated/alert-dialog.tsx", dest: "components/ui-opinionated/alert-dialog.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["alert-dialog"],
		tags: ["opinionated"],
	},
	"aspect-ratio-opinionated": {
		name: "aspect-ratio-opinionated",
		description: "Re-exported aspect ratio component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/aspect-ratio.tsx", dest: "components/ui-opinionated/aspect-ratio.tsx" }],
		deps: [],
		internalDeps: ["aspect-ratio"],
		tags: ["opinionated"],
	},
	"avatar-opinionated": {
		name: "avatar-opinionated",
		description: "Opinionated avatar with automatic initials fallback from name",
		files: [{ src: "templates/ui-opinionated/avatar.tsx", dest: "components/ui-opinionated/avatar.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["avatar"],
		tags: ["opinionated"],
	},
	"block-loader-opinionated": {
		name: "block-loader-opinionated",
		description: "Re-exported block loader component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/block-loader.tsx", dest: "components/ui-opinionated/block-loader.tsx" }],
		deps: [],
		internalDeps: ["block-loader"],
		tags: ["opinionated"],
	},
	"breadcrumb-opinionated": {
		name: "breadcrumb-opinionated",
		description: "Opinionated breadcrumb with items array API",
		files: [{ src: "templates/ui-opinionated/breadcrumb.tsx", dest: "components/ui-opinionated/breadcrumb.tsx" }],
		deps: [],
		internalDeps: ["breadcrumb"],
		tags: ["opinionated"],
	},
	"calendar-opinionated": {
		name: "calendar-opinionated",
		description: "Re-exported calendar component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/calendar.tsx", dest: "components/ui-opinionated/calendar.tsx" }],
		deps: [],
		internalDeps: ["calendar"],
		tags: ["opinionated"],
	},
	"carousel-opinionated": {
		name: "carousel-opinionated",
		description: "Opinionated carousel with items array API",
		files: [{ src: "templates/ui-opinionated/carousel.tsx", dest: "components/ui-opinionated/carousel.tsx" }],
		deps: ["embla-carousel-react"],
		internalDeps: ["carousel"],
		tags: ["opinionated"],
	},
	"checkbox-opinionated": {
		name: "checkbox-opinionated",
		description: "Re-exported checkbox component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/checkbox.tsx", dest: "components/ui-opinionated/checkbox.tsx" }],
		deps: [],
		internalDeps: ["checkbox"],
		tags: ["opinionated"],
	},
	"code-block-opinionated": {
		name: "code-block-opinionated",
		description: "Re-exported code block component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/code-block.tsx", dest: "components/ui-opinionated/code-block.tsx" }],
		deps: [],
		internalDeps: ["code-block"],
		tags: ["opinionated"],
	},
	"combobox-opinionated": {
		name: "combobox-opinionated",
		description: "Opinionated combobox with options array API for standalone usage",
		files: [{ src: "templates/ui-opinionated/combobox.tsx", dest: "components/ui-opinionated/combobox.tsx" }],
		deps: [],
		internalDeps: ["combobox"],
		tags: ["opinionated"],
	},
	"container-opinionated": {
		name: "container-opinionated",
		description: "Re-exported container component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/container.tsx", dest: "components/ui-opinionated/container.tsx" }],
		deps: [],
		internalDeps: ["container"],
		tags: ["opinionated"],
	},
	"divider-opinionated": {
		name: "divider-opinionated",
		description: "Re-exported divider component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/divider.tsx", dest: "components/ui-opinionated/divider.tsx" }],
		deps: [],
		internalDeps: ["divider"],
		tags: ["opinionated"],
	},
	"dropdown-menu-opinionated": {
		name: "dropdown-menu-opinionated",
		description: "Opinionated dropdown menu with trigger and items array API",
		files: [{ src: "templates/ui-opinionated/dropdown-menu.tsx", dest: "components/ui-opinionated/dropdown-menu.tsx" }],
		deps: [],
		internalDeps: ["dropdown-menu"],
		tags: ["opinionated"],
	},
	"dropzone-opinionated": {
		name: "dropzone-opinionated",
		description: "Re-exported dropzone component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/dropzone.tsx", dest: "components/ui-opinionated/dropzone.tsx" }],
		deps: [],
		internalDeps: ["dropzone"],
		tags: ["opinionated"],
	},
	"field-opinionated": {
		name: "field-opinionated",
		description: "Re-exported field component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/field.tsx", dest: "components/ui-opinionated/field.tsx" }],
		deps: [],
		internalDeps: ["field"],
		tags: ["opinionated"],
	},
	"glyph-opinionated": {
		name: "glyph-opinionated",
		description: "Re-exported glyph component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/glyph.tsx", dest: "components/ui-opinionated/glyph.tsx" }],
		deps: [],
		internalDeps: ["glyph"],
		tags: ["opinionated"],
	},
	"grid-opinionated": {
		name: "grid-opinionated",
		description: "Re-exported grid component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/grid.tsx", dest: "components/ui-opinionated/grid.tsx" }],
		deps: [],
		internalDeps: ["grid"],
		tags: ["opinionated"],
	},
	"hover-card-opinionated": {
		name: "hover-card-opinionated",
		description: "Opinionated hover card with trigger and content props",
		files: [{ src: "templates/ui-opinionated/hover-card.tsx", dest: "components/ui-opinionated/hover-card.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["hover-card"],
		tags: ["opinionated"],
	},
	"icon-opinionated": {
		name: "icon-opinionated",
		description: "Re-exported icon component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/icon.tsx", dest: "components/ui-opinionated/icon.tsx" }],
		deps: [],
		internalDeps: ["icon"],
		tags: ["opinionated"],
	},
	"input-opinionated": {
		name: "input-opinionated",
		description: "Re-exported input component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/input.tsx", dest: "components/ui-opinionated/input.tsx" }],
		deps: [],
		internalDeps: ["input"],
		tags: ["opinionated"],
	},
	"input-group-opinionated": {
		name: "input-group-opinionated",
		description: "Re-exported input group component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/input-group.tsx", dest: "components/ui-opinionated/input-group.tsx" }],
		deps: [],
		internalDeps: ["input-group"],
		tags: ["opinionated"],
	},
	"label-opinionated": {
		name: "label-opinionated",
		description: "Re-exported label component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/label.tsx", dest: "components/ui-opinionated/label.tsx" }],
		deps: [],
		internalDeps: ["label"],
		tags: ["opinionated"],
	},
	"layout-opinionated": {
		name: "layout-opinionated",
		description: "Re-exported layout components for opinionated layer",
		files: [{ src: "templates/ui-opinionated/layout.tsx", dest: "components/ui-opinionated/layout.tsx" }],
		deps: [],
		internalDeps: ["layout"],
		tags: ["opinionated"],
	},
	"layout-bento-opinionated": {
		name: "layout-bento-opinionated",
		description: "Re-exported bento layout components for opinionated layer",
		files: [{ src: "templates/ui-opinionated/layout-bento.tsx", dest: "components/ui-opinionated/layout-bento.tsx" }],
		deps: [],
		internalDeps: ["layout-bento"],
		tags: ["opinionated"],
	},
	"line-item-opinionated": {
		name: "line-item-opinionated",
		description: "Re-exported line item component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/line-item.tsx", dest: "components/ui-opinionated/line-item.tsx" }],
		deps: [],
		internalDeps: ["line-item"],
		tags: ["opinionated"],
	},
	"line-item-header-opinionated": {
		name: "line-item-header-opinionated",
		description: "Re-exported line item header component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/line-item-header.tsx", dest: "components/ui-opinionated/line-item-header.tsx" }],
		deps: [],
		internalDeps: ["line-item-header"],
		tags: ["opinionated"],
	},
	"popover-opinionated": {
		name: "popover-opinionated",
		description: "Opinionated popover with trigger and content props",
		files: [{ src: "templates/ui-opinionated/popover.tsx", dest: "components/ui-opinionated/popover.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["popover"],
		tags: ["opinionated"],
	},
	"progress-opinionated": {
		name: "progress-opinionated",
		description: "Opinionated progress bar with label and value display",
		files: [{ src: "templates/ui-opinionated/progress.tsx", dest: "components/ui-opinionated/progress.tsx" }],
		deps: [],
		internalDeps: ["progress"],
		tags: ["opinionated"],
	},
	"radio-group-opinionated": {
		name: "radio-group-opinionated",
		description: "Re-exported radio group component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/radio-group.tsx", dest: "components/ui-opinionated/radio-group.tsx" }],
		deps: [],
		internalDeps: ["radio-group"],
		tags: ["opinionated"],
	},
	"select-opinionated": {
		name: "select-opinionated",
		description: "Opinionated select with options array API for standalone usage",
		files: [{ src: "templates/ui-opinionated/select.tsx", dest: "components/ui-opinionated/select.tsx" }],
		deps: [],
		internalDeps: ["select"],
		tags: ["opinionated"],
	},
	"separator-opinionated": {
		name: "separator-opinionated",
		description: "Re-exported separator component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/separator.tsx", dest: "components/ui-opinionated/separator.tsx" }],
		deps: [],
		internalDeps: ["separator"],
		tags: ["opinionated"],
	},
	"sidebar-opinionated": {
		name: "sidebar-opinionated",
		description: "Re-exported sidebar components for opinionated layer",
		files: [{ src: "templates/ui-opinionated/sidebar.tsx", dest: "components/ui-opinionated/sidebar.tsx" }],
		deps: [],
		internalDeps: ["sidebar"],
		tags: ["opinionated"],
	},
	"slider-opinionated": {
		name: "slider-opinionated",
		description: "Re-exported slider component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/slider.tsx", dest: "components/ui-opinionated/slider.tsx" }],
		deps: [],
		internalDeps: ["slider"],
		tags: ["opinionated"],
	},
	"sonner-opinionated": {
		name: "sonner-opinionated",
		description: "Re-exported sonner toaster component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/sonner.tsx", dest: "components/ui-opinionated/sonner.tsx" }],
		deps: [],
		internalDeps: ["sonner"],
		tags: ["opinionated"],
	},
	"spacer-opinionated": {
		name: "spacer-opinionated",
		description: "Re-exported spacer component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/spacer.tsx", dest: "components/ui-opinionated/spacer.tsx" }],
		deps: [],
		internalDeps: ["spacer"],
		tags: ["opinionated"],
	},
	"stack-opinionated": {
		name: "stack-opinionated",
		description: "Re-exported stack component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/stack.tsx", dest: "components/ui-opinionated/stack.tsx" }],
		deps: [],
		internalDeps: ["stack"],
		tags: ["opinionated"],
	},
	"switch-opinionated": {
		name: "switch-opinionated",
		description: "Re-exported switch component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/switch.tsx", dest: "components/ui-opinionated/switch.tsx" }],
		deps: [],
		internalDeps: ["switch"],
		tags: ["opinionated"],
	},
	"textarea-opinionated": {
		name: "textarea-opinionated",
		description: "Re-exported textarea component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/textarea.tsx", dest: "components/ui-opinionated/textarea.tsx" }],
		deps: [],
		internalDeps: ["textarea"],
		tags: ["opinionated"],
	},
	"tree-view-opinionated": {
		name: "tree-view-opinionated",
		description: "Re-exported tree view component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/tree-view.tsx", dest: "components/ui-opinionated/tree-view.tsx" }],
		deps: [],
		internalDeps: ["tree-view"],
		tags: ["opinionated"],
	},

	// ─── Phase 2 Components ──────────────────────────────────────────────
	"tree-view": {
		name: "tree-view",
		description: "ASCII-art collapsible tree with keyboard navigation and ARIA semantics",
		files: [{ src: "templates/_internal/tree-view.tsx", dest: "components/_internal/tree-view.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"code-block": {
		name: "code-block",
		description: "Monospace code display with line numbers and overflow scrolling",
		files: [{ src: "templates/_internal/code-block.tsx", dest: "components/_internal/code-block.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"block-loader": {
		name: "block-loader",
		description: "Animated Unicode spinner with 11 sequence modes",
		files: [{ src: "templates/_internal/block-loader.tsx", dest: "components/_internal/block-loader.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	list: {
		name: "list",
		description: "Variant list renderer: arrow, bullet",
		files: [{ src: "templates/ui-opinionated/list.tsx", dest: "components/ui-opinionated/list.tsx" }],
		deps: ["class-variance-authority", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["opinionated"],
	},
	"token-config-panel": {
		name: "token-config-panel",
		description: "Live token editor — color picker, dimension sliders, font selector, JSON export/import, and 6 built-in presets. Edits CSS custom properties on the document root in real time.",
		files: [{ src: "templates/ui-opinionated/token-config-panel.tsx", dest: "components/ui-opinionated/token-config-panel.tsx" }],
		deps: ["react-colorful"],
		internalDeps: [
			"button",
			"input",
			"scroll-area",
			"separator",
			"sheet",
			"stack",
			"tabs",
			"textarea",
			"typography",
			"form-input",
			"form-slider",
		],
		tags: ["opinionated", "tooling"],
		postInstallNote: "Add <TokenConfigPanel /> to any page or layout. It renders a palette icon button that opens a slide-out token editor panel.",
	},
	"theme-injector": {
		name: "theme-injector",
		description: "Floating palette button fixed to the top-right corner of any page. Opens the full token config panel so you can live-edit design tokens without touching your layout.",
		files: [{ src: "templates/ui-opinionated/theme-injector.tsx", dest: "components/ui-opinionated/theme-injector.tsx" }],
		deps: [],
		internalDeps: ["token-config-panel"],
		tags: ["opinionated", "tooling"],
		postInstallNote: "Add <ThemeInjector /> to your root layout (e.g. layout.tsx or App.tsx). It floats in the top-right corner of every page.",
	},

};
