export interface ComponentEntry {
	name: string;
	description: string;
	files: { src: string; dest: string }[];
	deps: string[];
	internalDeps: string[];
	tags: string[];
}

export const registry: Record<string, ComponentEntry> = {
	// ─── Foundation ──────────────────────────────────────────────────────
	utils: {
		name: "utils",
		description: "Utility functions for className merging and focus ring styles",
		files: [{ src: "templates/lib/utils.ts", dest: "lib/utils.ts" }],
		deps: ["clsx", "tailwind-merge"],
		internalDeps: [],
		tags: ["foundation"],
	},
	styles: {
		name: "styles",
		description: "Base design system CSS styles and theme tokens",
		files: [{ src: "templates/styles/composable.css", dest: "styles/composable.css" }],
		deps: ["tailwindcss"],
		internalDeps: [],
		tags: ["foundation"],
	},
	"numeric-input": {
		name: "numeric-input",
		description: "Numeric input parsing and formatting utilities",
		files: [{ src: "templates/lib/numeric-input.ts", dest: "lib/numeric-input.ts" }],
		deps: [],
		internalDeps: [],
		tags: ["foundation"],
	},

	// ─── Hooks ───────────────────────────────────────────────────────────
	"use-mobile": {
		name: "use-mobile",
		description: "Hook to detect mobile viewport breakpoint",
		files: [{ src: "templates/hooks/use-mobile.ts", dest: "hooks/use-mobile.ts" }],
		deps: [],
		internalDeps: [],
		tags: ["hook"],
	},
	"use-breadcrumbs": {
		name: "use-breadcrumbs",
		description: "Hook to generate breadcrumbs from TanStack Router matches",
		files: [{ src: "templates/hooks/use-breadcrumbs.ts", dest: "hooks/use-breadcrumbs.ts" }],
		deps: ["@tanstack/react-router"],
		internalDeps: [],
		tags: ["hook"],
	},
	"use-numeric-input": {
		name: "use-numeric-input",
		description: "Hook for numeric input handling with sanitization and parsing",
		files: [{ src: "templates/hooks/use-numeric-input.ts", dest: "hooks/use-numeric-input.ts" }],
		deps: [],
		internalDeps: ["numeric-input"],
		tags: ["hook"],
	},

	// ─── Tooling ─────────────────────────────────────────────────────────
	"biome-ui-restricted": {
		name: "biome-ui-restricted",
		description: "Biome lint rule restricting direct UI component imports",
		files: [{ src: "templates/rules/biome-ui-restricted.json", dest: "rules/biome-ui-restricted.json" }],
		deps: [],
		internalDeps: [],
		tags: ["tooling"],
	},

	// ─── Primitive UI Components ─────────────────────────────────────────
	accordion: {
		name: "accordion",
		description: "Vertically collapsible content sections",
		files: [{ src: "templates/ui/accordion.tsx", dest: "components/ui/accordion.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	alert: {
		name: "alert",
		description: "Contextual feedback messages for user actions",
		files: [{ src: "templates/ui/alert.tsx", dest: "components/ui/alert.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"alert-dialog": {
		name: "alert-dialog",
		description: "Modal dialog for important confirmations",
		files: [{ src: "templates/ui/alert-dialog.tsx", dest: "components/ui/alert-dialog.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	"aspect-ratio": {
		name: "aspect-ratio",
		description: "Container that maintains a fixed aspect ratio",
		files: [{ src: "templates/ui/aspect-ratio.tsx", dest: "components/ui/aspect-ratio.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	avatar: {
		name: "avatar",
		description: "Circular image element for user profiles",
		files: [{ src: "templates/ui/avatar.tsx", dest: "components/ui/avatar.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	badge: {
		name: "badge",
		description: "Small status label with color variants",
		files: [{ src: "templates/ui/badge.tsx", dest: "components/ui/badge.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	breadcrumb: {
		name: "breadcrumb",
		description: "Navigation trail showing page hierarchy",
		files: [{ src: "templates/ui/breadcrumb.tsx", dest: "components/ui/breadcrumb.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	button: {
		name: "button",
		description: "Clickable button element with size and style variants",
		files: [{ src: "templates/ui/button.tsx", dest: "components/ui/button.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	calendar: {
		name: "calendar",
		description: "Date picker calendar powered by react-day-picker",
		files: [{ src: "templates/ui/calendar.tsx", dest: "components/ui/calendar.tsx" }],
		deps: ["lucide-react", "react-day-picker"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	card: {
		name: "card",
		description: "Bordered content container with header and footer slots",
		files: [{ src: "templates/ui/card.tsx", dest: "components/ui/card.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	carousel: {
		name: "carousel",
		description: "Horizontally scrollable content slider with navigation",
		files: [{ src: "templates/ui/carousel.tsx", dest: "components/ui/carousel.tsx" }],
		deps: ["embla-carousel-react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	checkbox: {
		name: "checkbox",
		description: "Toggle checkbox input with checked state",
		files: [{ src: "templates/ui/checkbox.tsx", dest: "components/ui/checkbox.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	collapsible: {
		name: "collapsible",
		description: "Expandable and collapsible content panel",
		files: [{ src: "templates/ui/collapsible.tsx", dest: "components/ui/collapsible.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: [],
		tags: ["primitive"],
	},
	combobox: {
		name: "combobox",
		description: "Searchable select dropdown with autocomplete",
		files: [{ src: "templates/ui/combobox.tsx", dest: "components/ui/combobox.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	container: {
		name: "container",
		description: "Centered max-width content wrapper",
		files: [{ src: "templates/ui/container.tsx", dest: "components/ui/container.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	dialog: {
		name: "dialog",
		description: "Modal dialog overlay with header, body, and footer",
		files: [{ src: "templates/ui/dialog.tsx", dest: "components/ui/dialog.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	"dropdown-menu": {
		name: "dropdown-menu",
		description: "Contextual menu triggered by a button",
		files: [{ src: "templates/ui/dropdown-menu.tsx", dest: "components/ui/dropdown-menu.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	dropzone: {
		name: "dropzone",
		description: "Drag-and-drop file upload area",
		files: [{ src: "templates/ui/dropzone.tsx", dest: "components/ui/dropzone.tsx" }],
		deps: ["lucide-react", "react-dropzone"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	empty: {
		name: "empty",
		description: "Empty state placeholder with icon, title, and description",
		files: [{ src: "templates/ui/empty.tsx", dest: "components/ui/empty.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	field: {
		name: "field",
		description: "Form field wrapper with label, description, and error slots",
		files: [{ src: "templates/ui/field.tsx", dest: "components/ui/field.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["label", "separator", "utils"],
		tags: ["primitive"],
	},
	grid: {
		name: "grid",
		description: "Responsive CSS grid layout component",
		files: [{ src: "templates/ui/grid.tsx", dest: "components/ui/grid.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	"hover-card": {
		name: "hover-card",
		description: "Preview card shown on hover",
		files: [{ src: "templates/ui/hover-card.tsx", dest: "components/ui/hover-card.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	icon: {
		name: "icon",
		description: "Icon wrapper with size and color variants",
		files: [{ src: "templates/ui/icon.tsx", dest: "components/ui/icon.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	input: {
		name: "input",
		description: "Text input field with focus ring styling",
		files: [{ src: "templates/ui/input.tsx", dest: "components/ui/input.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"input-group": {
		name: "input-group",
		description: "Input with addons, buttons, and text segments",
		files: [{ src: "templates/ui/input-group.tsx", dest: "components/ui/input-group.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["button", "input", "textarea", "utils"],
		tags: ["primitive"],
	},
	item: {
		name: "item",
		description: "Flexible list item with media, content, and actions",
		files: [{ src: "templates/ui/item.tsx", dest: "components/ui/item.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["separator", "utils"],
		tags: ["primitive"],
	},
	label: {
		name: "label",
		description: "Accessible text label for form controls",
		files: [{ src: "templates/ui/label.tsx", dest: "components/ui/label.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	pagination: {
		name: "pagination",
		description: "Page navigation with previous, next, and page links",
		files: [{ src: "templates/ui/pagination.tsx", dest: "components/ui/pagination.tsx" }],
		deps: ["lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	popover: {
		name: "popover",
		description: "Floating content panel anchored to a trigger",
		files: [{ src: "templates/ui/popover.tsx", dest: "components/ui/popover.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	progress: {
		name: "progress",
		description: "Horizontal progress bar indicator",
		files: [{ src: "templates/ui/progress.tsx", dest: "components/ui/progress.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"radio-group": {
		name: "radio-group",
		description: "Group of mutually exclusive radio options",
		files: [{ src: "templates/ui/radio-group.tsx", dest: "components/ui/radio-group.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	resizable: {
		name: "resizable",
		description: "Resizable split pane panels",
		files: [{ src: "templates/ui/resizable.tsx", dest: "components/ui/resizable.tsx" }],
		deps: ["react-resizable-panels"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	"scroll-area": {
		name: "scroll-area",
		description: "Custom scrollbar container with overflow handling",
		files: [{ src: "templates/ui/scroll-area.tsx", dest: "components/ui/scroll-area.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	select: {
		name: "select",
		description: "Dropdown select menu with scrollable options",
		files: [{ src: "templates/ui/select.tsx", dest: "components/ui/select.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	separator: {
		name: "separator",
		description: "Visual divider line between content sections",
		files: [{ src: "templates/ui/separator.tsx", dest: "components/ui/separator.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	sheet: {
		name: "sheet",
		description: "Slide-out panel from screen edge",
		files: [{ src: "templates/ui/sheet.tsx", dest: "components/ui/sheet.tsx" }],
		deps: ["@base-ui/react", "lucide-react"],
		internalDeps: ["button", "utils"],
		tags: ["primitive"],
	},
	sidebar: {
		name: "sidebar",
		description: "Application sidebar with collapsible navigation groups",
		files: [{ src: "templates/ui/sidebar.tsx", dest: "components/ui/sidebar.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority", "lucide-react"],
		internalDeps: ["button", "input", "separator", "sheet", "skeleton", "tooltip", "use-mobile", "utils"],
		tags: ["primitive"],
	},
	skeleton: {
		name: "skeleton",
		description: "Animated placeholder for loading content",
		files: [{ src: "templates/ui/skeleton.tsx", dest: "components/ui/skeleton.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	slider: {
		name: "slider",
		description: "Draggable range slider input",
		files: [{ src: "templates/ui/slider.tsx", dest: "components/ui/slider.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	sonner: {
		name: "sonner",
		description: "Toast notification system powered by Sonner",
		files: [{ src: "templates/ui/sonner.tsx", dest: "components/ui/sonner.tsx" }],
		deps: ["sonner"],
		internalDeps: [],
		tags: ["primitive"],
	},
	spacer: {
		name: "spacer",
		description: "Flexible whitespace component for spacing",
		files: [{ src: "templates/ui/spacer.tsx", dest: "components/ui/spacer.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	stack: {
		name: "stack",
		description: "Flex-based vertical or horizontal stack layout",
		files: [{ src: "templates/ui/stack.tsx", dest: "components/ui/stack.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	switch: {
		name: "switch",
		description: "Toggle switch for on/off states",
		files: [{ src: "templates/ui/switch.tsx", dest: "components/ui/switch.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	table: {
		name: "table",
		description: "Semantic HTML table with styled rows and cells",
		files: [{ src: "templates/ui/table.tsx", dest: "components/ui/table.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	tabs: {
		name: "tabs",
		description: "Tabbed content navigation with line and pill variants",
		files: [{ src: "templates/ui/tabs.tsx", dest: "components/ui/tabs.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	textarea: {
		name: "textarea",
		description: "Multi-line text input with auto-sizing",
		files: [{ src: "templates/ui/textarea.tsx", dest: "components/ui/textarea.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	toggle: {
		name: "toggle",
		description: "Pressable toggle button with active state",
		files: [{ src: "templates/ui/toggle.tsx", dest: "components/ui/toggle.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	tooltip: {
		name: "tooltip",
		description: "Informational popup on hover or focus",
		files: [{ src: "templates/ui/tooltip.tsx", dest: "components/ui/tooltip.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},
	typography: {
		name: "typography",
		description: "Polymorphic text component with typographic scale variants",
		files: [{ src: "templates/ui/typography.tsx", dest: "components/ui/typography.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive"],
	},

	receipt: {
		name: "receipt",
		description:
			"Receipt and ledger primitives: Divider, SectionLabel, Row, DataTable, Glyph, Ledger. Information-dense receipt/typewriter aesthetic with CVA variants and semantic tokens.",
		files: [{ src: "templates/ui/receipt.tsx", dest: "components/ui/receipt.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},
	"layout-bento": {
		name: "layout-bento",
		description:
			"Bento grid layout primitives: BentoGrid, BentoCell, BentoSplit, BentoLeader, BentoQuad, BentoTriple, CellGrid, CellRow, StatCell. Gap-as-border system with configurable --bento-gap, --bento-border-color, --bento-radius tokens.",
		files: [{ src: "templates/ui/layout-bento.tsx", dest: "components/ui/layout-bento.tsx" }],
		deps: [],
		internalDeps: ["utils"],
		tags: ["primitive", "layout"],
	},

	// ─── Opinionated UI Components ───────────────────────────────────────
	"accordion-opinionated": {
		name: "accordion-opinionated",
		description: "Opinionated accordion with items array API",
		files: [{ src: "templates/ui-opinionated/accordion.tsx", dest: "components/ui-opinionated/accordion.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["accordion"],
		tags: ["opinionated"],
	},
	"alert-opinionated": {
		name: "alert-opinionated",
		description: "Opinionated alert with type-based icon and variant mapping",
		files: [{ src: "templates/ui-opinionated/alert.tsx", dest: "components/ui-opinionated/alert.tsx" }],
		deps: ["lucide-react"],
		internalDeps: ["alert"],
		tags: ["opinionated"],
	},
	"badge-opinionated": {
		name: "badge-opinionated",
		description: "Opinionated badge with simplified variant prop",
		files: [{ src: "templates/ui-opinionated/badge.tsx", dest: "components/ui-opinionated/badge.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["badge"],
		tags: ["opinionated"],
	},
	"button-opinionated": {
		name: "button-opinionated",
		description: "Opinionated button with loading spinner support",
		files: [{ src: "templates/ui-opinionated/button.tsx", dest: "components/ui-opinionated/button.tsx" }],
		deps: ["class-variance-authority", "lucide-react"],
		internalDeps: ["button"],
		tags: ["opinionated"],
	},
	"card-opinionated": {
		name: "card-opinionated",
		description: "Opinionated card with title, description, action, and footer props",
		files: [{ src: "templates/ui-opinionated/card.tsx", dest: "components/ui-opinionated/card.tsx" }],
		deps: [],
		internalDeps: ["card"],
		tags: ["opinionated"],
	},
	"collapsible-opinionated": {
		name: "collapsible-opinionated",
		description: "Opinionated collapsible with trigger prop and chevron icons",
		files: [{ src: "templates/ui-opinionated/collapsible.tsx", dest: "components/ui-opinionated/collapsible.tsx" }],
		deps: ["lucide-react"],
		internalDeps: ["collapsible", "utils"],
		tags: ["opinionated"],
	},
	"dialog-opinionated": {
		name: "dialog-opinionated",
		description: "Opinionated modal dialog with trigger, title, and footer props",
		files: [{ src: "templates/ui-opinionated/dialog.tsx", dest: "components/ui-opinionated/dialog.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["dialog"],
		tags: ["opinionated"],
	},
	"empty-opinionated": {
		name: "empty-opinionated",
		description: "Opinionated empty state with table row variant",
		files: [{ src: "templates/ui-opinionated/empty.tsx", dest: "components/ui-opinionated/empty.tsx" }],
		deps: [],
		internalDeps: ["empty", "table-opinionated", "typography-opinionated"],
		tags: ["opinionated"],
	},
	"form-calendar-popover": {
		name: "form-calendar-popover",
		description: "Date picker field with calendar popover",
		files: [{ src: "templates/ui-opinionated/form-calendar-popover.tsx", dest: "components/ui-opinionated/form-calendar-popover.tsx" }],
		deps: ["class-variance-authority", "lucide-react"],
		internalDeps: ["button", "calendar", "field", "popover", "utils"],
		tags: ["opinionated", "form"],
	},
	"form-checkbox": {
		name: "form-checkbox",
		description: "Checkbox field with label, description, and error handling",
		files: [{ src: "templates/ui-opinionated/form-checkbox.tsx", dest: "components/ui-opinionated/form-checkbox.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["checkbox", "field"],
		tags: ["opinionated", "form"],
	},
	"form-combobox": {
		name: "form-combobox",
		description: "Searchable select field with options array API",
		files: [{ src: "templates/ui-opinionated/form-combobox.tsx", dest: "components/ui-opinionated/form-combobox.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["combobox", "field"],
		tags: ["opinionated", "form"],
	},
	"form-date-of-birth": {
		name: "form-date-of-birth",
		description: "Three-field date of birth input with auto-advance",
		files: [{ src: "templates/ui-opinionated/form-date-of-birth.tsx", dest: "components/ui-opinionated/form-date-of-birth.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "input", "utils"],
		tags: ["opinionated", "form"],
	},
	"form-dropzone": {
		name: "form-dropzone",
		description: "Single file upload field with drag-and-drop",
		files: [{ src: "templates/ui-opinionated/form-dropzone.tsx", dest: "components/ui-opinionated/form-dropzone.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["dropzone", "field"],
		tags: ["opinionated", "form"],
	},
	"form-input": {
		name: "form-input",
		description: "Text input field with label, error, and numeric mode support",
		files: [{ src: "templates/ui-opinionated/form-input.tsx", dest: "components/ui-opinionated/form-input.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "input", "use-numeric-input"],
		tags: ["opinionated", "form"],
	},
	"form-input-group": {
		name: "form-input-group",
		description: "Input group field with addons, buttons, and numeric support",
		files: [{ src: "templates/ui-opinionated/form-input-group.tsx", dest: "components/ui-opinionated/form-input-group.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "input-group", "use-numeric-input"],
		tags: ["opinionated", "form"],
	},
	"form-multi-combobox": {
		name: "form-multi-combobox",
		description: "Multi-select combobox field with chip display",
		files: [{ src: "templates/ui-opinionated/form-multi-combobox.tsx", dest: "components/ui-opinionated/form-multi-combobox.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["combobox", "field"],
		tags: ["opinionated", "form"],
	},
	"form-multi-dropzone": {
		name: "form-multi-dropzone",
		description: "Multi-file upload field with drag-and-drop",
		files: [{ src: "templates/ui-opinionated/form-multi-dropzone.tsx", dest: "components/ui-opinionated/form-multi-dropzone.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["dropzone", "field"],
		tags: ["opinionated", "form"],
	},
	"form-radiogroup": {
		name: "form-radiogroup",
		description: "Radio group field with options array API",
		files: [{ src: "templates/ui-opinionated/form-radiogroup.tsx", dest: "components/ui-opinionated/form-radiogroup.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["field", "label", "radio-group"],
		tags: ["opinionated", "form"],
	},
	"form-select": {
		name: "form-select",
		description: "Select dropdown field with options array API",
		files: [{ src: "templates/ui-opinionated/form-select.tsx", dest: "components/ui-opinionated/form-select.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "select"],
		tags: ["opinionated", "form"],
	},
	"form-slider": {
		name: "form-slider",
		description: "Slider field with label, value display, and error handling",
		files: [{ src: "templates/ui-opinionated/form-slider.tsx", dest: "components/ui-opinionated/form-slider.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["field", "slider"],
		tags: ["opinionated", "form"],
	},
	"form-switch": {
		name: "form-switch",
		description: "Switch toggle field with label and description",
		files: [{ src: "templates/ui-opinionated/form-switch.tsx", dest: "components/ui-opinionated/form-switch.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["field", "switch"],
		tags: ["opinionated", "form"],
	},
	"form-textarea": {
		name: "form-textarea",
		description: "Textarea field with label, description, and error handling",
		files: [{ src: "templates/ui-opinionated/form-textarea.tsx", dest: "components/ui-opinionated/form-textarea.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["field", "textarea"],
		tags: ["opinionated", "form"],
	},
	"item-opinionated": {
		name: "item-opinionated",
		description: "Opinionated list item with title, description, icon, and actions props",
		files: [{ src: "templates/ui-opinionated/item.tsx", dest: "components/ui-opinionated/item.tsx" }],
		deps: ["class-variance-authority"],
		internalDeps: ["item", "typography-opinionated"],
		tags: ["opinionated"],
	},
	"pagination-opinionated": {
		name: "pagination-opinionated",
		description: "Opinionated pagination with currentPage and totalPages API",
		files: [{ src: "templates/ui-opinionated/pagination.tsx", dest: "components/ui-opinionated/pagination.tsx" }],
		deps: [],
		internalDeps: ["pagination"],
		tags: ["opinionated"],
	},
	"resizable-opinionated": {
		name: "resizable-opinionated",
		description: "Re-exported resizable panel components",
		files: [{ src: "templates/ui-opinionated/resizable.tsx", dest: "components/ui-opinionated/resizable.tsx" }],
		deps: [],
		internalDeps: ["resizable"],
		tags: ["opinionated"],
	},
	"scroll-area-opinionated": {
		name: "scroll-area-opinionated",
		description: "Opinionated scroll area with maxHeight presets",
		files: [{ src: "templates/ui-opinionated/scroll-area.tsx", dest: "components/ui-opinionated/scroll-area.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["scroll-area", "utils"],
		tags: ["opinionated"],
	},
	"sheet-opinionated": {
		name: "sheet-opinionated",
		description: "Opinionated sheet with trigger, title, and footer props",
		files: [{ src: "templates/ui-opinionated/sheet.tsx", dest: "components/ui-opinionated/sheet.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["sheet"],
		tags: ["opinionated"],
	},
	"skeleton-opinionated": {
		name: "skeleton-opinionated",
		description: "Opinionated skeleton with shape variants and preset helpers",
		files: [{ src: "templates/ui-opinionated/skeleton.tsx", dest: "components/ui-opinionated/skeleton.tsx" }],
		deps: [],
		internalDeps: ["skeleton", "utils"],
		tags: ["opinionated"],
	},
	"table-opinionated": {
		name: "table-opinionated",
		description: "Re-exported table components for opinionated layer",
		files: [{ src: "templates/ui-opinionated/table.tsx", dest: "components/ui-opinionated/table.tsx" }],
		deps: [],
		internalDeps: ["table"],
		tags: ["opinionated"],
	},
	"tabs-opinionated": {
		name: "tabs-opinionated",
		description: "Opinionated tabs with items array API",
		files: [{ src: "templates/ui-opinionated/tabs.tsx", dest: "components/ui-opinionated/tabs.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["tabs"],
		tags: ["opinionated"],
	},
	"toggle-opinionated": {
		name: "toggle-opinionated",
		description: "Opinionated toggle with left and right icon slots",
		files: [{ src: "templates/ui-opinionated/toggle.tsx", dest: "components/ui-opinionated/toggle.tsx" }],
		deps: ["@base-ui/react", "class-variance-authority"],
		internalDeps: ["toggle"],
		tags: ["opinionated"],
	},
	"tooltip-opinionated": {
		name: "tooltip-opinionated",
		description: "Opinionated tooltip with content prop shorthand",
		files: [{ src: "templates/ui-opinionated/tooltip.tsx", dest: "components/ui-opinionated/tooltip.tsx" }],
		deps: ["@base-ui/react"],
		internalDeps: ["tooltip"],
		tags: ["opinionated"],
	},
	"typography-opinionated": {
		name: "typography-opinionated",
		description: "Re-exported typography component for opinionated layer",
		files: [{ src: "templates/ui-opinionated/typography.tsx", dest: "components/ui-opinionated/typography.tsx" }],
		deps: [],
		internalDeps: ["typography"],
		tags: ["opinionated"],
	},
};
