import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { aiElementPageMeta } from '../showcase/src/ai-elements-pages'
import { showcasePageMeta } from '../showcase/src/showcase-pages'

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const routesRoot = join(repoRoot, 'showcase/src/routes')

for (const page of showcasePageMeta) {
	const routeFile = join(routesRoot, page.slug, 'index.tsx')
	const routePath = `${page.path}/`

	mkdirSync(dirname(routeFile), { recursive: true })
	writeFileSync(
		routeFile,
		`// Generated by scripts/generate-showcase-routes.ts.\n` +
			`import { createFileRoute } from '@tanstack/react-router'\n` +
			`import { ComponentRoute } from '@/component-route'\n\n` +
			`export const Route = createFileRoute('${routePath}')({\n` +
			`\tcomponent: () => <ComponentRoute slug="${page.slug}" />,\n` +
			`})\n`,
	)
}

for (const page of aiElementPageMeta) {
	const routeFile = join(routesRoot, 'ai-elements', page.slug, 'index.tsx')
	const routePath = `${page.path}/`

	mkdirSync(dirname(routeFile), { recursive: true })
	writeFileSync(
		routeFile,
		`// Generated by scripts/generate-showcase-routes.ts.\n` +
			`import { createFileRoute } from '@tanstack/react-router'\n` +
			`import { AIElementRoute } from '@/ai-element-route'\n\n` +
			`export const Route = createFileRoute('${routePath}')({\n` +
			`\tcomponent: () => <AIElementRoute slug="${page.slug}" />,\n` +
			`})\n`,
	)
}

console.log(
	`Generated ${showcasePageMeta.length} showcase route files and ${aiElementPageMeta.length} AI element route files.`,
)
